                <div class="container">          
                  <header>                  
                    <h1> <strong>ProfileIT</strong> Sistema Colaborativo</h1>
                    <h2>Otimize seus Relacionamnetos Profissionais</h2>         

                    <div class="support-note">
                      <span class="note-ie">Sorry, only modern browsers.</span>
                    </div>
                    
                  </header>
                  
                  <section class="main">
					         <div class="panel-error">
	                   <p><img src="<?php echo IMG; ?>NotFound.png"></p>
					           <a href="home"><h4>Return to Home Page</h4></a>
					        </div>
                  </section>                  
                </div>