	   <!-- ==============================================
	   Layout Content Site (Definição de Layout)
      ====================================-->
		<div class="layout">
			<main>
				<?php echo (isset($this->alert) ? $this->alert : ''); ?>
				<section class="update-menu">
					<div class="container">
						<div class="options-menu">
							<a class="item-central pointer-cursor" href="home.html">
								<img src="<?php echo IMAGES; ?>curriculo-tag-miolo.png" alt="Curriculo TAG">
							</a>

							<a class="icone-lapis pointer-cursor" data-tooltip="Visualizar Alterações" href="<?php echo BASE . 'usuario/'; ?>" >
								<i class="fa fa-refresh" alt="Edit Curriculo"></i>
							</a>

							<a class="icone-codigo pointer-cursor" href="<?php echo BASE . 'home/'; ?>" data-tooltip="I’m the tooltip text.">
								<i class="fa fa-code" alt="Edit Curriculo"></i>
							</a>

							<a class="icone-coracao pointer-cursor" data-tooltip="Atualizar Questionário" href="<?php echo BASE . 'upquestionario/responder/'; ?>">
								<i class="fa fa-file-text" alt="Alterar Questionário" ></i>
							</a>

							<a class="icone-compartilhar pointer-cursor" data-tooltip="Encontrar Usuário." href="home.html">
								<i class="fa fa-users" alt="Localizar Usuário" ></i>
							</a>
						</div><!-- </options-menu> -->
						<div class="row">
							<div class="col-md-12">

							</div>
						</div>
					</div><!-- </container> -->
				</section><!-- </update-menu> Section de Menu de Acessos Rápidos-->

				<section class="update-access" id="access">
					<div class="container">
						<div class="row">
							<form id="access-form" enctype="multipart/form-data" action="<?php echo BASE; ?>temp/editar/" method="post">
								<div class="col-sm-6 infos">
									<div class="row">
										<div class="col-sm-12">
											<div class="quadro1">
												<picture-profile>
													<div class="picture-top">
									               <?php
									                  if (!is_null($view_user->image)) {
									                     echo '<img class="avatar-lg wow bounceIn" src="' . BASE . 'public/uploads/users/' . $view_user->id . '/' . $view_user->image . '" width="160">';
									                   }
									                  else{
									                     echo '<img class="avatar-lg wow bounceIn" src="' . BASE . 'public/uploads/users/' . 'default' . '/' . 'default.png' . '" width="160">';
									                  }
									               ?>
													</div>
													<div class="picture-bottom">
														<div class="row">
															<div class="col-md-12">
																<div class="box-input">
																	<input type="file" name="file-1" id="file-1" class="upFile upFile-1" data-multiple-caption="{count} files selected" multiple />
																	<label for="file-1"><svg xmlns="http://www.w3.org/2000/svg" width="20" height="17" viewBox="0 0 20 17"><path d="M10 0l-5.2 4.9h3.3v5.1h3.8v-5.1h3.3l-5.2-4.9zm9.3 11.5l-3.2-2.1h-2l3.4 2.6h-3.5c-.1 0-.2.1-.2.1l-.8 2.3h-6l-.8-2.2c-.1-.1-.1-.2-.2-.2h-3.6l3.4-2.6h-2l-3.2 2.1c-.4.3-.7 1-.6 1.5l.6 3.1c.1.5.7.9 1.2.9h16.3c.6 0 1.1-.4 1.3-.9l.6-3.1c.1-.5-.2-1.2-.7-1.5z"/></svg> <span>Selecionar Foto</span></label>
																</div><!-- </box-input> -->
																<div class="msgFront" name="msgFront">
								               				<span></span>
								            				</div>
															</div><!-- </col-md-12> -->
														</div><!-- </row> -->
														<div class="col-sm-12">
															<div class="separator"></div>
															<h1><strong><?php echo $view_user->name; ?></strong></h1>
															<p>#<?php echo (!$view_preference) ? null : $view_preference->function ; ?> #<?php echo (!$view_preference) ? null : $view_preference->area ; ?> #<?php echo (!$view_preference) ? null : $view_preference->especially ; ?></p>
															<div class="separator"></div>
														</div>
													</div>
												</picture-profile>
											</div><!-- </quadro1> -->
										</div><!-- </col-sm-12> -->
									</div><!-- </row> -->
								</div><!-- </col-sm-6 infos> -->
								<div class="col-sm-6">
									<div class="quadro">
										<h1>Dados de Acesso e Login</h1>
											<div class="cols">
												<div class="col">
													<div class="form-group">
														<input type="text" name="usernameAccess" id="usernameAccess"  placeholder="usuário"  value="<?php echo $view_user->username;?>">
													</div>
												</div>
												<div class="col">
													<div class="form-group">
														<input type="text" name="emailAccess" id="emailAccess" placeholder="e-mail"  value="<?php echo $view_user->email;?>">
													</div>
												</div>
												<div class="col">
													<div class="form-group">
														<input type="password" id="password" name="password" placeholder="******" />
													</div>
												</div>
												<div class="col">
													<div class="form-group">
														<input type="password" id="confirmPassword" name="confirmPassword" placeholder="Confirmar Senha" />
														<div class="help-block with-errors"></div>
													</div>
												</div>
												<div class="md-padder text-right">
													<button type="submit" class="btn btn-primary btn-lg margin-btm-30" data-tooltip="Alterar Acessos ao Sistema." > <i class="fa fa-user"></i> <span class="hidden-xs"> Atualizar </span> Acesso </button>
												</div>
											</div><!-- </cols> -->
									</div><!-- </quadro> -->
								</div><!-- </col-sm-6 infos> -->
							</form>
						</div><!-- </row> -->
					</div><!-- </container> -->
				</section><!-- </update-access> -->
				<!-- ==============================================
			    Update Midias Sociais (Edit Peronal Information)
			   =============================================== -->
			   <section class="update-social" id="social">
			    	<div class="container">
			    		<!-- TitleSection -->
			    		<div class="cols">
			    			<div class="title-section" id="shortcodes">
			    				<h2 class="title">Informações de Midias Sociais<span class="cursor-tag">_</span></h2>
			    				<h3 class="title-description">Redes Sociais e Contatos.</h3>
			    			</div>
			    		</div>
			    		<!-- End Title Section -->
			    		<div class="row">
							<form class="form-social" id="form-social" action="<?php echo BASE; ?>perfil/upSocial/" method="post">
			    				<div class="col-sm-6 infos">
			    					<div class="row">
			    						<div class="col-sm-12">
			    							<div class="quadro30">
			    								<div class="col">
			    									<div class="form-group">
			    										<span class="icone-campo"><i class="fa fa-facebook fa-2x"></i></span>
			    									</div>
			    								</div>
			    								<div class="col">
			    									<div class="form-group">
			    										<input name="facebook" placeholder="facebook" type="text" value="<?php echo $view_user->network->facebook; ?>" >
			    									</div>
			    								</div>

			    								<div class="col">
			    									<div class="form-group">
			    										<span class="icone-campo"><i class="fa fa-linkedin fa-2x"></i></span>
			    									</div>
			    								</div>
			    								<div class="col">
			    									<div class="form-group">
			    										<input type="text" name="linkedin" placeholder="LinkedIn" value="<?php echo $view_user->network->linkedin; ?>">
			    									</div>
			    								</div>

			    								<div class="col">
			    									<div class="form-group">
			    										<span class="icone-campo"><i class="fa fa-twitter fa-2x"></i></span>
			    									</div>
			    								</div>
			    								<div class="col">
			    									<div class="form-group">
			    										<input type="text" name="twitter" placeholder="Twitter" value="<?php echo $view_user->network->twitter; ?>" >
			    									</div>
			    								</div>
			    							</div><!-- </quadro30> -->
			    						</div><!-- </col-sm-12> -->
			    					</div><!-- </row> -->
			    				</div><!-- </col-sm-6 infos> -->
			    				<div class="col-sm-6">
			    					<div class="quadro31">
			    						<div class="col">
			    							<div class="form-group">
			    								<span class="icone-campo"><i class="fa fa-instagram fa-2x"></i></span>
			    							</div>
			    						</div>
			    						<div class="col">
			    							<div class="form-group">
			    								<input type="text" name="instagram" placeholder="Instagram" value="<?php echo $view_user->network->instagram; ?>" >
			    							</div>
			    						</div>
			    						<div class="col">
			    							<div class="form-group">
			    								<span class="icone-campo"><i class="fa fa-github fa-2x"></i></span>
			    							</div>
			    						</div>
			    						<div class="col">
			    							<div class="form-group">
			    								<input type="text"  name="github" placeholder="GitHub" value="<?php echo $view_user->network->github; ?>">
			    							</div>
			    						</div>
			    						<div class="col">
			    							<div class="form-group">
			    								<span class="icone-campo"><i class="fa fa-globe fa-2x"></i></span>
			    							</div>
			    						</div>
			    						<div class="col">
			    							<div class="form-group">
			    								<input type="text"  name="web" placeholder="Seu site ou dominio" value="<?php echo $view_user->network->web; ?>" >
			    							</div>
			    						</div>
			    					</div>
			    					<div class="md-padder text-right">
			    						<button type="submit" class="btn btn-primary btn-lg margin-btm-30" data-tooltip="Social media information." href="update.html" target="_blank"> <i class="fa fa-cloud"></i> <span class="hidden-xs"> Atualizar </span> Mídias </button>
			    					</div><!-- </quadro31> -->
			    				</div><!-- </col-sm-6> -->
			    			</form><!-- </form-social> -->
			    		</div><!-- </row> -->
			    	</div><!-- </container> -->
			   </section><!-- </update-social> -->
				<!-- ==============================================
			   Históric (Historico Profissional e Academico)
			   =============================================== -->
			   <section class="update-historic" id="historic">
			    	<div class="container">
			    		<!-- TitleSection -->
			    		<div class="cols">
			    			<div class="title-section">
			    				<h2 class="title">Histórico Acadêmico e Profissional<span class="cursor-tag">_</span></h2>
			    				<h3 class="title-description">Experiências e Formações.</h3>
			    			</div>
			    		</div>

			    		<div class="row">
			    			<div class="col-md-12 text-center">
			    				<div class="row">
			    					<div class="col-md-6 col-xs-12">
			    						<h3 class="spec">Histórico Profissional</h3>
			    						<table>
			    							<thead>
			    								<tr>
			    									<th>Empresa</th>
			    									<th>Função</th>
			    									<th>Admissão</th>
			    									<th>Saída</th>
			    									<th>Editar</th>
			    									<th>Delete</th>
			    								</tr>
			    							</thead>
			    							<tbody>
												<?php
												foreach ($view_user->professionals as $professional):
												?>
				    								<tr>
				    									<td class="historic"><?php echo $professional->company ?></td>
				    									<td class="historic"><?php echo $professional->function ?></td>
				    									<td class="historic"><?php echo $professional->date_entry->format('Y') ?></td>
				    									<td class="historic">
															<?php
															if ($professional->date_out == null) {
																echo ('Atual');
															}
															else echo $professional->date_out->format('Y');
															?>
				    									</td>
				    									<td class="historic">
															<button type="button" onclick="sendUpProfessional(<?php echo $professional->id ?>)" class="btn btn-xs btn-warning" data-toggle="modal" data-target="#modalEditarProfessional">
																<i class="fa fa-unlock"></i> Editar
															</button>
				    									</td>
				    									<td class="historic">
				    										<button type="button" value="<?php echo $professional->id ?>" onclick="sendDelProfessional(this.value, '<?php echo $view_user->name?>')" class="btn btn-xs btn-danger">
				    											<i class="fa fa-trash"></i> Delete
				    										</button>
				    									</td>
				    								</tr>
												<?php
												endforeach;
												?>
			    							</tbody>
			    						</table>
										<div class="separator"></div>
	    								<div class="md-padder text-center">
		 									<button id="addProfessional" type="button" data-tooltip="Inclusão de Experiência" class="btn btn-primary btn-lg margin-btm-30" data-toggle="modal" data-target="#formProfessional"> <i class="fa fa-cloud" aria-hidden="true"></i> <span class="hidden-xs"> Adicionar </span> Experiência </button>
		 								</div>
			    					</div><!-- </col-sm-12> -->

			    					<div class="col-md-6 col-xs-12">
			    						<h3 class="spec">Histórico Acadêmico</h3>
			    						<table>
			    							<thead>
			    								<tr>
			    									<th>Instituição</th>
			    									<th>Curso</th>
			    									<th>Nível</th>
			    									<th>Conclusão</th>
			    									<th>Editar</th>
			    									<th>Delete</th>
			    								</tr>
			    							</thead>
			    							<tbody>
			    								<?php
			    									foreach ($view_user->academics as $academic):
			    								?>
			    								<tr>
			    									<td class="academic"><?php echo $academic->institution ?></td>
			    									<td class="academic"><?php echo $academic->course ?></td>
			    									<td class="academic"><?php echo $academic->level ?></td>
			    									<td class="academic">

														<?php if ($academic->date_conclusion === NULL) : ?>
															-
														<?php else: ?>
															<?php echo $academic->date_conclusion->format('Y') ?>
														<?php endif; ?>
			    									</td>

			    									<td class="academic">
														<?php if ($academic->status === 3) : ?>
															<a href="" class="btn btn-xs btn-success disabled">
																<i class="fa fa-lock"></i> Concluído
															</a>
														<?php else: ?>
															<button type="button" onclick="sendUpAcademic(<?php echo $academic->id ?>)" class="btn btn-xs btn-warning" data-toggle="modal" data-target="#modal1">
																<i class="fa fa-unlock"></i> Cursando
															</button>
														<?php endif; ?>
			    									</td>
			    									<td class="academic">
			    										<button type="button" value="<?php echo $academic->id ?>" onclick="sendDelAcademic(this.value, '<?php echo $view_user->name?>')" class="btn btn-xs btn-danger">
			    											<i class="fa fa-trash"></i> Delete
			    										</button>
			    									</td>
			    								</tr>
			    								<?php
			    									endforeach;
			    								?>
			    							</tbody>
			    						</table>
		         					<div class="separator"></div>
		         					<div class="md-padder text-center">
		 									<button id="addExperiencia" type="button" data-tooltip="Add Formação Acadêmica" class="btn btn-primary btn-lg margin-btm-30" data-toggle="modal" data-target="#formAcademic"> <i class="fa fa-graduation-cap"></i> <span class="hidden-xs"> Adicionar </span> Formação </button>
		 								</div>
			    					</div><!-- </col-sm-12> -->
			    				</div><!-- </row> -->
			    			</div><!-- </col-sm-12> -->
			    		</div><!-- </row> -->
			    	</div><!-- </container> -->
			   </section><!--</update-historic> -->
				<!-- ==============================================
	    		Skill Técnico (Technical Skill)
	    		=============================================== -->
	 			<section class="update-skill" id="skills">
	 				<div class="container">
	 					<!-- TitleSection -->
	 					<div class="cols">
	 						<div class="title-section">
	 							<h2 class="title">Qualificações<span class="cursor-tag">_</span></h2>
	 							<h3 class="title-description">Sumário de qualificações e competênciais.</h3>
	 						</div>
	 					</div>
	 					<!-- End Title Section -->
						<div class="row">
						<!--
	 					*	Atualizar Competências Atuais
	 					*-->
							<div class="col-md-6">
								<div class="row">
									<div class="col-md-12">
										<form method="POST" class="form-horizontal wrapper-repeater" role="form">
											<fieldset>
												<legend>Atualizar Competências Atuais</legend>
												<?php
													foreach ($view_user->competencies as $competency):
												?>
													<div class="row">
														<div class="col-xs-12 col-sm-8 col-md-7 col-lg-6 wow flipInx" data-wow-delay="0.3s">
															<div class="skill-bar">
														    	<ul>
																	<li>
																		<div class="bar" data-value="" style="width: <?php echo $competency->level ?>0%;">
																			<h5><?php echo $competency->qualification->qualification ?></h5>
																		</div>
																		<span><?php echo $competency->level ?> / 10</span>
																	</li>
														      </ul><!-- </ul> Lista de Barras Skill -->
														   </div><!-- </skill-bar> -->
														</div><!-- </col-md-5 col-sm-12> -->

														<div class="col-xs-2 col-sm-4 col-md-2 col-lg-2 selectUpSkill wow flipInx">
															<select name="make" id="level<?php echo $competency->id ?>" class="form-control">
																<option value="1" <?php ($competency->level == "1") ? print "selected" : ""; ?>>
																	1
																</option>
																<option value="2" <?php ($competency->level == '2') ? print "selected" : ""; ?>>
																	2
																</option>
																<option value="3" <?php ($competency->level == '3') ? print "selected" : ""; ?>>
																	3
																</option>
																<option value="4" <?php ($competency->level == '4') ? print "selected" : ""; ?>>
																	4
																</option>
																<option value="5" <?php ($competency->level == '5') ? print "selected" : ""; ?> >
																	5
																</option>
																<option value="6" <?php ($competency->level == '6') ? print "selected" : ""; ?>>
																	6
																</option>
																<option value="7" <?php ($competency->level == '7') ? print "selected" : ""; ?>>
																	7
																</option>
																<option value="8" <?php ($competency->level == '8') ? print "selected" : ""; ?>>
																	8
																</option>
																<option value="9" <?php ($competency->level == '9') ? print "selected" : ""; ?>>
																	9
																</option>
																<option value="10" <?php ($competency->level == '10') ? print "selected" : ""; ?>>
																	10
																</option>
															</select>
					         						</div><!-- </col-md-1> -->
														<div class="col-xs-2 col-sm-6 col-md-1 col-lg-2 text-right wow flipInx">
															<div class="boxButton">
					                        			<button type="button" value="level<?php echo $competency->id ?>" onclick="sendEdit(this.value, <?php echo $competency->id ?>, <?php echo $competency->level?> ,'<?php echo $view_user->name?>')" class="btn btn-primary btn-sm margin-btm-30" id="btnUP">
				                        					<i class="fa fa-pencil"></i>
				                        					<span>Editar</span>
				                        				</button>
			                        				</div>
														</div>
														<div class="col-xs-2 col-sm-6 col-md-1 col-lg-2 wow flipInx">
															<div class="boxButton">
																<button type="button" value="<?php echo $competency->id ?>" onclick="sendDel(this.value, '<?php echo $view_user->name?>')" class="btn btn-primary btn-sm margin-btm-30" id="btnDel">
				                        					<i class="fa fa-trash"></i>
				                        					<span>Delete</span>
				                        				</button>
				                        			</div>
														</div>
													</div><!-- </row> -->
												<?php	endforeach
												?>
											</fieldset>
										</form>
									</div><!-- </col-md-12> -->
								</div><!-- </row> -->
							</div><!-- </col-md-6> -->
		 					<!--
		 					*	Add Novas Competências
		 					*-->
							<div class="col-md-6">
								<div class="row">
									<div class="col-md-12">
										<form method="POST" action="<?php echo BASE; ?>perfil/addcompetency/"  name="addcompetency" id="addcompetency" class="form-horizontal wrapper-repeater addcompetency" >
											<fieldset id="addCompetencyField">
												<legend>+ Novas Competências</legend>
												<div class="row">
													<div class="boxTitles">
														<div class="col-md-7">
															<label>Competências</label>
														</div>
														<div class="col-md-3">
															<label>Nível</label>
														</div>
													</div>
												</div><!-- </row> -->
												<div id="testeRepeater">
						      					<div class="competencies-group">
							      					<div class="row">
															<div class="col-xs-8 col-sm-7 col-md-7 col-lg-7">
								   							<div class="box-input">
								   								<label for="competency_0_0" data-pattern-text="Competência +=1:" class="sr-only" >Competência 1:</label>
								   								<select class="form-control border input" name="competency[0][qualification]" id="competency_0_qualification" data-pattern-name="competency[++][qualification]" data-pattern-id="competency_++qualification">
			 															<option class="opt-placeholder" value="-1" selected="">Competência</option>
					 													<optgroup label="Microsoft">
					 													<?php foreach ($view_qualificacoes as $qualificacao) :
					 													if ($qualificacao->domain == 'Microsoft') : ?>
						 													<option value="<?php echo $qualificacao->id ?>">
						 														<?php echo $qualificacao->qualification ?>
						 													</option>
						 												<?php endif;
						 												endforeach; ?>
					 													</optgroup>
					 													<optgroup label="Linux">
					 													<?php foreach ($view_qualificacoes as $qualificacao) :
					 													if ($qualificacao->domain == 'Linux') : ?>
						 													<option value="<?php echo $qualificacao->id?>">
						 														<?php echo $qualificacao->qualification ?>
						 													</option>
						 												<?php endif;
						 												endforeach; ?>
					 													</optgroup>
					 													<optgroup label="Especializações">
					 													<?php foreach ($view_qualificacoes as $qualificacao) :
					 													if ($qualificacao->domain == 'Especialização') : ?>
						 													<option value="<?php echo $qualificacao->qualification ?>">
						 														<?php echo $qualificacao->qualification ?>
						 													</option>
						 												<?php endif;
						 												endforeach; ?>
					 													</optgroup>
					 													<optgroup label="Processos ">
					 													<?php foreach ($view_qualificacoes as $qualificacao) :
					 													if ($qualificacao->domain == 'Processos') : ?>
						 													<option value="<?php echo $qualificacao->qualification ?>">
						 														<?php echo $qualificacao->qualification ?>
						 													</option>
						 												<?php endif;
						 												endforeach; ?>
					 													</optgroup>
				 													</select>
								   							</div><!-- </box-input> -->
								      					</div><!-- </col-md-5> -->
															<div class="col-xs-2 col-sm-2 col-md-3 col-lg-3">
			 													<div class="box-input">
			 														<select name="competency[0][level]" id="competency_0_level" data-pattern-name="competency[++][level]" data-pattern-id="competency_++level" class="form-control">
					 													<option class="opt-placeholder" value="-1" selected="">Nivel</option>
					 													<option value="1">
					 														1
					 													</option>
					 													<option value="2">
					 														2
					 													</option>
					 													<option value="3">
					 														3
					 													</option>
					 													<option value="4">
					 														4
					 													</option>
					 													<option value="5">
					 														5
					 													</option>
					 													<option value="6">
					 														6
					 													</option>
					 													<option value="7">
					 														7
					 													</option>
					 													<option value="8">
					 														8
					 													</option>
					 													<option value="9">
					 														9
					 													</option>
					 													<option value="10">
					 														10
					 													</option>
				 													</select>
			 													</div>
							         					</div><!-- </col-md-1> -->

															<!-- Add a remove button for the item. If one didn't exist, it would be added to overall group -->
								      					<div class="col-xs-2 col-sm-2 col-md-2 col-lg-2 wow flipInx">
																<div class="box-input form-group"">
																	<span data-repeater-delete class="btn btn-danger btn-sm academic a-btnRemove">
																		<span class="glyphicon glyphicon-remove"></span> Delete
																	</span>
																</div>
	 														</div>

														</div><!-- </row> -->
													</div>	<!-- </competency-group> -->

													<!--
														Botão Add do Repeater
													-->
													<div class="row">
														<div class="col-md-4">
															<div class="form-group">
																<span data-tooltip="Include new skills" name="add-academic" id="add-academic" class="btn btn-info btn-md academic a-btnAdd">
																	<span class="glyphicon glyphicon-plus"></span> add
																</span>
															</div>
														</div><!-- </col-md-4> -->
													</div>

												</div><!-- </competencyRepeater> -->
												<div class="md-padder text-left">
	                        				<button type="button" value="<?php echo $view_user->name; ?>" class="btn btn-primary btn-lg margin-btm-30 btn-addCompetency" id="btnOK">
	                        					<i class="fa fa-send"></i>
	                        					<span>OK</span>
	                        				</button>
				 								</div><!-- </md-padder> -->
											</fieldset>
										</form>
									</div><!-- </col-md-12> -->
								</div><!-- </row> -->
							</div><!-- </col-md-6> -->
						</div><!-- </row> -->
	 				</div><!-- </container> -->
	 			</section><!-- </section-technical> -->
				<!-- ==============================================
			    Formulario Dados Pessoais (Dados Pessoais)
			   =============================================== -->
				<section class="update-dataInfo" id="update-dataInfo">
					<div class="container">
					   <div class="container-fluid">

				    		<!-- TitleSection -->
				    		<div class="cols">
				    			<div class="title-section">
				    				<h2 class="title">Informações e Dados Pessoais<span class="cursor-tag">_</span></h2>
				    				<h3 class="title-description">Endereço, telefone, cidade, descrição.</h3>
				    			</div>
				    		</div>
					      <div class="row">
					      	<div class="col-lg-4 col-md-5">
					      		<div class="card card-user">
					      			<div class="backgroundHeader">
					      				<img src="<?php echo IMAGES; ?>background.jpg" alt="..."/>
					      			</div><!-- </div>image> -->
					      			<div class="content">
					      				<div class="author">
					      					<!--<img class="avatar border-white" src="<?php echo IMAGES; ?>elisandromello.jpg" alt="..."/>-->

							               <?php
							                   if (!is_null($view_user->image)) {
							                       echo '<img class="avatar border-white" src="' . BASE . 'public/uploads/users/' . $view_user->id . '/' . $view_user->image . '" width="160">';
							                   }
							                   else{
							                       echo '<img class="avatar border-white" src="' . BASE . 'public/uploads/users/' . 'default' . '/' . 'default.png' . '" width="160">';
							                   }
							               ?>

					      					<h4 class="title"><?php echo $view_user->name; ?><br />
					      						<a href="#"><small><?php echo $view_user->email; ?></small></a>
					      					</h4>
					      				</div><!-- </author> -->
					      				<p class="description text-center">
					      					"I like the way you work it <br>
					      					No diggity <br>
					      					I wanna bag it up"
					      				</p>
					      			</div><!-- <!/content> -->
					      			<hr>
					      			<div class="text-center">
					      				<div class="row">
					      					<div class="col-md-3 col-md-offset-1">
					      						<h5>12<br /><small>Files</small></h5>
					      					</div><!-- </col-md-4 col-md-offset-1> -->
					      					<div class="col-md-4">
					      						<h5>2GB<br /><small>Used</small></h5>
					      					</div><!-- </col-md-4> -->
					      					<div class="col-md-3">
					      						<h5>24,6$<br /><small>Spent</small></h5>
					      					</div><!-- </col-md-3> -->
					      				</div><!-- </row> -->
					      			</div><!-- </text-center> -->
					      		</div><!-- </card card-user> -->
					      		<div class="card">
					      			<div class="header">
					      				<h4 class="title">Social Media</h4>
					      			</div><!-- </header> -->
					      			<div class="content">
					      				<ul class="list-unstyled team-members">
					      					<li>
					      						<div class="row">
					      							<div class="col-xs-3">
															<div class="pull-left icone-fa icone-fa-card text-center">
																<i class="fa fa-linkedin"></i>
															</div>
					      							</div>
					      							<div class="col-xs-9">
					      								in/<?php echo $view_user->network->linkedin; ?>
					      								<br />
					      								<span class="text-muted"><small>Offline</small></span>
					      							</div>
					      						</div>
					      					</li>
					      					<li>
					      						<div class="row">
					      							<div class="col-xs-3">
															<div class="pull-left icone-fa icone-fa-card text-center">
																<i class="fa fa-facebook"></i>
															</div>
					      							</div>
					      							<div class="col-xs-9">
					      								facebook.com/<?php echo $view_user->network->facebook; ?>
					      								<br />
					      								<span class="text-success"><small>Available</small></span>
					      							</div>
					      						</div>
					      					</li>
					      					<li>
					      						<div class="row">
					      							<div class="col-xs-3">
															<div class="pull-left icone-fa icone-fa-card text-center">
																<i class="fa fa-twitter"></i>
															</div>
					      							</div>
					      							<div class="col-xs-9">
					      								@<?php echo $view_user->network->twitter; ?>
					      								<br />
					      								<span class="text-danger"><small>Busy</small></span>
					      							</div><!-- </col-xs-6> -->

					      						</div><!-- </row> -->
					      					</li><!-- </li> -->
					      				</ul><!-- </list-unstyled team-members> -->
					      			</div><!-- </content> -->
					      		</div><!-- </card> -->
					         </div><!-- <col-lg-4 col-md-5 -->
					         <div class="col-lg-8 col-md-7">
					         	<div class="card">
					         		<div class="header">
					         			<h4 class="title">Editar Perfil</h4>
					         		</div>
					         		<div class="content">

											<form class="form-registry" id="form-registry" action="<?php echo BASE; ?>perfil/upRegistry/" method="post">
												<fieldset id="registrosPessoais">
					         				<div class="row">
					         					<div class="col-md-6">
					         						<div class="form-group">
					         							<label>Nome</label>
					         							<input type="text" name="name" class="form-control border-input" placeholder="Nome" value="<?php echo $view_user->name; ?>">
					         						</div><!-- </form-group> -->
					         					</div><!-- </col-md-6> -->
					         					<div class="col-md-6">
					         						<div class="form-group">
					         							<label>Sobrenome</label>
					         							<input type="text" name="last_name" class="form-control border-input" placeholder="Sobrenome" value="<?php echo $view_user->last_name; ?>">
					         						</div><!-- </form-group> -->
					         					</div><!-- </col-md-6> -->
					         				</div><!-- </row> 2º Linha do formulario -->

					         				<div class="row">
					         					<div class="col-md-4">
					         						<div class="form-group">
					         							<label>Celular Móvel</label>
					         							<input type="text" id="celular" name="celular" class="form-control border-input" placeholder="Celular" value="<?php echo $view_user->registry->celular; ?>" >
					         						</div><!-- </form-group> -->
					         					</div><!-- </col-md-4> -->
					         					<div class="col-md-4">
					         						<div class="form-group">
					         							<label>Informe CEP</label>
															<label class="sr-only" for="zipcode">CEP</label>
				                        			<div class="text-success" id="infocep"></div>
				                        			<input type="text" name="zipcode" id="zipcode" placeholder="CEP" required class="form-control pulacampos" value="<?php echo $view_user->registry->zipcode; ?>">
					         						</div><!-- </form-group> -->
					         					</div><!-- </col-md-4> -->
					         				</div><!-- </row> 2º Linha do formulario -->

					         				<div class="row">
					         					<div class="col-md-9">
					         						<div class="form-group">
					         							<label>Endereço</label>
					         							<input type="text" name="address" id="address" class="form-control border-input" placeholder="Endereço" value="<?php echo $view_user->registry->address; ?>" >
					         						</div><!-- </form-group> -->
					         					</div><!-- </col-md-10> -->
					         				</div><!-- </row> 3º Linha do formulario -->

					         				<div class="row">
					         					<div class="col-md-4">
					         						<div class="form-group">
					         							<label>Bairro</label>
					         							<input type="text" name="burgh" id="burgh" class="form-control border-input" placeholder="Bairro" value="<?php echo $view_user->registry->burgh; ?>">
					         						</div><!-- </form-group> -->
					         					</div><!-- </col-md-4> -->
													<div class="col-md-4">
					         						<div class="form-group">
					         							<label>Cidade</label>
					         							<input type="text" id="city" name="city" class="form-control border-input" placeholder="Cidade" value="<?php echo $view_user->registry->city; ?>">
					         						</div><!-- </form-group> -->
					         					</div><!-- </col-md-4> -->
					         					<div class="col-md-2">
					         						<div class="form-group">
					         							<label>UF</label>
					         							<input type="text" id="state" name="state" class="form-control border-input" placeholder="UF" value="<?php echo $view_user->registry->state; ?>">
					         						</div><!-- </form-group> -->
					         					</div><!-- </col-md-4> -->
					         				</div><!-- </row> 4º Linha do formulario -->
					         				<div class="row">
					         					<div class="col-md-12">
					         						<div class="form-group">
					         							<label>Sobre Mim</label>
					         							<textarea rows="5" id="sobremim" name="sobremim" class="form-control" > <?php echo htmlentities( $view_user->registry->about); ?>
					         							</textarea>
					         						</div><!-- </form-group> -->
					         					</div><!-- </col-md-12> -->
					         				</div><!-- </row> -->
				         					<div class="md-padder text-center">
				 									<button type="submit" value="Submit" class="btn btn-primary btn-lg margin-btm-30"> <i class="fa fa-user"></i> <span class="hidden-xs"> Atualizar </span> Cadastro </button>
				 									<button type="submit" value="Cancel" class="btn btn-primary btn-lg margin-btm-30" formnovalidate name="cancel"> <i class="fa fa-user"></i> <span class="hidden-xs"> Cancelar </span> Cadastro </button>
				 								</div>
					         				<div class="clearfix"></div>
					         			</form>
					         		</div><!-- </content> -->
					         	</div>
					         </div>

					      </div><!-- </row> -->
					      <div class="row">
					      	<div class="col-md-12">

					      	</div>
					      </div>
					   </div><!-- </container-fluid> -->
					</div><!-- </container> -->
				</section>
			</main><!-- </main> Final Corpo de Conteúdo-->