	   <!-- ==============================================
	   Layout Content Site (Definição de Layout)
      ====================================-->
		<div class="layout">
			<main>
				<?php echo (isset($this->alert) ? $this->alert : ''); ?>	
				
				<!-- ==============================================
	    		Skill Técnico (Technical Skill)
	    		=============================================== -->
	 			<section class="update-skill" id="skills">
	 				<div class="container">
	 					<!-- TitleSection -->
	 					<div class="cols">
	 						<div class="title-section">
	 							<h2 class="title">Skill<span class="cursor-tag">_</span></h2>
	 							<h3 class="title-description">Summary of qualifications and competences.</h3>
	 						</div>
	 					</div>
	 					<!-- End Title Section -->
						<div class="row">
						<!--
	 					*	Atualizar Competências Atuais
	 					*-->
							<div class="col-md-6">
								<div class="row">
									<div class="col-md-12">
										<form method="POST" class="form-horizontal wrapper-repeater" role="form">
											<fieldset>
												<legend>Atualizar Competências Atuais</legend>
												<?php
													foreach ($view_user->competencies as $competency):
												?>
													<div class="row">
														<div class="col-md-5 col-sm-12 wow flipInx" data-wow-delay="0.3s">
															<div class="skill-bar">
														    	<ul>
																	<li>
																		<div class="bar" data-value="" style="width: <?php echo $competency->level ?>0%;">
																			<h5><?php echo $competency->competency ?></h5>
																		</div>
																		<span><?php echo $competency->level ?> / 10</span>
																	</li>
														      </ul><!-- </ul> Lista de Barras Skill -->
														   </div><!-- </skill-bar> -->
														</div><!-- </col-md-5 col-sm-12> -->

														<div class="col-md-2  wow flipInx">
															<select name="make" id="level<?php echo $competency->id ?>" class="form-control">
																<option value="1" <?php ($competency->level == "1") ? print "selected" : ""; ?>>
																	1
																</option>
																<option value="2" <?php ($competency->level == '2') ? print "selected" : ""; ?>>
																	2
																</option>
																<option value="3" <?php ($competency->level == '3') ? print "selected" : ""; ?>>
																	3
																</option>
																<option value="4" <?php ($competency->level == '4') ? print "selected" : ""; ?>>
																	4
																</option>
																<option value="5" <?php ($competency->level == '5') ? print "selected" : ""; ?> >
																	5
																</option>
																<option value="6" <?php ($competency->level == '6') ? print "selected" : ""; ?>>
																	6
																</option>
																<option value="7" <?php ($competency->level == '7') ? print "selected" : ""; ?>>
																	7
																</option>
																<option value="8" <?php ($competency->level == '8') ? print "selected" : ""; ?>>
																	8
																</option>
																<option value="9" <?php ($competency->level == '9') ? print "selected" : ""; ?>>
																	9
																</option>
																<option value="10" <?php ($competency->level == '10') ? print "selected" : ""; ?>>
																	10
																</option>
															</select>
					         						</div><!-- </col-md-1> -->
														<div class="col-md-2  wow flipInx">

				                        			<button type="button" value="level<?php echo $competency->id ?>" onclick="sendEdit(this.value, <?php echo $competency->id ?>, <?php echo $competency->level?> ,'<?php echo $view_user->name?>')" class="btn btn-primary btn-sm margin-btm-30" id="btnUP">
			                        					<i class="fa fa-pencil"></i>
			                        					<span>Editar</span>
			                        				</button>
														</div>
														<div class="col-md-2  wow flipInx">
															<button type="button" value="<?php echo $competency->id ?>" onclick="sendDel(this.value, '<?php echo $view_user->name?>')" class="btn btn-primary btn-sm margin-btm-30" id="btnDel">
			                        					<i class="fa fa-trash"></i>
			                        					<span>Excluir</span>
			                        				</button>
														</div>
													</div><!-- </row> -->	
												<?php	endforeach
												?>
											</fieldset>
										</form>
									</div><!-- </col-md-12> -->
								</div><!-- </row> -->
							</div><!-- </col-md-6> -->	 					
		 					<!--
		 					*	Add Novas Competências
		 					*-->
							<div class="col-md-6">
								<div class="row">
									<div class="col-md-12">
										<form method="POST" action="<?php echo BASE; ?>tests/cadastrar/"  name="addcompetency" id="addcompetency" class="form-horizontal wrapper-repeater" >
											<fieldset>
												<legend>Add Novas Competências</legend>
							 					<div class="repeater-custom-show-hide">
													<div class="row">
														<div class="col-md-5">
															<label>Competências</label>
														</div>
														<div class="col-md-3">
															<label>Domínio</label>		
														</div>
														<div class="col-md-2">
															<label>Nível</label>		
														</div>
														<div class="col-md-2">
															<label>Excluir</label>
														</div>
													</div><!-- </row> -->

							 						<div data-repeater-list="car">
							 							<div data-repeater-item="">
															<div class="row">
																<div class="col-md-5 wow flipInx">
									   							<div class="box-input">
									   								<input type="text" name="competency" id="competency" class="form-control border-input" placeholder="Competência">
									   							</div>
									      					</div><!-- </col-md-5> -->
																<div class="col-md-3 wow flipInx">
																	<div class="box-input">
																		<select name="domain" id="domain" class="form-control">
																			<option value="1">
																				Microsoft
																			</option>
																			<option value="2">
																				Linux
																			</option>
																			<option value="3">
																				Especializações
																			</option>
																		</select>
																	</div>							
										      				</div><!-- </col-md-3> -->

							 									<div class="col-md-2">
							 										<div class="box-input">
							 										<select name="nivel" class="form-control">
							 											<option value="1" selected="">1</option>
							 											<option value="2">2</option>
							 											<option value="3">3</option>
							 										</select>
							 										</div>
							 									</div>
									      					<div class="col-md-2 wow flipInx">
																	<div class="box-input">
																		<a data-repeater-delete class="btn btn-primary btn-sm margin-btm-30" > <i class="fa fa-minus-circle"></i> <span class="hidden-xs"></span> Delete </a>
																	</div>
																</div>
															</div><!-- </row> -->
							 							</div><!-- </data-repeater-item> -->
							 						</div><!-- </data-repeater-list> -->
						 							<div class="form-group">
						 								<div class="col-sm-offset-1 col-sm-11">
						 									<span class="btn btn-info btn-md" data-repeater-create="">
						 										<span class="glyphicon glyphicon-plus"></span> Add
						 									</span>
						 								</div>
						 							</div>
						 							<hr>
						 						</div><!-- </repeater-custom-show-hide> -->
												<div class="md-padder text-left wow flipInx">
	                        				<button type="button" value="<?php echo $view_user->name; ?>" onclick="sendAdd(this.value)" class="btn btn-primary btn-lg margin-btm-30" id="btnOK">
	                        					<i class="fa fa-send"></i>
	                        					<span>OK</span>
	                        				</button>
				 								</div>
											</fieldset>
										</form>				
									</div><!-- </col-md-12> -->
								</div><!-- </row> -->
							</div><!-- </col-md-6> -->
						
						</div><!-- </row> -->

	 				</div><!-- </container> -->
	 			</section><!-- </section-technical> -->
				<!-- ==============================================
			    Recommendations (Acc Recomendações)
			    =============================================== -->
				<section class="quotes" id="recomendations">
					<div class="container">
						<!-- TitleSection -->
					    <div class="cols">
				            <div class="title-section">
				                <h2 class="title">Recommendations and Quotes<span class="cursor-tag">_</span></h2>
				                <h3 class="title-description">Some feedback on my work.</h3>
				            </div>
					    </div>
					    <!-- End Title Section -->        
				        <!-- Start BlockQuote/Tooltip Section -->
				        <div class="row">
				        	<!-- Start Blockquote -->
				            <div class="col-sm-6">
				            	<h3 class="spec">Blockquote</h3>
				                <blockquote>
					                <p>Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Donec ullamcorper nulla non metus auctor fringilla.</p>
					                <small>
				                    	<cite title="John Bostic">John Bostic</cite>
				                    </small>
				                </blockquote>
				            </div>
				            <!-- End Blockquote -->
				            
				            <!-- Start Tooltip -->
				            <div class="col-sm-6">
				            	<h3 class="spec">Tooltip</h3>
				            	
				                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas neque diam, luctus at laoreet in, <a href="#" data-toggle="tooltip" title="I'm a Simple Tootlip">auctor ut tellus</a>. Etiam enim lacus, ornare et tempor, rhoncus rhoncus sem.</p>
				                
				            </div>
				            <!-- End Tootlip -->
				        </div>
				        <!-- End BlockQuote/Tooltip Section -->
					</div>
				</section>		 					

				<!-- ==============================================
			    Formulario Dados Pessoais (Dados Pessoais)
			   =============================================== -->
				<section class="update-dataInfo" id="update-dataInfo">
					<div class="container">
					   <div class="container-fluid">

				    		<!-- TitleSection -->
				    		<div class="cols">
				    			<div class="title-section">
				    				<h2 class="title">Information and personal data<span class="cursor-tag">_</span></h2>
				    				<h3 class="title-description">Address, phone, city, description.</h3>
				    			</div>
				    		</div>				   
					      <div class="row">
					      	<div class="col-lg-4 col-md-5">
					      		<div class="card card-user">
					      			<div class="backgroundHeader">
					      				<img src="<?php echo IMAGES; ?>background.jpg" alt="..."/>
					      			</div><!-- </div>image> -->
					      			<div class="content">
					      				<div class="author">
					      					<!--<img class="avatar border-white" src="<?php echo IMAGES; ?>elisandromello.jpg" alt="..."/>-->

							               <?php
							                   if (!is_null($view_user->image)) {
							                       echo '<img class="avatar border-white" src="' . BASE . 'public/uploads/users/' . $view_user->id . '/' . $view_user->image . '" width="160">';
							                   }
							                   else{
							                       echo '<img class="avatar border-white" src="' . BASE . 'public/uploads/users/' . 'default' . '/' . 'default.png' . '" width="160">';
							                   }
							               ?>

					      					<h4 class="title"><?php echo $view_user->name; ?><br />
					      						<a href="#"><small><?php echo $view_user->email; ?></small></a>
					      					</h4>
					      				</div><!-- </author> -->
					      				<p class="description text-center">
					      					"I like the way you work it <br>
					      					No diggity <br>
					      					I wanna bag it up"
					      				</p>
					      			</div><!-- <!/content> -->
					      			<hr>
					      			<div class="text-center">
					      				<div class="row">
					      					<div class="col-md-3 col-md-offset-1">
					      						<h5>12<br /><small>Files</small></h5>
					      					</div><!-- </col-md-4 col-md-offset-1> -->
					      					<div class="col-md-4">
					      						<h5>2GB<br /><small>Used</small></h5>
					      					</div><!-- </col-md-4> -->
					      					<div class="col-md-3">
					      						<h5>24,6$<br /><small>Spent</small></h5>
					      					</div><!-- </col-md-3> --> 
					      				</div><!-- </row> -->
					      			</div><!-- </text-center> -->
					      		</div><!-- </card card-user> -->
					      		<div class="card">
					      			<div class="header">
					      				<h4 class="title">Social Media</h4>
					      			</div><!-- </header> -->
					      			<div class="content">
					      				<ul class="list-unstyled team-members">
					      					<li>
					      						<div class="row">
					      							<div class="col-xs-3">
															<div class="pull-left icone-fa icone-fa-card text-center">
																<i class="fa fa-linkedin"></i>
															</div>
					      							</div>
					      							<div class="col-xs-9">
					      								in/<?php echo $view_user->network->linkedin; ?>
					      								<br />
					      								<span class="text-muted"><small>Offline</small></span>
					      							</div>
					      						</div>
					      					</li>
					      					<li>
					      						<div class="row">
					      							<div class="col-xs-3">
															<div class="pull-left icone-fa icone-fa-card text-center">
																<i class="fa fa-facebook"></i>
															</div>
					      							</div>
					      							<div class="col-xs-9">
					      								facebook.com/<?php echo $view_user->network->facebook; ?>
					      								<br />
					      								<span class="text-success"><small>Available</small></span>
					      							</div>
					      						</div>
					      					</li>
					      					<li>
					      						<div class="row">
					      							<div class="col-xs-3">
															<div class="pull-left icone-fa icone-fa-card text-center">
																<i class="fa fa-twitter"></i>
															</div>
					      							</div>
					      							<div class="col-xs-9">
					      								@<?php echo $view_user->network->twitter; ?>
					      								<br />
					      								<span class="text-danger"><small>Busy</small></span>
					      							</div><!-- </col-xs-6> -->

					      						</div><!-- </row> -->
					      					</li><!-- </li> -->
					      				</ul><!-- </list-unstyled team-members> -->
					      			</div><!-- </content> -->
					      		</div><!-- </card> -->
					         </div><!-- <col-lg-4 col-md-5 -->
					         <div class="col-lg-8 col-md-7">
					         	<div class="card">
					         		<div class="header">
					         			<h4 class="title">Edit Profile</h4>
					         		</div>
					         		<div class="content">
					         			<form>
					         				<div class="row">
					         					<div class="col-md-3">
					         						<div class="form-group">
					         							<label>Username</label>
					         							<input type="text" class="form-control border-input" disabled placeholder="usuário" value="<?php echo $view_user->username; ?>">
					         						</div><!-- </form-group> -->
					         					</div><!-- </col-md-5> --> 
					         					<div class="col-md-4">
					         						<div class="form-group">
					         							<label for="exampleInputEmail1">Email address</label>
					         							<input type="email" class="form-control border-input" disabled placeholder="Email" value="<?php echo $view_user->email; ?>" >
					         						</div><!-- </form-group> -->
					         					</div><!-- </col-md-3> -->
					         					<div class="col-md-5">
					         						<div class="form-group">
															<label class="card-genero">Sexo</label>
															<input type="radio" id="radio03" name="radio" />
															<label for="radio03"><span></span>Female</label>
															<input type="radio" id="radio04" name="radio" />
															<label for="radio04"><span></span>Male</label>
					         						</div><!-- </form-group> -->
					         					</div><!-- </col-md-4> -->
					         				</div><!-- </row> 1º Linha do formulario -->

					         				<div class="row">
					         					<div class="col-md-6">
					         						<div class="form-group">
					         							<label>First Name</label>
					         							<input type="text" class="form-control border-input" placeholder="Company" value="<?php echo $view_user->name; ?>">
					         						</div><!-- </form-group> -->
					         					</div><!-- </col-md-6> -->
					         					<div class="col-md-6">
					         						<div class="form-group">
					         							<label>Last Name</label>
					         							<input type="text" class="form-control border-input" placeholder="Last Name" value="M. Corrêa">
					         						</div><!-- </form-group> -->
					         					</div><!-- </col-md-6> -->
					         				</div><!-- </row> 2º Linha do formulario --> 

					         				<div class="row">
					         					<div class="col-md-4">
					         						<div class="form-group">
					         							<label>Phone</label>
					         							<input type="text" class="form-control border-input" placeholder="Phone" value="<?php echo $view_user->registry->phone; ?>" >
					         						</div><!-- </form-group> -->
					         					</div><!-- </col-md-4> -->
					         					<div class="col-md-4">
					         						<div class="form-group">
					         							<label>Celular Mobile</label>
					         							<input type="text" class="form-control border-input" placeholder="Mobile" value="<?php echo $view_user->registry->celular; ?>" >
					         						</div><!-- </form-group> -->
					         					</div><!-- </col-md-4> -->
					         					<div class="col-md-4">
					         						<div class="form-group">
					         							<label>State</label>
						    								<select name="state" class="form-control border-input" >
						    									<option value=" " >Please select your state</option>
						    									<option>Acre</option>
						    									<option>Alagoas</option>
						    									<option>Amampá</option>
						    									<option>Amazonas</option>
						    									<option>Bahia</option>
						    									<option>Ceará</option>
						    									<option>Distrito Federal</option>
						    									<option>Espírito Santo</option>
						    									<option>Góias</option>
						    									<option>Maranhão</option>
						    									<option>Mato Grosso</option>
						    									<option>Mato Grosso do Sul</option>
						    									<option>Minas Gerais</option>
						    									<option>Pará</option>
						    									<option>Paraíba</option>
						    									<option>Paraná</option>
						    									<option>Pernambuco</option>
						    									<option>Piauí</option>
						    									<option>Rio de Janeiro</option>
						    									<option>Rio Grande do Norte</option>
						    									<option>Rio Grande do Sul</option>
						    									<option>Rondônia</option>
						    									<option>Roraima</option>
						    									<option>Santa Catarina</option>
						    									<option>São Paulo</option>
						    									<option>Sergipe</option>
						    									<option>Tocantins</option>
						    								</select>
					         						</div><!-- </form-group> -->
					         					</div><!-- </col-md-4> -->				         					
					         				</div><!-- </row> 2º Linha do formulario --> 

					         				<div class="row">
					         					<div class="col-md-9">
					         						<div class="form-group">
					         							<label>Address</label>
					         							<input type="text" class="form-control border-input" placeholder="Home Address" value="<?php echo $view_user->registry->address; ?>" >
					         						</div><!-- </form-group> -->
					         					</div><!-- </col-md-10> -->         					
					         				</div><!-- </row> 3º Linha do formulario --> 

					         				<div class="row">
					         					<div class="col-md-4">
					         						<div class="form-group">
					         							<label>City</label>
					         							<input type="text" class="form-control border-input" placeholder="City" value="Melbourne">
					         						</div><!-- </form-group> -->
					         					</div><!-- </col-md-4> -->
					         					<div class="col-md-4">
					         						<div class="form-group">
					         							<label>Country</label>
					         							<input type="text" class="form-control border-input" placeholder="Country" value="Australia">
					         						</div><!-- </form-group> -->
					         					</div><!-- </col-md-4> -->
					         					<div class="col-md-4">
					         						<div class="form-group">
					         							<label>Postal Code</label>
					         							<input type="number" class="form-control border-input" placeholder="ZIP Code" value="<?php echo $view_user->registry->zipcode; ?>" >
					         						</div><!-- </form-group> -->
					         					</div><!-- </col-md-4> -->
					         				</div><!-- </row> 4º Linha do formulario --> 

					         				<div class="row">
					         					<div class="col-md-12">
					         						<div class="form-group">
					         							<label>About Me</label>
					         							<textarea rows="5" class="form-control border-input" placeholder="Here can be your description" value="<?php echo $view_user->registry->about; ?>" >
					         							</textarea>
					         						</div><!-- </form-group> -->
					         					</div><!-- </col-md-12> -->
					         				</div><!-- </row> -->
				         					<div class="md-padder text-center">
				 									<button type="submit" data-tooltip="Change personal infos" class="btn btn-primary btn-lg margin-btm-30"> <i class="fa fa-user"></i> <span class="hidden-xs"> Update </span> Infos </button>
				 								</div>
					         				<div class="clearfix"></div>
					         			</form>
					         		</div><!-- </content> -->
					         	</div>
					         </div>

					      </div><!-- </row> -->
					      <div class="row">
					      	<div class="col-md-12">

					      	</div>
					      </div>
					   </div><!-- </container-fluid> -->
					</div><!-- </container> -->
				</section>			   			
			</main><!-- </main> Final Corpo de Conteúdo-->		