			<footer>
				<!-- ==============================================
			    Footer (Rodapé)
			   =============================================== -->
			   <section class="social-links">
			    	<div class="container">
			    		<div class="row">
			    			<ul>
			    				<li> <a href="https://www.facebook.com/profile.php?id=1800765934" target="_blank" title=""> <span> <i class="fa fa-facebook"></i> </span> </a> </li>
			    				<li> <a href="https://twitter.com/elisandromello" target="_blank" title=""> <span> <i class="fa fa-twitter"></i> </span> </a> </li>
			    				<li> <a href="http://www.linkedin.com/in/elisandromello" target="_blank" title=""> <span> <i class="fa fa-linkedin"></i> </span> </a> </li>
			    				<li> <a href="http://www.instagram.com/iamelisandromello" target="_blank" title=""> <span> <i class="fa fa-instagram"></i> </span> </a> </li>
			    				<li> <a href="https://github.com/iamelisandromello" target="_blank" title=""> <span> <i class="fa fa-github"></i> </span> </a> </li>
			    				<li> <a href="mailto:iam@elisandromello.com.br?subject=Eu tenho um comentário para você..." title=""><span> <i class="fa fa-envelope"></i></span></a></li>
			    			</ul>
			    		</div><!-- /row -->
			    	</div><!-- /container -->
			   </section><!-- </social-links> -->

				<!-- ==============================================
				   Créditos (Credits)
				=============================================== -->
			   <section class="copyright">
			   	<div class="container">
			   		<div class="col-md-12">
			   			<div class="text-center">
			   				<!-- Logo Header -->
			   				<section id="fox_footer" class="fox_footer">
			   					<div>
			   						<img src="<?php echo IMAGES; ?>logofooter.png" alt="Foxin by Elisandro Mello"> - &copy;<script>document.write(new Date().getFullYear())</script> - Designer coded and designed by <i class="fa fa-cloud-upload"></i> Elisandro Mello
			   					</div>
			   				</section><!-- </fox_footer> -->
			   				<!--/ Logo Header-->
			   			</div><!-- </text-center> -->
			   		</div><!-- </col-md-12> -->
			   	</div><!-- </container> -->
			   </section><!-- </copyright> -->
			</footer>
			<!-- Back To Top -->
			<a id="back-to-top" href="#">
				<i class="font-icon-arrow-simple-up"></i>
			</a>
			<!-- End Back to Top -->
			<!-- ==============================================
			   Modal Inclusão Experiência Profissional
			=============================================== -->
			<div class="modal fade" id="formProfessional" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
			    <div class="modal-dialog">
			    	<div class="modal-content modal-popup">
			        	<div class="modal-header">
		            	<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
		                <h2 class="modal-title">Incluir Nova Experiência</h2>
			        	</div><!-- </modal-header> -->
						<div class="row">
							<div class="col-lg-12 col-md-12">
				         	<div class="">
				         		<div class="header">
				         			<h4 class="title"></h4>
				         		</div><!-- </header> -->
			         			<div class="row">
										<div class="col-md-12">
											<div class="form-group">
												<label for="exemplo">Emprego Atual: </label>
												<input type="checkbox" name="atual" value="0" id="atual" checked="true">
												<span>Empregado</span>

											</div>
										</div>
									</div>
				         		<div class="content">
				         			<form method="POST" action="<?php echo BASE; ?>perfil/addProfessional/" id="addProfessionalForm" class="addProfessionalForm">
				         				<fieldset id="addProfessionalField">
					         				<div class="row">
					         					<div class="col-md-12">
					         						<div class="form-group">
					         							<input type="text" name="addCompany" id="addCompany" class="input-modal" placeholder="Empresa" >
					         						</div><!-- </form-group> -->
					         					</div><!-- </col-md-12> -->
					         				</div><!-- </row> 1º Linha do formulario -->

					         				<div class="row">
					         					<div class="col-md-12">
					         						<div class="form-group">
					         							<input type="text" name="addFunction" id="addFunction" class="input-modal" placeholder="Função" >
					         						</div><!-- </form-group> -->
					         					</div><!-- </col-md-4> -->
					         				</div><!-- </row> 2º Linha do formulario -->

					         				<div class="row">
					         					<div class="col-md-12">
					         						<div class="form-group">
					         							<textarea name="addAssignments" id="addAssignments" rows="4" class="finput-modal textarea-modal" placeholder="Atividades Exercidas"></textarea>
					         						</div><!-- </form-group> -->
					         					</div><!-- </col-md-4> -->
					         				</div><!-- </row> 3º Linha do formulario -->

												<div id="boxDataEntry">
													<div class="row">
														<div class="col-md-6 sandbox-container">
															<label for="">Incluir Data de Entrada</label>
															<div class="input-group date">
																<input type="text" name="adddate_entry" id="adddate_entry" class="input-modal" placeholder="00/00/0000">
																<span class="input-group-addon">
																	<i class="glyphicon glyphicon-th"></i>
																</span>
															</div><!-- </input-group date> -->
															<div class="msgFront" name="msgFront">
								               			<span></span>
								            			</div>
														</div><!-- </col-md-6 centered> -->
														<div class="col-md-6 sandbox-container" id="boxDataOut">
															<label for="">Incluir Data de Saída</label>
															<div class="input-group date">
																<input type="text" name="adddate_out" id="adddate_out" class="input-modal" placeholder="00/00/0000">
																<span class="input-group-addon">
																	<i class="glyphicon glyphicon-th"></i>
																</span>
															</div><!-- </input-group date> -->
															<div class="msgFront" name="msgFront">
								               			<span></span>
								            			</div>
														</div><!-- </col-md-6 centered> -->
													</div><!-- </row> 4º Linha do formulario -->
												</div>

												<input name="adicionar" type="button" class="form-control btn-addProfessional" value=" Adicionar Experiência">
								            <div class="row">
								            	<div class="col-md-12 msgbox" id="msg-box3">
								               	<span></span>
								            	</div>
								            </div>
				         				</fieldset>
				         			</form>
				         		</div><!-- </content> -->
				         	</div>
				         </div><!-- </col-md-12> -->
						</div><!-- </row> -->
			      </div><!-- </modal-content> -->
			   </div><!-- </modal-dialog> -->
			</div><!-- </modal fade> -->
			<!-- ==============================================
			    Modal Editar Experiência Profissional
			=============================================== -->
			<div class="modal fade" id="modalEditarProfessional" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
			    <div class="modal-dialog">
			    	<div class="modal-content modal-popup">
			        	<div class="modal-header">
		            	<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
		                <h2 class="modal-title">Atualização</h2>
			        	</div><!-- </modal-header> -->
    					<div class="row">
							<div class="col-md-10 centered">
								<div class="modal-containerStep">
									<span class="step-num">1</span>
									<div class="modal-text">
										Editar Experiência Profissional
									</div><!-- </modal-text> -->
								</div><!-- </moldal-containerStep> -->
							</div><!-- </col-md-10> -->
						</div><!-- </row>  -->
						<form method="POST" action="<?php echo BASE; ?>perfil/upprofessional/" name="upProfessionalForm" id="upProfessionalForm" class="upProfessionalForm">
							<fieldset id="upProfessionalField">
	         				<div class="row">
	         					<div class="col-md-12">
	         						<div class="form-group">
	         							<input type="text" name="upIDProfessional" id="upIDProfessional" value="<?php echo $professional->id ?>" class="input-modal" placeholder="ID" readonly hidden>
	         						</div><!-- </form-group> -->
	         					</div><!-- </col-md-12> -->
	         				</div><!-- </row> 1º Linha do formulario -->
	         				<div class="row">
	         					<div class="col-md-12">
	         						<div class="form-group">
	         							<input type="text" name="upCompany" id="upCompany" value="<?php echo $professional->company ?>" class="input-modal" placeholder="Empresa" >
	         						</div><!-- </form-group> -->
	         					</div><!-- </col-md-12> -->
	         				</div><!-- </row> 1º Linha do formulario -->

	         				<div class="row">
	         					<div class="col-md-12">
	         						<div class="form-group">
	         							<input type="text" name="upFunction" id="upFunction" value="<?php echo $professional->function ?>" class="input-modal" placeholder="Função" >
	         						</div><!-- </form-group> -->
	         					</div><!-- </col-md-4> -->
	         				</div><!-- </row> 2º Linha do formulario -->

	         				<div class="row">
	         					<div class="col-md-12">
	         						<div class="form-group">
	         							<textarea name="upAssignments" id="upAssignments" rows="4" class="finput-modal textarea-modal" placeholder="Atividades Exercidas"><?php echo $professional->assignments ?></textarea>
	         						</div><!-- </form-group> -->
	         					</div><!-- </col-md-4> -->
	         				</div><!-- </row> 3º Linha do formulario -->

								<div id="boxDataEntry">
									<div class="row">
										<div class="col-md-6 sandbox-container">
											<label for="">Incluir Data de Entrada</label>
											<div class="input-group date">
												<input type="text" name="update_entry" id="update_entry" class="input-modal" placeholder="00/00/0000">
												<span class="input-group-addon">
													<i class="glyphicon glyphicon-th"></i>
												</span>
											</div><!-- </input-group date> -->
										</div><!-- </col-md-6 centered> -->
										<div class="col-md-6 sandbox-container">
											<label for="">Incluir Data de Saída</label>
											<div class="input-group date">
												<input type="text" name="update_out" id="update_out" class="input-modal" placeholder="00/00/0000">
												<span class="input-group-addon">
													<i class="glyphicon glyphicon-th"></i>
												</span>
											</div><!-- </input-group date> -->
										</div><!-- </col-md-6 centered> -->
									</div><!-- </row> 4º Linha do formulario -->
									<div class="row">
										<div class="msgFront" name="msgFront">
				               			<span></span>
				            		</div>
									</div>
								</div>

								<input name="editar" type="button" class="form-control btn-UpProfessional" value=" Editar Experiência">
				            <div class="row">
				            	<div class="col-md-12 msgbox" id="msg-box3">
				               	<span></span>
				            	</div>
				            </div>
	      				</fieldset>
		            </form>
			      </div><!-- </modal-content> -->
			   </div><!-- </modal-dialog> -->
			</div><!-- </modal fade> -->
			<!-- ==============================================
			    Modal Concluir Formação Acadêmica
			=============================================== -->
			<div class="modal fade" id="modal1" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
			    <div class="modal-dialog">
			    	<div class="modal-content modal-popup">
			        	<div class="modal-header">
		            	<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
		                <h2 class="modal-title">Conclusão</h2>
			        	</div><!-- </modal-header> -->
    					<div class="row">
							<div class="col-md-10 centered">
								<div class="modal-containerStep">
									<span class="step-num">1</span>
									<div class="modal-text">
										Incluir Data de Conclusão
									</div><!-- </modal-text> -->
								</div><!-- </moldal-containerStep> -->
							</div><!-- </col-md-10> -->
						</div><!-- </row>  -->
						<form method="POST" action="<?php echo BASE; ?>perfil/upconclusion/" onsubmit="myFunction()" name="addconclusion" id="addconclusion" >
						<fieldset id="conclusionAcademic">
							<!-- Inicio Grupo Componente -->
							<div class="row">
								<div class="col-md-6 centered">
									<div class="modal-groupForm">
										<div class="grupo-input">
											<input type="text" name="modalId" id="modalId" class="input-modal hideme" readonly>
										</div><!-- </grupo-input> -->
									</div><!-- </modal-groupForm> -->
								</div><!-- </col-md-6 centered> -->
							</div><!-- </row> -->
							<div class="row">
								<div class="col-md-6 centered" id="sandbox-container">
									<div class="input-group date">
										<input type="text" name="date_conclusion" id="date_conclusion" class="input-modal" placeholder="00/00/0000">
										<span class="input-group-addon">
											<i class="glyphicon glyphicon-th"></i>
										</span>
									</div><!-- </input-group date> -->
								</div><!-- </col-md-6 centered> -->
							</div><!-- </row> -->
							<!-- <button type="button" class="btn btn-default" data-dismiss="modal" onclick="academicConclusion()">Concluir</button> -->
							<input name="conclusao" type="button" class="form-control" data-dismiss="modal" onclick="academicConclusion()" value="Conclusão">
						</fieldset>
		            </form>
			      </div><!-- </modal-content> -->
			   </div><!-- </modal-dialog> -->
			</div><!-- </modal fade> -->

			<!-- ==============================================
			   Modal Inclusão Formação Acadêmica
			=============================================== -->
			<div class="modal fade" id="formAcademic" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
			    <div class="modal-dialog">
			    	<div class="modal-content modal-popup">
			        	<div class="modal-header">
		            	<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
		                <h2 class="modal-title">Incluir Nova Formação</h2>
			        	</div><!-- </modal-header> -->
						<div class="row">
							<div class="col-lg-12 col-md-12">
				         	<div class="">
				         		<div class="header">
				         			<h4 class="title"></h4>
				         		</div><!-- </header> -->
				         		<div class="content">
				         			<form method="POST" action="<?php echo BASE; ?>perfil/addAcademic/" id="addAcademicForm" class="addAcademicForm">
				         				<fieldset>
					         				<div class="row">
					         					<div class="col-md-12">
					         						<div class="form-group">
					         							<input type="text" name="addCurso" id="addCurso" class="input-modal" placeholder="Curso" >
					         						</div><!-- </form-group> -->
					         					</div><!-- </col-md-12> -->
					         				</div><!-- </row> 1º Linha do formulario -->

					         				<div class="row">
					         					<div class="col-md-12">
					         						<div class="form-group">
					         							<input type="text" name="addInstituicao" id="addInstituicao" class="input-modal" placeholder="Instituição" >
					         						</div><!-- </form-group> -->
					         					</div><!-- </col-md-4> -->
					         				</div><!-- </row> 2º Linha do formulario -->

					         				<div class="row">
					         					<div class="col-md-6">
					         						<div class="form-group">
					         							<input type="text" class="input-modal" name="addLocal" id="addLocal" placeholder="Local" >
					         						</div><!-- </form-group> -->
					         					</div><!-- </col-md-4> -->
													<div class="col-md-6">
					         						<div class="form-group">
															<select name="addLevel" class="select-modal selectpicker" >
																<option class="opt-placeholder" value="-1" selected="" data-type="pos">
																	Nivel…
																</option>
																<option value="PHD">PHD</option>
																<option value="Doutorado">Doutorado</option>
																<option value="Mestrado">Mestrado</option>
																<option value="Pos">Pós Graduação</option>
																<option value="Bacharelado">Bacharelado</option>
																<option value="Tecnologo">Tecnólogo</option>
																<option value="Tecnico">Técnico</option>
																<option value="Medio">Ensino Médio</option>
															</select>
					         						</div><!-- </form-group> -->
					         					</div><!-- </col-md-4> -->
					         				</div><!-- </row> 3º Linha do formulario -->

												<div class="row titleRadio">
													<div class="col-md-12">
														<label>NIVEL DA FORMAÇÃO</label>
													</div>
												</div>
					         				<div class="row boxRadio" id="boxRadio">
					         					<div class="col-md-4">
					         						<div class="form-group">
															<input type="radio" id="level01" name="addAcademic" class="radio-academic academic" value="3">
                            						<label for="level01"><span></span>Completo</label>
					         						</div><!-- </form-group> -->
					         					</div><!-- </col-md-4> -->
					         					<div class="col-md-4">
					         						<div class="form-group">
															<input type="radio" id="level02" name="addAcademic" class="radio-academic academic" value="1">
                            						<label for="level02"><span></span>Trancado</label>
					         						</div><!-- </form-group> -->
					         					</div><!-- </col-md-4> -->
					         					<div class="col-md-4">
					         						<div class="form-group">
															<input type="radio" id="level03" name="addAcademic" class="radio-academic academic" value="2">
                            						<label for="level03"><span></span>Cursando</label>
					         						</div><!-- </form-group> -->
					         					</div><!-- </col-md-4> -->
					         				</div><!-- </row> 4º Linha do formulario -->

												<div id="boxDataConclusion">
												<div class="row">
													<div class="col-md-6 centered" id="sandbox-container">
														<label for="">Incluir Data de Conclusão</label>
														<div class="input-group date">
															<input type="text" name="adddate_conclusion" id="adddate_conclusion" class="input-modal" placeholder="00/00/0000">
															<span class="input-group-addon">
																<i class="glyphicon glyphicon-th"></i>
															</span>
														</div><!-- </input-group date> -->
													</div><!-- </col-md-6 centered> -->
												</div><!-- </row> 4º Linha do formulario -->
												</div>
												<input name="adicionar" type="button" class="form-control btn-UpAcademic" value=" Adicionar  Formação">
								            <div class="row">
								            	<div class="col-md-12 msgbox" id="msg-box3">
								               	<span></span>
								            	</div>
								            </div>

				         				</fieldset>
				         			</form>
				         		</div><!-- </content> -->
				         	</div>
				         </div><!-- </col-md-12> -->
						</div><!-- </row> -->
			      </div><!-- </modal-content> -->
			   </div><!-- </modal-dialog> -->
			</div><!-- </modal fade> -->
			<!-- ==============================================
			End Session Modal's (Final área de modal's)
			=============================================== -->
		</div><!--  </layout> Final do Layout Visivel-->
		<!-- ==============================================
		Javascripts
		================================================== -->
      <!-- Libs - Bibliotecas JQuery via Bower-->
		<script src="<?php echo BOWER; ?>jquery/dist/jquery.min.js"></script>
		<script src="<?php echo BOWER; ?>bootstrap-sass/assets/javascripts/bootstrap.min.js"></script>
		<script src="<?php echo BOWER; ?>wow/dist/wow.min.js"></script>
		<script src="<?php echo BOWER; ?>magnific-popup/dist/jquery.magnific-popup.min.js"></script>
		<script src="<?php echo BOWER; ?>flexslider/jquery.flexslider-min.js"></script>
		<script src="<?php echo BOWER; ?>jquery.scrollTo/jquery.scrollTo.min.js"></script>
		<script src="<?php echo BOWER; ?>jquery.easing/js/jquery.easing.min.js"></script>
		<script src="<?php echo BOWER; ?>jpreloader/js/jpreloader.min.js"></script>
		<script src="<?php echo BOWER; ?>jquery-validation/dist/jquery.validate.min.js"></script>
      <script src="<?php echo BOWER; ?>bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js"></script>
      <script src="<?php echo BOWER; ?>bootstrap-datepicker/dist/locales/bootstrap-datepicker.pt-BR.min.js"></script>
      <script src="<?php echo BOWER; ?>inputmask/dist/min/jquery.inputmask.bundle.min.js"></script>
      <!-- Libs - Bibliotecas JQuery -->
      <script src="<?php echo JS; ?>libs/jquery.form-repeater.js"></script>
		<script src="<?php echo JS; ?>libs/smooth-scrolling.js"></script>
		<!-- Scripts JavaScript Personalizados-->
		<script src="<?php echo JS; ?>perfil/perfil_mask.js"></script>
		<script src="<?php echo JS; ?>valida_data.js"></script>
		<script src="<?php echo JS; ?>perfil/main-perfil.js"></script>
		<script src="<?php echo JS; ?>search_cep.js"></script>
		<script src="<?php echo JS; ?>boxmessage.js"></script>
		<script src="<?php echo JS; ?>perfil/competency-perfil.js"></script>
		<script src="<?php echo JS; ?>perfil/academic-perfil.js"></script>
		<script src="<?php echo JS; ?>perfil/professional-perfil.js"></script>

		<script type="text/javascript">
		  	$('#testeRepeater').repeater({
		   	btnAddClass: 'a-btnAdd',
		      btnRemoveClass: 'a-btnRemove',
		      groupClass: 'competencies-group',
		      minItems: 1,
		      maxItems: 0,
		      startingIndex: 0,
		      reindexOnDelete: true,
		      repeatMode: 'append',
		      animation: 'fade',
		      animationSpeed: 800,
		      animationEasing: 'swing',
		      clearValues: true
		  	});
		</script>

      <script>
	      $('.sandbox-container .input-group.date').datepicker({
	          format: "dd/mm/yyyy",
	          language: "pt-BR",
	          clearBtn: true,
	          autoclose: true,
	          toggleActive: true
	      });
      </script>

		<!-- Tuner ACessibilidade de Cores -->
		<script src="<?php echo TUNER; ?>js/tuner.js"></script>
		<div id="tuner" class="tuner">
			<label>Theme Colors</label>
			<ul class="colors">
				<li data-color="orange" class="color-orange"><span></span></li>
				<li data-color="purple" class="color-purple"><span></span></li>
				<li data-color="green" class="color-green"><span></span></li>
				<li data-color="pink" class="color-pink"><span></span></li>
				<li data-color="blue" class="color-blue active"><span></span></li>
				<li data-color="cyan" class="color-cyan"><span></span></li>
			</ul>
			<label>Layout Styles</label>
			<ul class="layouts">
				<li data-layout="boxed">Boxed</li>
				<li data-layout="widescreen" class="active">Widescreen</li>
			</ul>
			<i id="tuner-switcher" class="fa fa-cogs"></i>
		</div><!--/ tuner -->
	</body>
</html>