			<footer>
				<!-- ==============================================
			    Footer (Rodapé)
			   =============================================== -->
			   <section class="social-links">
			    	<div class="container">
			    		<div class="row">
			    			<ul>
			    				<li> <a href="https://www.facebook.com/profile.php?id=1800765934" target="_blank" title=""> <span> <i class="fa fa-facebook"></i> </span> </a> </li>
			    				<li> <a href="https://twitter.com/elisandromello" target="_blank" title=""> <span> <i class="fa fa-twitter"></i> </span> </a> </li>
			    				<li> <a href="http://www.linkedin.com/in/elisandromello" target="_blank" title=""> <span> <i class="fa fa-linkedin"></i> </span> </a> </li>
			    				<li> <a href="http://www.instagram.com/iamelisandromello" target="_blank" title=""> <span> <i class="fa fa-instagram"></i> </span> </a> </li>
			    				<li> <a href="https://github.com/iamelisandromello" target="_blank" title=""> <span> <i class="fa fa-github"></i> </span> </a> </li>
			    				<li> <a href="mailto:iam@elisandromello.com.br?subject=Eu tenho um comentário para você..." title=""><span> <i class="fa fa-envelope"></i></span></a></li>
			    			</ul>
			    		</div><!-- /row -->
			    	</div><!-- /container -->    
			   </section><!-- </social-links> -->

				<!-- ==============================================
				   Créditos (Credits)
				=============================================== --> 
			   <section class="copyright">
			   	<div class="container">
			   		<div class="col-md-12">
			   			<div class="text-center"> 
			   				<!-- Logo Header -->
			   				<section id="fox_footer" class="fox_footer">
			   					<div>
			   						<img src="<?php echo IMAGES; ?>logofooter.png" alt="Foxin by Elisandro Mello"> - &copy;<script>document.write(new Date().getFullYear())</script> - Designer coded and designed by <i class="fa fa-cloud-upload"></i> Elisandro Mello
			   					</div>
			   				</section><!-- </fox_footer> -->
			   				<!--/ Logo Header-->
			   			</div><!-- </text-center> -->
			   		</div><!-- </col-md-12> -->
			   	</div><!-- </container> -->
			   </section><!-- </copyright> -->			
			</footer>
			<!-- Back To Top -->
			<a id="back-to-top" href="#">
				<i class="font-icon-arrow-simple-up"></i>
			</a>
			<!-- End Back to Top -->

		</div><!--  </layout> Final do Layout Visivel-->
		
		<!-- ==============================================
		Javascripts
		================================================== -->
		<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
		<script src="<?php echo BOWER; ?>jquery/dist/jquery.min.js"></script>
		<script src="<?php echo JS; ?>front/modernizr.js"></script>
		<script src="<?php echo JS; ?>front/jquery.custom-file-input.js"></script>

		<script src="<?php echo BOWER; ?>bootstrap-sass/assets/javascripts/bootstrap.min.js"></script> <!-- Bootstrap -->
		<script src="<?php echo JS; ?>front/tmp/classie.js"></script>
		<!-- Contact JS -->
		<script src="<?php echo BOWER; ?>jqBootstrapValidation/src/jqBootstrapValidation.js"></script><!--BootstrapValida-->
		<!-- Inclua os plugins compilados (abaixo) ou inclua arquivos individuais conforme necessário -->		
		<script src="<?php echo BOWER; ?>wow/dist/wow.min.js"></script> <!-- WOW --> 
		<script src="<?php echo BOWER; ?>jquery.scrollTo/jquery.scrollTo.min.js"></script> <!-- ScrollTo -->		
		<script src="<?php echo BOWER; ?>jquery.easing/js/jquery.easing.min.js"></script> <!-- Easing -->
		<script src="<?php echo BOWER; ?>jpreloader/js/jpreloader.min.js"></script> <!-- PreLoader -->	
		<script src="<?php echo JS; ?>front/smooth-scrolling.js"></script> <!-- Deslocamento Suave Sesões - One Page -->
		<script src="<?php echo JS; ?>front/main-update.js"></script> <!-- Default JS Pagina Update-->
		<!-- Função Repeater -->
		<script src="<?php echo JS; ?>front/jquery.repeater.min.js"></script>
		<script src="<?php echo JS; ?>front/use-repeater.js"></script>
		<script src="<?php echo JS; ?>modal.js"></script>		
		<script src="<?php echo JS; ?>competency.js"></script>

		<!-- Tuner ACessibilidade de Cores -->
		<script src="<?php echo TUNER; ?>js/tuner.js"></script>
		<div id="tuner" class="tuner">
			<label>Theme Colors</label>
			<ul class="colors">
				<li data-color="orange" class="color-orange"><span></span></li>
				<li data-color="purple" class="color-purple"><span></span></li>
				<li data-color="green" class="color-green"><span></span></li>
				<li data-color="pink" class="color-pink"><span></span></li>
				<li data-color="blue" class="color-blue active"><span></span></li>
				<li data-color="cyan" class="color-cyan"><span></span></li>
			</ul>
			<label>Layout Styles</label>
			<ul class="layouts">
				<li data-layout="boxed">Boxed</li>
				<li data-layout="widescreen" class="active">Widescreen</li>
			</ul>
			<i id="tuner-switcher" class="fa fa-cogs"></i>
		</div><!--/ tuner -->
	</body>
</html>