<!DOCTYPE html>
<html lang="pt-br">
	<head>
		<meta charset="UTF-8" />
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">

		<!-- Stylesheet
		================================================== -->
		<link rel="stylesheet" type="text/css" href="<?php echo CSS; ?>general.css">
		<link rel="stylesheet" type="text/css" href="<?php echo CSS; ?>update.css">
		<link rel="stylesheet" type="text/css" href="<?php echo CSS; ?>plugins.css">
		<link rel="stylesheet" type="text/css" href="<?php echo CSS; ?>fonts.css">
		<link rel="stylesheet" type="text/css" href="<?php echo CSS; ?>nav.css">
		<link rel="stylesheet" type="text/css" href="<?php echo CSS; ?>inputfile/inputfile.css" />
      <link rel="stylesheet" type="text/css" href="<?php echo CSS; ?>inputfile/component.css" />
      <link rel="stylesheet" type="text/css" href="<?php echo BOWER; ?>bootstrap-datepicker/dist/css/bootstrap-datepicker3.css" />

		<!-- Switcher Tuner Only -->
		<link rel="stylesheet" type="text/css" href="<?php echo TUNER; ?>css/tuner.css">

		<!-- Pre-Define Custom Style Sheet
		================================================== -->
		<link rel="stylesheet" href="<?php echo CSS; ?>themes/color-cyan.css" title="color-cyan" media="all" property="">
		<link rel="alternate stylesheet" href="<?php echo CSS; ?>themes/color-blue.css" title="color-blue" media="all" property="">
		<link rel="alternate stylesheet" href="<?php echo CSS; ?>themes/color-green.css" title="color-green" media="all" property="">
		<link rel="alternate stylesheet" href="<?php echo CSS; ?>themes/color-orange.css" title="color-orange" media="all" property="">
		<link rel="alternate stylesheet" href="<?php echo CSS; ?>themes/color-pink.css" title="color-pink" media="all" property="">
		<link rel="alternate stylesheet" href="<?php echo CSS; ?>themes/color-purple.css" title="color-purple" media="all" property="">
		<!-- remove this if you use Modernizr -->
		<!--<script>
			(function(e,t,n){var r=e.querySelectorAll("html")[0];r.className=r.className.replace(/(^|\s)no-js(\s|$)/,"$1js$2")})(document,window,0);
		</script>-->
		<script src="<?php echo JS; ?>register/inputfile/modernizr.js"></script>
	</head>
	<body>
		<!-- This section is for Splash Screen -->
		<section id="jSplash">
			<div id="circle"></div>
		</section>
		<!-- End of Splash Screen -->

		<!-- ==============================================
		Navbar (Menu Principal de Navegação)
		=============================================== -->
		<div id="home-nav" class="navbar navbar-default navbar-fixed-top" role="navigation">
			<div class="container">
				<div class="navbar-header">
					<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1"> <span class="sr-only">Toggle navigation</span> <span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> </button>
					<a class="navbar-brand" href="#home">
						<!-- Logo Header -->
						<section id="foxin" class="foxin">
							<div> <img src="<?php echo IMAGES; ?>Logo_Navbar.png" alt="Foxin by Elisandro Mello"> </div>
						</section>
						<!--/ Logo Header-->
					</a>
				</div>
				<div class="navbar-collapse collapse" id="bs-example-navbar-collapse-1">
					<ul class="nav navbar-nav navbar-right">
						<li><a href="<?php echo BASE . 'home/'; ?>">Home</a></li>
						<li><a href="#access">Acesso</a></li>
						<li><a href="#social">Sociais</a></li>
						<li><a href="#update-dataInfo">Pessoais</a></li>
						<li><a href="#skills">Qualificações</a></li>
						<li><a href="#historic">Histórico</a></li>
						<li><a href="<?php echo BASE . 'login/sair'; ?>" title="Logout Sistema">
				      	<span> <i class="fa fa-sign-out"></i> </span>
				   	</a></li>
					</ul>
				</div><!-- </navbar-collapse collapse" id="bs-example-navbar-collapse-1> -->
			</div><!-- </container> -->
		</div><!-- </navbar navbar-default navbar-fixed-top> -->