      <footer>
        <!-- ==============================================
             Footer (Rodapé)
        =============================================== -->
        <section class="social-links">
          <div class="container">
            <div class="row">
              <ul>
                 <li> <a href="https://www.facebook.com/profile.php?id=1800765934" target="_blank" title=""> <span> <i class="fa fa-facebook"></i> </span> </a> </li>
                 <li> <a href="https://twitter.com/elisandromello" target="_blank" title=""> <span> <i class="fa fa-twitter"></i> </span> </a> </li>
                 <li> <a href="http://www.linkedin.com/in/elisandromello" target="_blank" title=""> <span> <i class="fa fa-linkedin"></i> </span> </a> </li>
                 <li> <a href="http://www.instagram.com/iamelisandromello" target="_blank" title=""> <span> <i class="fa fa-instagram"></i> </span> </a> </li>
                 <li> <a href="https://github.com/iamelisandromello" target="_blank" title=""> <span> <i class="fa fa-github"></i> </span> </a> </li>
                 <li> <a href="mailto:iam@elisandromello.com.br?subject=Eu tenho um comentário para você..." title=""><span> <i class="fa fa-envelope"></i></span></a></li>
              </ul>
            </div><!-- /row -->
          </div><!-- /container -->
        </section>

        <!-- ==============================================
           Créditos (Credits)
        =============================================== -->
        <section class="copyright">
          <div class="container">
            <div class="col-md-12">
              <div class="text-center">
                <!-- Logo Header -->
                <section id="fox_footer" class="fox_footer">
                    <div> <img src="<?php echo IMAGES; ?>logofooter_login.png" alt="Foxin by Elisandro Mello">   -  &copy;<?php echo date("Y")  ?> - Design and Development Encoded by <i class="fa fa-cloud-upload"></i> Elisandro Mello</div>
                </section>
                <!--/ Logo Header-->
              </div>
            </div>
          </div>
        </section>
      </footer>

      <!-- ==============================================
      Javascripts - Inclua todos os plugins compilados (abaixo),
      ou inclua arquivos individuais conforme necessário
       ================================================== -->
      <!-- JQuery -->
      <script src="<?php echo BOWER; ?>jquery/dist/jquery.min.js"></script>
      <!-- Bootstrap -->
      <script src="<?php echo BOWER; ?>bootstrap-sass/assets/javascripts/bootstrap.min.js"></script>
      <!-- InputMask - Máscara Campos Input Formulário-->
      <script src="<?php echo JS; ?>register/jquery.inputmask.bundle.js"></script>
      <!-- Validate - Validação de Campos do Formulário -->
      <script src="<?php echo JS; ?>register/jquery.validate.js"></script>
      <script src="<?php echo JS; ?>register/retina-1.1.0.min.js"></script>
      <!-- Repeater - Inclusão de Elementos Dinâmicos p/Cadastro -->
      <script src="<?php echo JS; ?>register/jquery.repeater.min.js"></script>
      <script src="<?php echo JS; ?>register/jquery.backstretch.min.js"></script>
      <!-- <script src="<?php echo JS; ?>register/register.js"></script> -->
      <script src="<?php echo JS; ?>jquery.form-repeater.js"></script>
      <script src="<?php echo JS; ?>register/data/bootstrap-datepicker.js"></script>
      <script src="<?php echo CSS; ?>locales/bootstrap-datepicker.pt-BR.min.js"></script>      
      <script src="<?php echo JS; ?>register/input_validate.js"></script>
      <script src="<?php echo JS; ?>register/input_mask.js"></script>
      <script src="<?php echo JS; ?>register/search_cep.js"></script>

      <script src="<?php echo JS; ?>register/scripts.js"></script>
      
      <!--      
      <script src="<?php echo JS; ?>jquery.form-repeater.js"></script>
      <script src="<?php echo JS; ?>register/use-repeater.js"></script>
      <script src="<?php echo JS; ?>register/input_validate.js"></script>
      <script src="<?php echo JS; ?>register/register.js"></script>
      <script src="<?php echo JS; ?>register/input_mask.js"></script>
      <script src="<?php echo JS; ?>register/search_cep.js"></script>-->

      <script type="text/javascript">
        $('#academicRepeater').repeater({
            btnAddClass: 'a-btnAdd',
            btnRemoveClass: 'a-btnRemove',
            groupClass: 'a-group',
            minItems: 1,
            maxItems: 0,
            startingIndex: 0,
            reindexOnDelete: true,
            repeatMode: 'append',
            animation: 'fade',
            animationSpeed: 800,
            animationEasing: 'swing',
            clearValues: true
        });
      </script>
      <script type="text/javascript">
        $('#courseRepeater').repeater({
            btnAddClass: 'c-btnAdd',
            btnRemoveClass: 'c-btnRemove',
            groupClass: 'c-group',
            minItems: 1,
            maxItems: 0,
            startingIndex: 0,
            reindexOnDelete: true,
            repeatMode: 'append',
            animation: 'fade',
            animationSpeed: 800,
            animationEasing: 'swing',
            clearValues: true
        });
      </script>
      <script type="text/javascript">
        $('#professionalRepeater').repeater({
            btnAddClass: 'p-btnAdd',
            btnRemoveClass: 'p-btnRemove',
            groupClass: 'p-group',
            minItems: 1,
            maxItems: 0,
            startingIndex: 0,
            reindexOnDelete: true,
            repeatMode: 'append',
            animation: 'fade',
            animationSpeed: 800,
            animationEasing: 'swing',
            clearValues: true
        });
      </script>      

      <Script>
      $('#wraper_conclusion .input-group.date').datepicker({
          format: "dd/mm/yyyy",
          language: "pt-BR",
          clearBtn: true,
          autoclose: true,
          toggleActive: true
      });
      </Script>

    </div><!-- Fechamento div Geral -->
   </body>
</html>