<!DOCTYPE html>
<html lang="pt-br">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<title>Cadastro - ProfileIT </title>

      <!-- ==============================================
      CSS
      ================================================== -->
      <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Roboto:400,100,300,500"> 
      <link rel="stylesheet" type="text/css" href="<?php echo CSS; ?>plugins.css" />      
      <link rel="stylesheet" type="text/css" href="<?php echo CSS; ?>register.css" />    

		<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
		<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
		<!--[if lt IE 9]>
	   <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
	   <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
	   <![endif]-->

	   <!-- Favicon and touch icons -->
	   <link rel="shortcut icon" href="assets/ico/favicon.png">
	   <link rel="apple-touch-icon-precomposed" sizes="144x144" href="assets/ico/apple-touch-icon-144-precomposed.png">
	   <link rel="apple-touch-icon-precomposed" sizes="114x114" href="assets/ico/apple-touch-icon-114-precomposed.png">
	   <link rel="apple-touch-icon-precomposed" sizes="72x72" href="assets/ico/apple-touch-icon-72-precomposed.png">
	   <link rel="apple-touch-icon-precomposed" href="assets/ico/apple-touch-icon-57-precomposed.png">
	</head>

   <body>
   	<!-- Top menu -->
   	<nav class="navbar navbar-inverse navbar-no-bg" role="navigation">
   		<div class="container">
   			<div class="navbar-header">
   				<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#top-navbar-1">
   					<span class="sr-only">Toggle navigation</span>
   					<span class="icon-bar"></span>
   					<span class="icon-bar"></span>
   					<span class="icon-bar"></span>
   				</button>
   				<a class="navbar-brand" href="index.html">Bootstrap Multi Step Registration Form Template</a>
   			</div><!-- </navbar-header> -->
   			<!-- Collect the nav links, forms, and other content for toggling -->
   			<div class="collapse navbar-collapse" id="top-navbar-1">
   				<ul class="nav navbar-nav navbar-right">
   					<li>
   						<span class="li-text">
   							Documentation
   						</span> 
   						<a href="#"><strong>heare</strong></a> 
   						<span class="li-text">
   							, or access icons: 
   						</span> 
   						<span class="li-social">
                        <a href="#"><i class="fa fa-facebook"></i></a> 
   							<a href="#"><i class="fa fa-twitter"></i></a> 
   							<a href="#"><i class="fa fa-envelope"></i></a> 
   							<a href="#"><i class="fa fa-github"></i></a>
   						</span>
   					</li>
   				</ul><!-- </nav navbar-nav navbar-right> -->
   			</div><!-- </collapse navbar-collapse> -->
   		</div><!-- </container> -->
   	</nav><!-- </navbar navbar-inverse navbar-no-bg> -->