
   	<!-- Top content -->
   	<div class="top-content">
   		<div class="inner-bg">
   			<div class="container">
   				<div class="row">
   					<div class="col-sm-8 col-sm-offset-2 form-box">
   						<?php echo (isset($this->alert) ? $this->alert : ''); ?>
                     <form action="<?php echo BASE; ?>tests/cadastrar/" role="form" data-toggle="validator" method="POST" class="clearfix registration-form" enctype="multipart/form-data">
                     <!--<form data-toggle="validator" role="form">-->                       
                        <fieldset>
                           <div class="form-top">
                              <div class="form-top-left">
                                 <h3>Step 6 / 7</h3>
                                 <p>Professional History:</p>
                              </div>
                              <div class="form-top-right">
                                 <i class="fa fa-th-list"></i>
                              </div>
                           </div>
                           <div class="form-bottom">
                              <div class="repeater-custom-show-hide">
                                 <div data-repeater-list="historic">                                 
                                    <div data-repeater-item>
                                       <div class="row">
                                          <div class="col-md-6">
                                             <div class="form-group">
                                                <label class="sr-only" for="company">Company</label>
                                                <input type="text" name="company" placeholder="Company..." class="form-company form-control" id="company">
                                             </div>
                                          </div><!-- </col-md-6> -->
                                       </div><!-- </row>-->                                      
                                       <div class="row">
                                          <div class="col-md-12">
                                             <div class="row">
                                                <div class="col-md-4 col-md-offset-4">
                                                   <div class="form-group">
                                                      <span data-repeater-delete class="btn btn-danger btn-sm">
                                                         <span class="glyphicon glyphicon-remove"></span> Delete
                                                      </span>
                                                   </div>                      
                                                </div><!-- </col-md-4> -->
                                                <div class="col-md-4">
                                                   <div class="form-group">
                                                      <span data-repeater-create data-tooltip="Include new skills" class="btn btn-info btn-md">
                                                         <span class="glyphicon glyphicon-plus"></span> add
                                                      </span>
                                                   </div>                      
                                                </div><!-- </col-md-4> -->                             
                                             </div><!-- </row>-->
                                          </div><!-- </col-md-12> -->
                                       </div>
                                    </div><!-- </data-repeater-item> -->
                                    <hr/>

                              <div class="row">
                                 <div class="col-md-12">
                                    <div class="form-group">
                                       <button type="button" class="btn-previous">
                                          <i class="fa fa-arrow-left"></i>
                                          <span>Previous</span>
                                       </button>
                                       <button type="submit" value="Submit" class="disabled">   
                                          <i class="fa fa-user"></i>
                                          <span>Sign UP</span>
                                       </button>   
                                    </div><!-- </form-group> -->                     
                                 </div><!-- </col-md-12> -->
                              </div><!-- </row> -->

                                 </div><!-- </data-repeater-list> -->           
                              </div><!-- </repeater-custom-show-hide> -->


                           </div><!-- </form-bottom> -->
                        </fieldset>
                                
                     </form><!-- </registration-form> -->
   					</div><!-- </form-box> -->
   				</div><!-- </row>  -->
   			</div><!-- </container>  -->
   		</div><!-- </inner-bg> -->
   	</div><!-- </top-content> -->