<!-- Top content -->
      <div class="top-content">
         <div class="inner-bg">
            <div class="container">
               <div class="row">
                  <div class="col-sm-8 col-sm-offset-2 form-box">
                     <?php echo (isset($this->alert) ? $this->alert : ''); ?>

                     <form action="" method="post" id="registration-form" class="registration-form">

                        <fieldset>
                           <div class="form-top">
                              <div class="form-top-left">
                                 <h3>Step 5 / 7</h3>
                                 <p>Academic Historic:</p>
                              </div>
                              <div class="form-top-right">
                                 <i class="fa-graduation-cap"></i>
                              </div>
                           </div>
                           <div class="form-bottom">                              
                              <div class="academic-repeater">
                                 <div data-repeater-list="academic-group" class="academic">
                                    <div data-repeater-item class="academic">
                                       <!--
                                       1º Linha Formulario Acadêmico
                                       -->
                                       <div class="row">
                                          <div class="col-md-6">
                                             <div class="form-group">
                                                <label class="sr-only" for="institution">Institution</label>
                                                <input type="text" name="institution" placeholder="Institution..." class="form-institution form-control academic" data-minlength="5" data-maxlength="10" required >
                                                <div class="help-block with-errors"></div>
                                             </div>
                                          </div><!-- </col-md-6> -->
                                          <div class="col-md-6">
                                             <div class="form-group">
                                                <label class="sr-only" for="local">Local</label>
                                                <input type="text" name="local" id="local" placeholder="Local..." class="form-local form-control academic" required>
                                                <div class="help-block with-errors"></div>
                                             </div><!-- </form-group> -->                    
                                          </div><!-- </col-md-6> -->
                                       </div><!-- </row>-->
                                       <!--
                                       2º Linha Formulario Acadêmico
                                       -->
                                       <div class="row">
                                          <div class="col-md-6">
                                             <div class="form-group">
                                                <label class="sr-only" for="course">Course</label>
                                                <input type="text" name="course" id="course" placeholder="Course" class="form-course form-control academic" required>
                                                <div class="help-block with-errors"></div>
                                             </div><!-- </form-group> -->
                                          </div><!-- </col-md-6> -->
                                          <div class="col-md-6">
                                             <div class="form-group">
                                                <label class="sr-only" for="date_out">Level</label>
                                                <select id="formation_list" name="formation_list" class="register-select academic" form="form-register" data-required>
                                                   <option class="opt-placeholder" value="-1" selected="">Formation
                                                   </option>
                                                   <optgroup label="Nível">
                                                   <option value="PHD">PHD</option>
                                                   <option value="Doutorado">Doutorado</option>
                                                   <option value="Mestrado">Mestrado</option>
                                                   <option value="Pós Graduação">Pós Graduação</option>
                                                   <option value="Graduação">Graduação</option>
                                                   <option value="Técnico">Técnico</option>
                                                   <option value="Ensino Médio">Ensino Médio</option>
                                                   </optgroup>
                                                </select>
                                                <div class="help-block with-errors"></div> 
                                             </div><!-- </form-group> -->                     
                                          </div><!-- </col-md-6> -->                           
                                       </div><!-- </row>-->
                                       <!--
                                       3º Linha Formulario Acadêmico
                                       -->                                       
                                       <div class="row">
                                          <div class="col-md-3">
                                             <div class="form-group">
                                                <label class="sr-only" for="conclusion-date">Conclusion Date</label>
                                                <input type="text" name="conclusion_date" class="form-conclusion_date form-control academic" placeholder="00/00/0000" value="<?php echo $this->request->post('conclusion_date') ?>" required >
                                                <div class="help-block with-errors"></div>
                                             </div><!-- </form-group> -->
                                          </div>
                                          <div class="col-md-3">
                                             <div class="form-group">
                                                <span data-repeater-delete class="btn btn-danger btn-sm academic">
                                                <span class="glyphicon glyphicon-remove"></span> Delete
                                                </span>
                                             </div>                      
                                          </div><!-- </col-md-4> -->
                                          <div class="col-md-6">
                                             <div class="row">
                                                <div class="col-md-12 wrapper_radio">
                                                   <div class="form-group">
                                                      <div class="row">
                                                         <div class="col-md-6">
                                                            <input type="radio" id="radio01" name="radioAcademic" class="radio-academic academic" value="1" required>
                                                            <label for="radio01"><span></span>Complete</label>              
                                                         </div>
                                                         <div class="col-md-6">
                                                            <input type="radio" id="radio02" name="radioAcademic" class="radio-academic academic" value="2" >
                                                            <label for="radio02"><span></span>Progress</label>           
                                                         </div>                    
                                                      </div>
                                                      <div class="row">
                                                         <div class="col-md-12">
                                                            <input type="radio" id="radio03" name="radioAcademic" class="radio-academic academic" value="3" >
                                                            <label for="radio03"><span></span>Locked</label>              
                                                         </div>
                                                      </div>
                                                   </div><!-- </div>form-group> -->
                                                </div><!-- </col-md-12 wrapper_radio> -->
                                             </div><!-- </row> -->
                                          </div><!-- </col-md-6> -->
                                       </div><!-- </row> -->
                                    <hr/><!-- Traço separador do Repeater -->
                                    </div><!-- </data-repeater-item> -->
                                 </div><!-- </data-repeater-list> -->
                                 <!--
                                 Button Add New Historico Academico
                                 -->                                
                                 <div class="row">
                                    <div class="col-md-4">
                                       <div class="form-group">
                                          <span data-repeater-create data-tooltip="Include new skills" name="add-academic" id="add-academic" class="btn btn-info btn-md academic">
                                             <span class="glyphicon glyphicon-plus"></span> add
                                          </span>
                                       </div>                      
                                    </div><!-- </col-md-4> -->  
                                 </div>      
                              </div><!-- </academic-repeater> -->
                              
                              <div class="row">
                                 <div class="col-md-12">
                                    <div class="form-group">
                                       <button type="button" class="btn-previous">
                                          <i class="fa fa-arrow-left"></i>
                                          <span>Previous</span>
                                       </button>
                                       <button type="submit" value="Submit" class="disabled">   
                                          <i class="fa fa-user"></i>
                                          <span>Sign UP</span>
                                       </button>
                                    </div><!-- </form-group> -->                     
                                 </div><!-- </col-md-12> -->
                              </div><!-- </row> -->
                           </div><!-- </form-bottom> -->
                        </fieldset><!-- </Academic Historic> -->                     

                        <div class="" style="background-color: #f2f2f2; padding: 30px;">
                            <div class="form-group">
                                <label for="nome">Nome</label>
                                <input type="text" name="nome" id="nome" required minlength="5" class="form-control pulacampos">
                            </div>

                            <div class="form-group">
                                <label for="email">Email</label>
                                <input type="email" name="email" id="email" required class="form-control pulacampos"></input>
                            </div>

                            <div class="form-group">
                                <label for="telefone">Telefone</label>
                                <input type="text" name="telefone" id="telefone" required class="form-control pulacampos"></input>
                            </div>

                            <div class="form-group">
                                <label for="celular">Celular</label>
                                <input type="text" name="celular" id="celular" required class="form-control pulacampos"></input>
                            </div>
                        </div>
                        <hr>

                        <div class="" style="background-color: #e7c5ff; padding: 30px;">
                            <div class="form-group">
                                <label for="cep">CEP</label>
                                <div class="text-success" id="infocep"></div>
                                <input type="text" name="cep" id="cep" required class="form-control pulacampos"></input>
                            </div>

                            <div class="form-group">
                                <label for="rua">Rua</label>
                                <input type="text" name="rua" id="rua" required class="form-control pulacampos"></input>
                            </div>

                            <div class="form-group">
                                <label for="bairro">Bairro</label>
                                <input type="text" name="bairro" id="bairro" required class="form-control pulacampos"></input>
                            </div>

                            <div class="form-group">
                                <label for="estado">Estado</label>
                                <input type="text" name="estado" id="estado" required class="form-control pulacampos"></input>
                            </div>

                            <div class="form-group">
                                <label for="cidade">Cidade</label>
                                <input type="text" name="cidade" id="cidade" required class="form-control pulacampos"></input>
                            </div>
                        </div>
                        <hr>

                        <div class="" style="background-color: #c8e9ed; padding: 30px;">
                            <div class="form-group">
                                <br>
                                <label for="usuario">Usuario</label>
                                <input type="text" name="usuario" id="usuario" required class="form-control pulacampos"></input>
                            </div>

                            <hr>
                            <div class="form-group">
                                <label for="senha">Senha</label>
                                <input type="password" name="senha" id="senha" required class="form-control pulacampos"></input>
                            </div>

                            <div class="form-group">
                                <label for="senhaconfirma">Senha Confirma</label>
                                <input type="password" name="senhaconfirma" id="senhaconfirma" required class="form-control pulacampos"></input>
                            </div>
                            <hr>

                            <div class="form-group text-center">
                                <label for="termos">Termos</label>
                                <br>
                                <input type="checkbox" name="termos" id="termos" required class=""> Voce aceita todos os termos neste cadastro?</input>
                            </div>
                            <div class="form-group">
                                <label for="mensagem">Mensagem</label>
                                <textarea type="text" name="mensagem" rows="5" id="mensagem" required class="form-control"></textarea>
                            </div>
                        </div>
                        <hr>

                        <div>
                            <input type="submit" class="btn btn-success btn-block" value="ENVIAR" >
                        </div>
                    </form>

                  </div><!-- </form-box> -->
               </div><!-- </row>  -->
            </div><!-- </container>  -->
         </div><!-- </inner-bg> -->
      </div><!-- </top-content> -->