<!-- Top content -->
      <div class="top-content">
         <div class="inner-bg">
            <div class="container">
               <div class="row">
                  <div class="col-sm-8 col-sm-offset-2 form-box">
                    <?php echo (isset($this->alert) ? $this->alert : ''); ?>
                    <form action="" method="post" id="registration-form" class="registration-form">
                      <fieldset>
                         <div class="form-top">
                            <div class="form-top-left">
                               <h3>Step 1 / 7</h3>
                               <p>Personal Data:</p>
                            </div>
                            <div class="form-top-right">
                               <i class="fa fa-user"></i>
                            </div>
                         </div><!-- </form-top> -->
                         <div class="form-bottom">                                 
                            <div class="row">
                               <div class="col-md-4">
                                  <div class="form-group">
                                     <label class="sr-only" for="name">First name</label>
                                     <input type="text" name="name" id="name" placeholder="First name..." class="form-control academic" value="<?php echo $this->request->post('name') ?>" >
                                  </div><!-- </form-group> -->
                               </div><!-- </col-md-4> -->
                               <div class="col-md-8">
                                  <div class="form-group">
                                     <label class="sr-only" for="form_last_name">Last name</label>
                                     <input type="text" name="last_name" id="last_name" placeholder="Last name..." class="form-control academic" required>
                                  </div><!-- </form-group> -->
                               </div><!-- </col-md-8> -->
                            </div><!-- </row> -->   
                            <div class="row">
                               <div class="col-md-4">
                                  <div class="form-group">
                                     <label class="sr-only" for="birth_date">Birth Date</label>
                                     <input type="text" name="birth_date" id="birth_date" placeholder="00/00/0000" class="form-control academic" value="<?php echo $this->request->post('birth_date') ?>" >
                                  </div><!-- </form-group> -->
                               </div>                              
                               <div class="col-md-4">
                                  <div class="form-group">
                                     <label class="sr-only" for="celular">Phone Mobile</label>
                                     <input type="text" class="form-control academic" name="celular" id="celular" placeholder="(00)99999-9999" value="<?php echo $this->request->post('celular') ?>" >
                                     <div class="help-block with-errors"></div>
                                  </div><!-- </form-group> --> 
                               </div><!-- </col-md-6> -->
                               <div class="col-md-4">
                                  <div class="form-group">
                                     <label class="sr-only" for="phone">Phone Residencial</label>
                                     <input type="text" class="form-control" name="phone" id="phone" placeholder="(00)0000-0000" value="<?php echo $this->request->post('phone') ?>" >
                                     <div class="help-block with-errors"></div>
                                  </div><!-- </form-group> -->                     
                               </div><!-- </col-md-6> -->
                            </div><!-- </row> -->                              
                            <div class="row">
                               <div class="col-md-12">
                                  <div class="form-group">
                                     <label class="sr-only" for="form-about-yourself">About yourself</label>
                                     <textarea name="about" id="about" placeholder="About yourself..." class="form-about-yourself form-control"></textarea>
                                  </div><!-- </form-group> -->                              
                               </div><!-- </col-md-12> -->
                            </div><!-- </row> -->
                            <div class="row">
                               <div class="col-md-12">
                                  <div class="form-group">
                                     <button type="button" class="btn-next">
                                        <i class="fa fa-arrow-right"></i>
                                        <span>Next</span>
                                     </button>
                                  </div><!-- </form-group> -->                              
                               </div><!-- </col-md-12> -->
                            </div><!-- </row> -->                                 
                         </div><!-- </form-bottom> -->
                      </fieldset> 
                      <fieldset>
                         <div class="form-top">
                            <div class="form-top-left">
                               <h3>Step 2 / 7</h3>
                               <p>Access & Password:</p>
                            </div>
                            <div class="form-top-right">
                               <i class="fa fa-key"></i>
                            </div>
                         </div>
                         <div class="form-bottom">
                            <div class="row">
                               <div class="col-md-6">
                                  <div class="form-group">
                                     <label class="sr-only" for="username">Username</label>
                                     <input type="text" name="username" id="username" placeholder="Username..." class="form-control academic" value="<?php echo $this->request->post('username') ?>">
                                     <div class="help-block with-errors"></div>
                                  </div>
                               </div>
                               <div class="col-md-6">                                   
                                  <div class="form-group">
                                     <label class="sr-only" for="form-email">Email</label>         
                                     <input type="email" class="form-control academic" name="email" id="email" placeholder="Email" value="<?php echo $this->request->post('email') ?>" >
                                     <div class="help-block with-errors"></div>
                                  </div>
                               </div>
                            </div>
                            <div class="row">
                               <div class="col-md-12">
                                  <div class="form-group">
                                     <label class="sr-only" for="form-senha">Password</label>
                                     <input type="password" class="form-control academic" name="senha" id="senha" placeholder="Password">
                                     <div class="help-block">Minimum of 8 characters</div>
                                  </div><!-- </form-group> -->                     
                               </div><!-- </col-md-12> -->
                            </div><!-- </row> -->
                            <div class="row">
                               <div class="col-md-12">
                                  <div class="form-group">
                                     <label class="sr-only" for="form-confirmaSenha">Repeat password</label>
                                        <input type="password" class="form-control academic" id="confirmaSenha" name="confirmaSenha" placeholder="Confirm" >
                                        <div class="help-block with-errors"></div>
                                  </div><!-- </form-group> -->                     
                               </div><!-- </col-md-12> -->
                            </div><!-- </row> -->
                            <div class="row">
                               <div class="col-md-12">
                                  <div class="form-group">
                                     <button type="button" class="btn-previous">
                                        <i class="fa fa-arrow-left"></i>
                                        <span>Previous</span>
                                     </button>        
                                     <button type="button" class="btn-next">
                                        <i class="fa fa-arrow-right"></i>
                                        <span>Next</span>
                                     </button> 
                                  </div><!-- </form-group> -->                     
                               </div><!-- </col-md-12> -->
                            </div><!-- </row> -->
                         </div><!-- </form-bottom> -->
                      </fieldset><!-- </Access & Password> -->
                      <fieldset>
                         <div class="form-top">
                            <div class="form-top-left">
                               <h3>Step 3 / 7</h3>
                               <p>Address Localization:</p>
                            </div>
                            <div class="form-top-right">
                               <i class="fa fa-globe"></i>
                            </div>
                         </div>
                         <div class="form-bottom">
                            <div class="row">
                               <div class="col-md-7">
                                  <div class="form-group">
                                    <label class="sr-only" for="address">Zip Code</label>
                                    <div class="text-success" id="infocep"></div>
                                    <input type="text" name="zipcode" id="zipcode" placeholder="Zip Code..." required class="form-control pulacampos" value="<?php echo $this->request->post('zipcode') ?>"></input>
                                  </div>
                               </div><!-- </col-md-9> -->
                            </div><!-- </row> -->                   
                            
                            <div class="row">
                              <div class="col-md-12">  
                                <div class="form-group">
                                    <label class="sr-only" for="address">Address</label>
                                    <input type="text" name="address" id="address" placeholder="Address..." required class="form-control pulacampos" value="<?php echo $this->request->post('address') ?>"></input>
                                </div>
                              </div>
                            </div>
                            <div class="row">
                              <div class="col-md-5">    
                                <div class="form-group">
                                  <label class="sr-only" for="address">Beighborhood</label>
                                  <input type="text" name="beighborhood" id="beighborhood" placeholder="Beighborhood" required class="form-control pulacampos"></input>
                                </div>
                              </div>  
                              <div class="col-md-2">
                                <div class="form-group">
                                  <label class="sr-only" for="address">State</label>
                                  <input type="text" name="state" id="state" placeholder="UF" required class="form-control pulacampos"></input>
                                </div>
                              </div>  
                              <div class="col-md-5">
                                <div class="form-group">
                                  <label class="sr-only" for="address">City</label>
                                  <input type="text" name="city" id="city" placeholder="City" required class="form-control pulacampos"></input>
                                </div>
                              </div>
                            </div>
                            <div class="row">
                               <div class="col-md-12">
                                  <div class="form-group">
                                     <button type="button" class="btn-previous">   
                                        <i class="fa fa-arrow-left"></i>
                                        <span>Previous</span>
                                     </button>
                                     <button type="button" class="btn-next">
                                        <i class="fa fa-arrow-right"></i>
                                        <span>Next</span>
                                     </button>
                                  </div><!-- </form-group> -->                     
                               </div><!-- </col-md-12> -->
                            </div><!-- </row> -->
                         </div><!-- </form-bottom> -->
                      </fieldset><!-- </Address & Localization> -->                        
                      <fieldset>
                         <div class="form-top">
                            <div class="form-top-left">
                               <h3>Step 4 / 7</h3>
                               <p>Social media profiles:</p>
                            </div>
                            <div class="form-top-right">
                               <i class="fa fa-twitter"></i>
                            </div>
                         </div>
                         <div class="form-bottom">
                            <div class="row">
                               <div class="col-md-6">
                                  <div class="form-group">
                                     <label class="sr-only" for="facebook">Facebook</label>
                                     <input type="text" name="facebook" id="facebook" placeholder="Facebook..." class="form-facebook form-control" value="<?php echo $this->request->post('facebook') ?>" >
                                  </div>
                               </div><!-- </col-md-6> -->
                               <div class="col-md-6">
                                  <div class="form-group">
                                     <label class="sr-only" for="twitter">Twitter</label>
                                     <input type="text" name="twitter" id="twitter" placeholder="Twitter..." class="form-twitter form-control" value="<?php echo $this->request->post('twitter') ?>" >
                                  </div>                                       
                               </div><!-- </col-md-6> -->
                            </div><!-- </row> -->

                            <div class="row">
                               <div class="col-md-6">
                                  <div class="form-group">
                                     <label class="sr-only" for="instagram">Instagram</label>
                                     <input type="text" name="instagram" id="instagram" placeholder="Instagram..." class="form-instagram form-control" value="<?php echo $this->request->post('instagram') ?>" >
                                  </div>                                       
                               </div><!-- </col-md-6> -->
                               <div class="col-md-6">
                                    <div class="form-group">
                                     <label class="sr-only" for="linkedin">Linkedin</label>
                                     <input type="text" name="linkedin" id="linkedin" placeholder="Linkedin..." class="form-linkedin form-control" value="<?php echo $this->request->post('linkedin') ?>" >
                                  </div>                                      
                               </div><!-- </col-md-6> -->
                            </div><!-- </row> -->
                            <div class="row">
                               <div class="col-md-6">
                                  <div class="form-group">
                                     <label class="sr-only" for="github">GitHub</label>
                                     <input type="text" id="github" name="github" placeholder="GitHub..." class="form-github form-control" value="<?php echo $this->request->post('github') ?>" >
                                  </div>                                       
                               </div><!-- </col-md-6> -->
                               <div class="col-md-6">
                                  <div class="form-group">
                                     <label class="sr-only" for="web">Web</label>
                                     <input type="text" name="web" id="web" placeholder="Web..." class="form-web form-control" value="<?php echo $this->request->post('web') ?>" >
                                  </div>                                        
                               </div><!-- </col-md-6> -->
                            </div><!-- </row> -->
                            <div class="row">
                               <div class="col-md-12">
                                  <div class="form-group">
                                     <button type="button" class="btn-previous">   
                                        <i class="fa fa-arrow-left"></i>
                                        <span>Previous</span>
                                     </button>
                                     <button type="button" class="btn-next">
                                        <i class="fa fa-arrow-right"></i>
                                        <span>Next</span>
                                     </button> 
                                  </div><!-- </form-group> -->                     
                               </div><!-- </col-md-12> -->
                            </div><!-- </row> -->
                         </div><!-- </form-bottom> -->
                      </fieldset><!-- </Social media profiles> -->
                      
                      <fieldset>
                         <div class="form-top">
                            <div class="form-top-left">
                               <h3>Step 5 / 7</h3>
                               <p>Academic Historic:</p>
                            </div>
                            <div class="form-top-right">
                               <i class="fa-graduation-cap"></i>
                            </div>
                         </div>
                         <div class="form-bottom">                              
                            <div class="academic-repeater">
                               <div data-repeater-list="academic-group" class="academic">
                                  <div data-repeater-item class="academic">
                                     <!--
                                     1º Linha Formulario Acadêmico
                                     -->
                                     <div class="row">
                                        <div class="col-md-6">
                                           <div class="form-group">
                                              <label class="sr-only" for="institution">Institution</label>
                                              <input type="text" name="institution" placeholder="Institution..." class="form-institution form-control academic pulacampos" >
                                              <div class="help-block with-errors"></div>
                                           </div>
                                        </div><!-- </col-md-6> -->
                                        <div class="col-md-6">
                                           <div class="form-group">
                                              <label class="sr-only" for="local">Local</label>
                                              <input type="text" name="local" id="local" placeholder="Local..." class="form-local form-control academic" required>
                                              <div class="help-block with-errors"></div>
                                           </div><!-- </form-group> -->                    
                                        </div><!-- </col-md-6> -->
                                     </div><!-- </row>-->
                                     <!--
                                     2º Linha Formulario Acadêmico
                                     -->
                                     <div class="row">
                                        <div class="col-md-6">
                                           <div class="form-group">
                                              <label class="sr-only" for="course">Course</label>
                                              <input type="text" name="course" id="course" placeholder="Course" class="form-course form-control academic" required>
                                              <div class="help-block with-errors"></div>
                                           </div><!-- </form-group> -->
                                        </div><!-- </col-md-6> -->
                                        <div class="col-md-6">
                                           <div class="form-group">
                                              <label class="sr-only" for="date_out">Level</label>
                                              <select id="formation_list" name="formation_list" class="register-select academic" form="form-register" data-required>
                                                 <option class="opt-placeholder" value="-1" selected="">Formation
                                                 </option>
                                                 <optgroup label="Nível">
                                                 <option value="PHD">PHD</option>
                                                 <option value="Doutorado">Doutorado</option>
                                                 <option value="Mestrado">Mestrado</option>
                                                 <option value="Pós Graduação">Pós Graduação</option>
                                                 <option value="Graduação">Graduação</option>
                                                 <option value="Técnico">Técnico</option>
                                                 <option value="Ensino Médio">Ensino Médio</option>
                                                 </optgroup>
                                              </select>
                                              <div class="help-block with-errors"></div> 
                                           </div><!-- </form-group> -->                     
                                        </div><!-- </col-md-6> -->                           
                                     </div><!-- </row>-->
                                     <!--
                                     3º Linha Formulario Acadêmico
                                     -->                                       
                                     <div class="row">
                                        <div class="col-md-3">
                                           <div class="form-group">
                                              <label class="sr-only" for="conclusion-date">Conclusion Date</label>
                                              <input type="text" name="conclusion_date" class="form-conclusion_date form-control academic" placeholder="00/00/0000" value="<?php echo $this->request->post('conclusion_date') ?>" required >
                                              <div class="help-block with-errors"></div>
                                           </div><!-- </form-group> -->
                                        </div>
                                        <div class="col-md-3">
                                           <div class="form-group">
                                              <span data-repeater-delete class="btn btn-danger btn-sm academic">
                                              <span class="glyphicon glyphicon-remove"></span> Delete
                                              </span>
                                           </div>                      
                                        </div><!-- </col-md-4> -->
                                        <div class="col-md-6">
                                           <div class="row">
                                              <div class="col-md-12 wrapper_radio">
                                                 <div class="form-group">
                                                    <div class="row">
                                                       <div class="col-md-6">
                                                          <input type="radio" id="radio01" name="radioAcademic" class="radio-academic academic" value="1" required>
                                                          <label for="radio01"><span></span>Complete</label>              
                                                       </div>
                                                       <div class="col-md-6">
                                                          <input type="radio" id="radio02" name="radioAcademic" class="radio-academic academic" value="2" >
                                                          <label for="radio02"><span></span>Progress</label>           
                                                       </div>                    
                                                    </div>
                                                    <div class="row">
                                                       <div class="col-md-12">
                                                          <input type="radio" id="radio03" name="radioAcademic" class="radio-academic academic" value="3" >
                                                          <label for="radio03"><span></span>Locked</label>              
                                                       </div>
                                                    </div>
                                                 </div><!-- </div>form-group> -->
                                              </div><!-- </col-md-12 wrapper_radio> -->
                                           </div><!-- </row> -->
                                        </div><!-- </col-md-6> -->
                                     </div><!-- </row> -->
                                  <hr/><!-- Traço separador do Repeater -->
                                  </div><!-- </data-repeater-item> -->
                               </div><!-- </data-repeater-list> -->
                               <!--
                               Button Add New Historico Academico
                               -->                                
                               <div class="row">
                                  <div class="col-md-4">
                                     <div class="form-group">
                                        <span data-repeater-create data-tooltip="Include new skills" name="add-academic" id="add-academic" class="btn btn-info btn-md academic">
                                           <span class="glyphicon glyphicon-plus"></span> add
                                        </span>
                                     </div>                      
                                  </div><!-- </col-md-4> -->  
                               </div>      
                            </div><!-- </academic-repeater> -->
                            
                            <div class="row">
                               <div class="col-md-12">
                                  <div class="form-group">
                                     <button type="button" class="btn-previous">
                                        <i class="fa fa-arrow-left"></i>
                                        <span>Previous</span>
                                     </button>
                                     <button type="submit" value="Submit" class="disabled">   
                                        <i class="fa fa-user"></i>
                                        <span>Sign UP</span>
                                     </button>
                                  </div><!-- </form-group> -->                     
                               </div><!-- </col-md-12> -->
                            </div><!-- </row> -->
                         </div><!-- </form-bottom> -->
                      </fieldset><!-- </Academic Historic> -->                     
                    </form>
                  </div><!-- </form-box> -->
               </div><!-- </row>  -->
            </div><!-- </container>  -->
         </div><!-- </inner-bg> -->
      </div><!-- </top-content> -->