<!-- Top content -->
      <div class="top-content">
         <div class="inner-bg">
            <div class="container">
               <div class="row">
                  <div class="col-sm-8 col-sm-offset-2 form-box">
                     <?php echo (isset($this->alert) ? $this->alert : ''); ?>
                     <form action="<?php echo BASE; ?>tests/cadastrar/" role="form" data-toggle="validator" method="post" class="registration-form" id="form-academic">                       
                        <fieldset>
                           <div class="form-top">
                              <div class="form-top-left">
                                 <h3>Step 6 / 7</h3>
                                 <p>Free Courses:</p>
                              </div>
                              <div class="form-top-right">
                                 <i class="fa-graduation-cap"></i>
                              </div>
                           </div>
                           <div class="form-bottom">

                              <div class="repeater-custom-show-hide">
                                 <div data-repeater-list="courses">                                 
                                    <div data-repeater-item>
                                       <div class="row">
                                          <div class="col-md-12">
                                             <div class="form-group">
                                                <label class="sr-only" for="institution">Course Title</label>
                                                <input type="text" name="title" placeholder="Course Title..." class="form-title form-control" id="title">
                                             </div>
                                          </div><!-- </col-md-12> -->
                                       </div><!-- </row>-->
                                       <div class="row">
                                          <div class="col-md-8">
                                             <div class="form-group">
                                                <label class="sr-only" for="institution">Institution</label>
                                                <input type="text" name="institution" placeholder="Institution..." class="form-institution form-control" id="institution">
                                             </div>
                                          </div><!-- </col-md-8> -->
                                           <div class="col-md-4">
                                             <div class="form-group">
                                                <label class="sr-only" for="date_out">Segment</label>
                                                <select name="formation-list" class="register-select" form="form-academic">
                                                   <option class="opt-placeholder" value="-1" selected="">Segment
                                                   </option>
                                                   <optgroup label="Area">
                                                   <option value="Microsoft">Microsoft</option>
                                                   <option value="Linux">Linux</option>
                                                   <option value="Management">Management</option>
                                                   <option value="Specializations">Specializations</option>                                          
                                                   </optgroup>
                                                </select> 
                                             </div><!-- </form-group> -->                     
                                          </div><!-- </col-md-4> -->
                                       </div><!-- </row>-->
                                       <div class="row">
                                          <div class="col-md-5">
                                             <div class="form-group">
                                                <label class="sr-only" for="institution">Workload</label>
                                                <input type="text" name="workload" placeholder="Workload..." class="form-workload form-control" id="workload">
                                             </div>
                                          </div>
                                          <div class="col-md-4">
                                             <div class="form-group">
                                                <label class="sr-only" for="date_conclusion">Conclusion Date</label>
                                                <input type="text" name="conclusion_date" id="conclusion_date" placeholder="00/00/0000" class="form-conclusion_date form-control" value="<?php echo $this->request->post('conclusion_date') ?>" required>
                                             </div><!-- </form-group> -->
                                          </div>
                                          <div class="col-md-3 col-md-offset-0">
                                             <div class="form-group">
                                                <span data-repeater-delete class="btn btn-danger btn-sm">
                                                   <span class="glyphicon glyphicon-remove"></span> Delete
                                                </span>
                                             </div>                      
                                          </div><!-- </col-md-4> -->
                                       </div><!-- </row> -->
                                    </div><!-- </data-repeater-item> -->
                                    <hr/>
                                 </div><!-- </data-repeater-list> -->
                                 <div class="row">
                                    <div class="col-md-4">
                                       <div class="form-group">
                                          <span data-repeater-create data-tooltip="Include new skills" class="btn btn-info btn-md">
                                             <span class="glyphicon glyphicon-plus"></span> add
                                          </span>
                                       </div>                      
                                    </div><!-- </col-md-4> -->  
                                 </div>      
                              </div><!-- </repeater-custom-show-hide> -->

                              <div class="row">
                                 <div class="col-md-12">
                                    <div class="form-group">
                                       <button type="button" class="btn-previous">
                                          <i class="fa fa-arrow-left"></i>
                                          <span>Previous</span>
                                       </button>
                                       <button type="submit" value="Submit" class="disabled">   
                                          <i class="fa fa-user"></i>
                                          <span>Sign UP</span>
                                       </button> 
                                    </div><!-- </form-group> -->                     
                                 </div><!-- </col-md-12> -->
                              </div><!-- </row> -->

                           </div><!-- </form-bottom> -->
                        </fieldset><!-- </Social media profiles> -->                         
                     </form><!-- </registration-form> -->
                  </div><!-- </form-box> -->
               </div><!-- </row>  -->
            </div><!-- </container>  -->
         </div><!-- </inner-bg> -->
      </div><!-- </top-content> -->