		<!-- Top content -->
		<div class="top-content">
			<div class="inner-bg">
				<div class="container">
					<div class="row">
						<div class="col-sm-8 col-sm-offset-2 form-box">
							<?php echo (isset($this->alert) ? $this->alert : ''); ?>
							<form action="<?php echo BASE; ?>temp/academic/" method="post" id="registration-form" class="registration-form">

								<!--
		                     Passo Formulario de Redes Sociais
		                  -->
		                  <fieldset id="stepSocial">
		                  	<div class="form-top">
		                  		<div class="form-top-left">
		                  			<h3>Step 4 / 8</h3>
		                  			<p>Redes Sociais:</p>
		                  		</div>
		                  		<div class="form-top-right">
		                  			<i class="fa fa-twitter"></i>
		                  		</div>
		                  	</div>
		                  	<div class="form-bottom">
		                        <!--
		                        	1º Linha Formulario  Redes Sociais
		                        -->
		                        <div class="row">
		                        	<div class="col-md-6">
		                        		<div class="form-group">
		                        			<label class="sr-only" for="facebook">Facebook</label>
		                        			<input type="text" name="facebook" id="facebook" placeholder="Facebook..." class="form-facebook form-control redessociais" value="<?php echo $this->request->post('facebook') ?>" >
		                        		</div>
		                        	</div><!-- </col-md-6> -->
		                        	<div class="col-md-6">
		                        		<div class="form-group">
		                        			<label class="sr-only" for="twitter">Twitter</label>
		                        			<input type="text" name="twitter" id="twitter" placeholder="Twitter..." class="form-twitter form-control redessociais no_obligatory" value="<?php echo $this->request->post('twitter') ?>" >
		                        		</div>
		                        	</div><!-- </col-md-6> -->
		                        </div><!-- </row> -->
		                        <!--
		                        	2º Linha Formulario  Redes Sociais
		                        -->
		                        <div class="row">
		                        	<div class="col-md-6">
		                        		<div class="form-group">
		                        			<label class="sr-only" for="instagram">Instagram</label>
		                        			<input type="text" name="instagram" id="instagram" placeholder="Instagram..." class="form-instagram form-control redessociais no_obligatory" value="<?php echo $this->request->post('instagram') ?>" >
		                        		</div>
		                        	</div><!-- </col-md-6> -->
		                        	<div class="col-md-6">
		                        		<div class="form-group">
		                        			<label class="sr-only" for="linkedin">Linkedin</label>
		                        			<input type="text" name="linkedin" id="linkedin" placeholder="Linkedin..." class="form-linkedin form-control redessociais" value="<?php echo $this->request->post('linkedin') ?>" >
		                        		</div>
		                        	</div><!-- </col-md-6> -->
		                        </div><!-- </row> -->
		                        <!--
		                        	3º Linha Formulario  Redes Sociais
		                        -->
		                        <div class="row">
		                        	<div class="col-md-6">
		                        		<div class="form-group">
		                        			<label class="sr-only" for="github">GitHub</label>
		                        			<input type="text" id="github" name="github" placeholder="GitHub..." class="form-github form-control redessociais no_obligatory" value="<?php echo $this->request->post('github') ?>" >
		                        		</div>
		                        	</div><!-- </col-md-6> -->
		                        	<div class="col-md-6">
		                        		<div class="form-group">
		                        			<label class="sr-only" for="web">Web</label>
		                        			<input type="text" name="web" id="web" placeholder="Web..." class="form-web form-control redessociais no_obligatory" value="<?php echo $this->request->post('web') ?>" >
		                        		</div>
		                        	</div><!-- </col-md-6> -->
		                        </div><!-- </row> -->
		                        <!--
		                        	Linha de Contole Formulario Redes Sociais
		                        -->
		                        <div class="row">
		                        	<div class="col-md-12">
		                        		<div class="form-group">
		                        			<button type="button" class="btn-previous">
		                        				<i class="fa fa-arrow-left"></i>
		                        				<span>Previous</span>
		                        			</button>
		                        			<button type="button" class="btn-next" id="step04">
		                        				<i class="fa fa-arrow-right"></i>
		                        				<span>Next</span>
		                        			</button>
		                        		</div><!-- </form-group> -->
		                        		<div class="form-group">
		                        			<div class="msgbox" id="msg-step04">
						               			<span></span>
						            			</div>
						            		</div>
		                        	</div><!-- </col-md-12> -->
		                        </div><!-- </row> -->
		                     </div><!-- </form-bottom> -->
		                  </fieldset><!-- </Social media profiles> -->

								<!--
									Passo Foto Avatar Perfil
								-->
								<fieldset id="stepAvatar">
									<div class="form-top">
										<div class="form-top-left">
											<h3>Foto</h3>
											<p>Imagem Avatar de Perfil:</p>
										</div>
										<div class="form-top-right">
											<i class="fa-graduation-cap"></i>
										</div>
									</div><!-- </form-top> Header and Title Fieldset -->
									<div class="form-bottom">

										<div class="row">
											<div class="col-md-8">
												<div class="boxReumePersonal">
													<span>Dados Pessoais</span>
													<div class="row">
													  	<div class="col-md-10">
													    	<p><strong>Nome do Usuário</strong></p>
													   	<p class="resumo" id= resumeNome></p>
													  	</div>
													</div> <!-- .row -->

													<div class="row">
													  	<div class="col-md-8">
													   	<p class="resumo" id="resumeProfessional"></p>
													  	</div>
													</div> <!-- .row -->

													<div class="row">
													  	<div class="col-md-4">
													    	<p><strong>Data Nascimento</strong></p>
													    	<p class="resumo" id="resumeDataNasc"></p>
													  	</div>
													  	<div class="col-md-4">
													    	<p><strong>Telefone</strong></p>
													    	<p class="resumo" id="resumeCelular"></p>
													  	</div>
													</div> <!-- .row -->

													<div class="row">
													  	<div class="col-md-4">
													    	<p><strong>Sobre</strong></p>
															<p class="resumo" id="resumeAbout"></p>
													  	</div>
													</div> <!-- .row -->
												</div><!-- </boxReumePersonal> -->

												<div class="boxResumeAccess">
													<span>Informações de Acesso</span>
													<div class="row">
													  	<div class="col-md-6">
													    	<p><strong>Usuário</strong></p>
															<p class="resumo" id="resumeUser"></p>
													  	</div>
														<div class="col-md-6">
													    	<p><strong>e-Mail</strong></p>
															<p class="resumo" id="resumeEmail"></p>
													  	</div>
													</div> <!-- .row -->
												</div><!-- </boxResumeAccess> -->
											</div><!-- </col-md-8> -->

											<div class="col-md-4">
												<div class="row">
													<div class="col-md-12" id="wrapper">

														<div class="row">
															<div class="col-md-10 centered">
																<div id="image-holder">
																	<img src="<?php echo BASE . 'public/uploads/users/default/userdefault.png'; ?>" height="160" width="160" alt="">
																</div>
															</div>
														</div>
														<div class="row">
															<div class="col-md-12">
																<div class="box-input">
																	<input type="file" name="file-1[]" id="file-1" class="upFile upFile-1" data-multiple-caption="{count} files selected" multiple />
																	<label for="file-1"><svg xmlns="http://www.w3.org/2000/svg" width="20" height="17" viewBox="0 0 20 17"><path d="M10 0l-5.2 4.9h3.3v5.1h3.8v-5.1h3.3l-5.2-4.9zm9.3 11.5l-3.2-2.1h-2l3.4 2.6h-3.5c-.1 0-.2.1-.2.1l-.8 2.3h-6l-.8-2.2c-.1-.1-.1-.2-.2-.2h-3.6l3.4-2.6h-2l-3.2 2.1c-.4.3-.7 1-.6 1.5l.6 3.1c.1.5.7.9 1.2.9h16.3c.6 0 1.1-.4 1.3-.9l.6-3.1c.1-.5-.2-1.2-.7-1.5z"/></svg> <span>Selecionar Foto</span></label>
																</div><!-- </box-input> -->
															</div><!-- </col-md-12> -->
														</div><!-- </row> -->
													</div><!-- </col-md-12> -->
												</div><!-- </row> -->
											</div><!-- </col-md-4> -->
										</div><!-- </row> -->
										<div class="row">
											<div class="col-md-12">
												<div class="boxResumeAddress">
													<span>Endereço & Address</span>
													<div class="row">
													  	<div class="col-md-6">
													    	<p><strong>Endereço</strong></p>
															<p class="resumo" id="resumeAddress"></p>
													  	</div>
														<div class="col-md-6">
													    	<p><strong>Cidade</strong></p>
															<p class="resumo" id="resumeCity"></p>
													  	</div>
													</div> <!-- .row -->

													<div class="row">
													  	<div class="col-md-6">
													    	<p><strong>Bairro</strong></p>
															<p class="resumo" id="resumeBeighborhood"></p>
													  	</div>
														<div class="col-md-6">
													    	<p><strong>Estado</strong></p>
															<p class="resumo" id="resumeState"></p>
													  	</div>
													</div> <!-- .row -->
												</div><!-- </boxResumeAddress> -->

												<div class="boxResumeSocial">
													<span>Redes Sociais</span>
													<div class="row">
													  	<div class="col-md-6">
													    	<p><strong>Facebook</strong></p>
															<p class="resumo" id="resumeFacebook"></p>
													  	</div>
														<div class="col-md-6">
													    	<p><strong>Twitter</strong></p>
															<p class="resumo" id="resumeTwitter"></p>
													  	</div>
													</div> <!-- .row -->

													<div class="row">
													  	<div class="col-md-6">
													    	<p><strong>Instagram</strong></p>
															<p class="resumo" id="resumeInstagram"></p>
													  	</div>
														<div class="col-md-6">
													    	<p><strong>LinkedIn</strong></p>
															<p class="resumo" id="resumeLinkedIn"></p>
													  	</div>
													</div> <!-- .row -->

													<div class="row">
													  	<div class="col-md-6">
													    	<p><strong>GitHub</strong></p>
															<p class="resumo" id="resumeGitHub"></p>
													  	</div>
														<div class="col-md-6">
													    	<p><strong>Site Pessoal</strong></p>
															<p class="resumo" id="resumeWeb"></p>
													  	</div>
													</div> <!-- .row -->
												</div><!-- </boxResumeSocial> -->

												<div class="boxResumeCertification">
													<span>Certificações</span>
													<div class="row">
													  	<div class="col-md-6">
													    	<p><strong>Microsoft</strong></p>
															<p class="resumo" id="resumeMicrsoft"></p>
													  	</div>
														<div class="col-md-6">
													    	<p><strong>Linux</strong></p>
															<p class="resumo" id="resumeLinux"></p>
													  	</div>
													</div> <!-- .row -->

													<div class="row">
													  	<div class="col-md-6">
													    	<p><strong>Cisco</strong></p>
															<p class="resumo" id="resumeCisco"></p>
													  	</div>
														<div class="col-md-6">
													    	<p><strong>VmWare</strong></p>
															<p class="resumo" id="resumeVirtualizacao"></p>
													  	</div>
													</div> <!-- .row -->

													<div class="row">
													  	<div class="col-md-6">
													    	<p><strong>PMI</strong></p>
															<p class="resumo" id="resumePMI"></p>
													  	</div>
														<div class="col-md-6">
													    	<p><strong>Agile</strong></p>
															<p class="resumo" id="resumeAgile"></p>
													  	</div>
													</div> <!-- .row -->
													<div class="row">
													  	<div class="col-md-6">
													    	<p><strong>Itil</strong></p>
															<p class="resumo" id="resumeItil"></p>
													  	</div>
													</div> <!-- .row -->
												</div><!-- </boxResumeSocial> -->

											</div><!-- </col-md-12> -->
										</div><!-- </row> -->
 										<!-- </Final Containers Resume> -->

										<hr/><!-- Traço separador do Repeater -->
										<!--
											Linha de Contole Formulario Historico Profissional
										-->
										<div class="row">
											<div class="col-md-12">
												<div class="form-group">
													<button type="button" class="btn-previous">
														<i class="fa fa-arrow-left"></i>
														<span>Previous</span>
													</button>
													<button type="button" class="btn-finish">
														<i class="fa fa-user"></i>
														<span>Sign UP</span>
													</button>
												</div><!-- </form-group> -->
											</div><!-- </col-md-12> -->
										</div><!-- </row> -->
									</div><!-- </form-bottom> -->
								</fieldset><!-- </Step Foto Avatar > -->
		               </form>
		            </div><!-- </form-box> -->
		         </div><!-- </row>  -->
		      </div><!-- </container>  -->
		   </div><!-- </inner-bg> -->
		</div><!-- </top-content> -->