		<!-- Top content -->
		<div class="top-content">
			<div class="inner-bg">
				<div class="container">
					<div class="row">
						<div class="col-sm-8 col-sm-offset-2 form-box">
							<?php echo (isset($this->alert) ? $this->alert : ''); ?>
							<form action="<?php echo BASE; ?>tests/cadastrar/" method="post" id="registration-form" class="registration-form">
							<!--
	                     Passo Formulario de Histórico Acadêmico
	                  -->
	                  <fieldset>
	                  	<div class="form-top">
	                  		<div class="form-top-left">
	                  			<h3>Step 5 / 7</h3>
	                  			<p>Academic Historic:</p>
	                  		</div>
	                  		<div class="form-top-right">
	                  			<i class="fa-graduation-cap"></i>
	                  		</div>
	                  	</div>
	                  	<div class="form-bottom">
	                  		<div class="academic-repeater">
	                  			<div data-repeater-list="academic-group" class="academic">
	                  				<div data-repeater-item class="academic">
												<!--
												1º Linha Formulario Acadêmico
											-->
											<div class="row">
												<div class="col-md-6">
													<div class="form-group">
														<label class="sr-only" for="institution">Institution</label>
														<input type="text" name="institution" placeholder="Institution..." class="form-control academic" >
														<div class="help-block with-errors"></div>
													</div>
												</div><!-- </col-md-6> -->
												<div class="col-md-6">
													<div class="form-group">
														<label class="sr-only" for="local">Local</label>
														<input type="text" name="local" id="local" placeholder="Local..." class="form-control academic">
														<div class="help-block with-errors"></div>
													</div><!-- </form-group> -->
												</div><!-- </col-md-6> -->
											</div><!-- </row>-->
                               	<!--
                               		2º Linha Formulario Acadêmico
                               	-->
                               	<div class="row">
                               		<div class="col-md-6">
                               			<div class="form-group">
                               				<label class="sr-only" for="course">Course</label>
                               				<input type="text" name="course" id="course" placeholder="Course" class="form-control academic">
                               				<div class="help-block with-errors"></div>
                               			</div><!-- </form-group> -->
                               		</div><!-- </col-md-6> -->
                               		<div class="col-md-6">
                               			<div class="form-group">
                               				<label class="sr-only" for="date_out">Level</label>
                               				<select id="formation_list" name="formation_list" class="register-select academic" form="form-register" data-required>
                               					<option class="opt-placeholder" value="-1" selected="">Formation
                               					</option>
                               					<optgroup label="Nível">
                               						   <option value="PHD">PHD</option>
                               						   <option value="Doutorado">Doutorado</option>
                               						   <option value="Mestrado">Mestrado</option>
                               						   <option value="Pós Graduação">Pós Graduação</option>
                               						<option value="Graduação">Graduação</option>
                               						<option value="Técnico">Técnico</option>
                               						<option value="Ensino Médio">Ensino Médio</option>
                               					</optgroup>
                               				</select>
                               				<div class="help-block with-errors"></div>
                               			</div><!-- </form-group> -->
                               		</div><!-- </col-md-6> -->
                               	</div><!-- </row>-->
	                               	<!--
	                               		3º Linha Formulario Acadêmico
	                               	-->
	                               	<div class="row">
	                               		<!--<div class="col-md-3">
	                               			<div class="form-group">
	                               				<label class="sr-only" for="date_conclusion">Conclusion Date</label>
	                               				<input type="text" name="date_conclusion" id="date_conclusion" class="form-control academic" placeholder="00/00/0000" value="<?php echo $this->request->post('date_conclusion') ?>" >
	                               				<div class="help-block with-errors"></div>
	                               			</div>
	                               		</div>-->
													<div class="col-md-4" id="sandbox-container">
														<div class="input-group date">
															<input type="text" name="date_conclusion" id="date_conclusion" class="form-control academic" placeholder="00/00/0000" value="<?php echo $this->request->post('date_conclusion') ?>">
															<span class="input-group-addon">
																<i class="glyphicon glyphicon-th"></i>
															</span>
														</div>
													</div>	
	                               		<div class="col-md-2">
	                               			<div class="form-group">
	                               				<span data-repeater-delete class="btn btn-danger btn-sm academic">
	                               					<span class="glyphicon glyphicon-remove"></span> Delete
	                               				</span>
	                               			</div>
	                               		</div><!-- </col-md-4> -->
	                               		<div class="col-md-6">
	                               			<div class="row">
	                               				<div class="col-md-12 wrapper_radio">
	                               					<div class="form-group">
	                               						<div class="row">
	                               							<div class="col-md-6">
	                               								<input type="radio" id="radio01" name="radioAcademic" class="radio-academic academic" value="1">
	                               								<label for="radio01"><span></span>Complete</label>
	                               							</div>
	                               							<div class="col-md-6">
	                               								<input type="radio" id="radio02" name="radioAcademic" class="radio-academic academic" value="2" >
	                               								<label for="radio02"><span></span>Progress</label>
	                               							</div>
	                               						</div>
	                               						<div class="row">
	                               							<div class="col-md-12">
	                               								<input type="radio" id="radio03" name="radioAcademic" class="radio-academic academic" value="3" >
	                               								<label for="radio03"><span></span>Locked</label>
	                               							</div>
	                               						</div>
	                               					</div><!-- </div>form-group> -->
	                               				</div><!-- </col-md-12 wrapper_radio> -->
	                               			</div><!-- </row> -->
	                               		</div><!-- </col-md-6> -->
	                               	</div><!-- </row> -->
	                               	<hr/><!-- Traço separador do Repeater -->
	                               </div><!-- </data-repeater-item class="academic"> -->
	                            </div><!-- </data-repeater-list = academic-group> -->
	                         	<!--
	                        		Button Add New Historico Academico
	                        	-->
	                        	<div class="row">
	                        		<div class="col-md-4">
	                        			<div class="form-group">
	                        				<span data-repeater-create data-tooltip="Include new skills" name="add-academic" id="add-academic" class="btn btn-info btn-md academic">
	                        					<span class="glyphicon glyphicon-plus"></span> add
	                        				</span>
	                        			</div>
	                        		</div><!-- </col-md-4> -->
	                        	</div>
	                        </div><!-- </academic-repeater> -->
	                        <!--
	                        	Linha de Contole Formulario Histórico Acadêmico
	                        -->
	                        <div class="row">
	                        	<div class="col-md-12">
	                        		<div class="form-group">
	                        			<button type="button" class="btn-previous">
	                        				<i class="fa fa-arrow-left"></i>
	                        				<span>Previous</span>
	                        			</button>
	                        			<button type="button" class="btn-next">
	                        				<i class="fa fa-arrow-right"></i>
	                        				<span>Next</span>
	                        			</button>>
	                        		</div><!-- </form-group> -->
	                        	</div><!-- </col-md-12> -->
	                        </div><!-- </row> -->
	                     </div><!-- </form-bottom> -->
	                  </fieldset><!-- </Academic Historic> -->							
							<!--
	                     Passo Formulario de Cursos Livres
	                  -->
	                  <fieldset>
	                  	<div class="form-top">
	                  		<div class="form-top-left">
	                  			<h3>Step 6 / 7</h3>
	                  			<p>Free Courses:</p>
	                  		</div>
	                  		<div class="form-top-right">
	                  			<i class="fa-graduation-cap"></i>
	                  		</div>
	                  	</div>
	                  	<div class="form-bottom">
	                  		<div class="course-repeater">
	                  			<div data-repeater-list="course-group" class="course">
	                  				<div data-repeater-item class="course">
		                              <!--
		                                 1º Linha Formulario Cursos Livres
		                              -->
		                              <div class="row">
		                              	<div class="col-md-12">
		                              		<div class="form-group">
		                              			<label class="sr-only" for="title">Course Title</label>
		                              			<input type="text" name="title" id="title" placeholder="Course Title..." class="title form-control course" value="<?php echo $this->request->post('title') ?>" >
		                              			<label id="labelTitle" class="title"></label>
		                              		</div>
		                              	</div><!-- </col-md-12> -->
		                              </div><!-- </row>-->
		                              <!--
		                                 2º Linha Formulario Cursos Livres
		                              -->
		                              <div class="row">
		                              	<div class="col-md-8">
		                              		<div class="form-group">
		                              			<label class="sr-only" for="institution">Institution</label>
		                              			<input type="text" name="institution" id="institution" placeholder="Institution..." class="form-institution form-control course">
		                              			<label id="labelInstitution" class="institution"></label>
		                              		</div>
		                              	</div><!-- </col-md-8> -->
		                              	<div class="col-md-4">
		                              		<div class="form-group">
		                              			<label class="sr-only" for="date_out">Segment</label>
		                              			<select name="formation-list" class="register-select course" form="form-register">
		                              				<option class="opt-placeholder course" value="-1" selected="">Segment
		                              				</option>
		                              				<optgroup label="Area">
		                              					   <option value="Microsoft">Microsoft</option>
		                              					   <option value="Linux">Linux</option>
		                              					   <option value="Management">Management</option>
		                              					   <option value="Specializations">Specializations</option>
		                              				</optgroup>
		                              			</select>
		                              		</div><!-- </form-group> -->
		                              	</div><!-- </col-md-4> -->
		                              </div><!-- </row>-->
		                              <!--
		                                 3º Linha Formulario Cursos Livres
		                              -->
		                              <div class="row">
		                              	<div class="col-md-5">
		                              		<div class="form-group">
		                              			<label class="sr-only" for="institution">Workload</label>
		                              			<input type="text" name="workload" id="workload" placeholder="Workload (ex: 18h)" class="form-workload form-control course" >
		                              			<label id="labelworkload" class="workload"></label>
		                              		</div>
		                              	</div>
		                              	<!--<div class="col-md-4">
		                              		<div class="form-group">
		                              			<label class="sr-only" for="schedule">Schedule</label>
		                              			<input type="text" name="schedule" id="schedule" placeholder="00/00/0000" class="form-control schedule course" value="<?php echo $this->request->post('schedule') ?>" >
		                              			<label id="labelSchedule" class="schedule"></label>
		                              		</div>
		                              	</div>-->
													<div class="col-md-4" id="sandbox-container">
														<div class="input-group date">
															<input type="text" name="schedule" id="schedule" class="form-control course schedule" placeholder="Admission" value="<?php echo $this->request->post('schedule') ?>">
															<span class="input-group-addon">
																<i class="glyphicon glyphicon-th"></i>
															</span>
														</div>
													</div>		                              	
		                              	<div class="col-md-3 col-md-offset-0">
		                              		<div class="form-group">
		                              			<span data-repeater-delete class="btn btn-danger btn-sm course">
		                              				<span class="glyphicon glyphicon-remove"></span> Delete
		                              			</span>
		                              		</div>
		                              	</div><!-- </col-md-4> -->
		                              </div><!-- </row> -->
		                           </div><!-- </data-repeater-item class="course"> -->
		                           <hr/>
		                        </div><!-- </data-repeater-list = course-group> -->
		                        <div class="row">
		                        	<div class="col-md-4">
		                        		<div class="form-group">
		                        			<span data-repeater-create data-tooltip="Include new skills" class="btn btn-info btn-md course">
		                        				<span class="glyphicon glyphicon-plus"></span> add
		                        			</span>
		                        		</div>
		                        	</div><!-- </col-md-4> -->
		                        </div><!-- </row> -->
		                     </div><!-- </course-repeater> -->
	                        <!--
	                        	Linha de Contole Formulario Cursos Livres
	                        -->
	                        <div class="row">
	                        	<div class="col-md-12">
	                        		<div class="form-group">
	                        			<button type="button" class="btn-previous">
	                        				<i class="fa fa-arrow-left"></i>
	                        				<span>Previous</span>
	                        			</button>
	                        			<button type="button" class="btn-next">
	                        				<i class="fa fa-arrow-right"></i>
	                        				<span>Next</span>
	                        			</button>
	                        		</div><!-- </form-group> -->
	                        	</div><!-- </col-md-12> -->
	                        </div><!-- </row> -->
	                     </div><!-- </form-bottom> -->
	                  </fieldset><!-- </Free Courses> -->								
							<!--
	                     Passo Formulario Histórico Profissional
	                  -->
	                  <fieldset>
	                  	<div class="form-top">
	                  		<div class="form-top-left">
	                  			<h3>Step 7 / 7</h3>
	                  			<p>Professional History:</p>
	                  		</div>
	                  		<div class="form-top-right">
	                  			<i class="fa fa-th-list"></i>
	                  		</div>
	                  	</div>
	                  	<div class="form-bottom">
	                  		<div class="professional-repeater">
	                  			<div data-repeater-list="professional-group" class="professional">
	                  				<div data-repeater-item class="professional">
		                              <!--
		                              	1º Linha Formulario Histórico Profissional
		                              -->
		                              <div class="row">
		                              	<div class="col-md-6">
		                              		<div class="form-group">
		                              			<label class="sr-only" for="company">Company</label>
		                              			<input type="text" name="company" placeholder="Company..." class="form-company form-control professional" id="company">
		                              		</div>
		                              	</div><!-- </col-md-6> -->
		                              	<div class="col-md-6">
		                              		<div class="form-group">
		                              			<label class="sr-only" for="function">Function</label>
		                              			<input type="text" name="function" id="function" placeholder="Function..." class="form-function form-control professional" >
		                              		</div><!-- </form-group> -->
		                              	</div><!-- </col-md-6> -->
		                              </div><!-- </row>-->
		                              <!--
		                              	2º Linha Formulario Histórico Profissional
		                              -->
		                              <div class="row">
		                              	<!--<div class="col-md-4">
		                              		<div class="form-group">
		                              			<label class="sr-only" for="date_entry">Admission</label>
		                              			<input type="text" name="date_entry" id="date_entry" placeholder="Admission..." class="form-admission form-control professional" >
		                              		</div>
		                              	</div>
		                              	<div class="col-md-4">
		                              		<div class="form-group">
		                              			<label class="sr-only" for="date_out">Out Put</label>
		                              			<input type="text" name="date_out" id="date_out" placeholder="Out Put..." class="form-output form-control professional">
		                              		</div>
		                              	</div>-->
													<div class="col-md-4" id="sandbox-container">
														<div class="input-group date">
															<input type="text" name="date_entry" id="date_entry" class="form-control professional date_entry" placeholder="Admission" value="<?php echo $this->request->post('date_entry') ?>">
															<span class="input-group-addon">
																<i class="glyphicon glyphicon-th"></i>
															</span>
														</div>
													</div>
													<div class="col-md-4" id="sandbox-container">
														<div class="input-group date">
															<input type="text" name="date_out" id="date_out" class="form-control professional date_out" placeholder="Out Put" value="<?php echo $this->request->post('date_out') ?>">
															<span class="input-group-addon">
																<i class="glyphicon glyphicon-th"></i>
															</span>
														</div>
													</div>
													<div class="col-md-4">
		                        				<div class="form-group">
		                        					<span data-repeater-delete class="btn btn-danger btn-sm professional">
		                        						<span class="glyphicon glyphicon-remove"></span> Delete
		                        					</span>
		                        				</div>	
			                        		</div><!-- </col-md-4> -->
		                              </div><!-- </row>-->
		                              <!--
		                              	3º Linha Formulario Histórico Profissional
		                              -->
		                              <div class="row">
		                              	<div class="col-md-12">
		                              		<div class="form-group">
		                              			<label class="sr-only" for="assignments">About yourself</label>
		                              			<textarea name="assignments" id="assignments" placeholder="About yourself..." class="form-about-yourself form-control professional" ></textarea>
		                              		</div><!-- </form-group> -->
		                              	</div><!-- </col-md-12> -->
		                              </div><!-- </row> -->
				                     </div><!-- </data-repeater-item ="professional"> -->
				                     <hr/>
				                  </div><!-- </data-repeater-list="professional-group"> -->
				                  <div class="row">
				                  	<div class="col-md-4">
				                  		<div class="form-group">
				                  			<span data-repeater-create data-tooltip="Include new skills" class="btn btn-info btn-md">
				                  				<span class="glyphicon glyphicon-plus"></span> add
				                  			</span>
				                  		</div>
				                  	</div><!-- </col-md-4> -->
				                  </div><!-- </row> -->
				               </div><!-- </professional-repeater> -->
	                        <!--
	                        	Linha de Contole Formulario Historico Profissional
	                        -->
	                        <div class="row">
	                        	<div class="col-md-12">
	                        		<div class="form-group">
	                        			<button type="button" class="btn-previous">
	                        				<i class="fa fa-arrow-left"></i>
	                        				<span>Previous</span>
	                        			</button>
	                        			<button type="submit" value="Submit" class="disabled">
	                        				<i class="fa fa-user"></i>
	                        				<span>Sign UP</span>
	                        			</button>
	                        		</div><!-- </form-group> -->
	                        	</div><!-- </col-md-12> -->
	                        </div><!-- </row> -->
	                     </div><!-- </form-bottom> -->
	                  </fieldset>
		               </form>
		            </div><!-- </form-box> -->
		         </div><!-- </row>  -->
		      </div><!-- </container>  -->
		   </div><!-- </inner-bg> -->
		</div><!-- </top-content> -->