<!-- Top content -->
      <div class="top-content">
         <div class="inner-bg">
            <div class="container">
               <div class="row">
                  <div class="col-sm-8 col-sm-offset-2 form-box">
                     <?php echo (isset($this->alert) ? $this->alert : ''); ?>
                     <form action="<?php echo BASE; ?>tests/cadastrar/" role="form" data-toggle="validator" method="post" class="registration-form">                       
                        <fieldset>
                           <div class="form-top">
                              <div class="form-top-left">
                                 <h3>Step 5 / 7</h3>
                                 <p>Academic Historic:</p>
                              </div>
                              <div class="form-top-right">
                                 <i class="fa-graduation-cap"></i>
                              </div>
                           </div>
                           <div class="form-bottom">
                              <div class="repeater-custom-show-hide">
                                 <div data-repeater-list="academic">              
                                    <div data-repeater-item name="repeater-academic" id="repeater-academic">
                                       <div class="row">
                                          <div class="col-md-6">
                                             <div class="form-group">
                                                <label class="sr-only" for="institution">Institution</label>
                                                <input type="text" name="institution" placeholder="Institution..." class="form-institution form-control" id="institution">
                                             </div>
                                          </div><!-- </col-md-6> -->
                                          <div class="col-md-6">
                                             <div class="form-group">
                                                <label class="sr-only" for="local">Local</label>
                                                <input type="text" name="local" placeholder="Local..." class="form-local form-control" id="local">
                                             </div><!-- </form-group> -->                    
                                          </div><!-- </col-md-6> -->
                                       </div><!-- </row>-->
                                       <div class="row">
                                          <div class="col-md-6">
                                             <div class="form-group">
                                                <label class="sr-only" for="course">Course</label>
                                                <input type="text" name="course" placeholder="Course" class="form-acourse form-control" id="course">
                                             </div><!-- </form-group> -->
                                          </div><!-- </col-md-6> -->
                                          <div class="col-md-6">
                                             <div class="form-group">
                                                <label class="sr-only" for="date_out">Level</label>
                                                <select name="formation-list" class="register-select" form="form-academic">
                                                   <option class="opt-placeholder" value="-1" selected="">Formation
                                                   </option>
                                                   <optgroup label="Nível">
                                                   <option value="PHD">PHD</option>
                                                   <option value="Doutorado">Doutorado</option>
                                                   <option value="Mestrado">Mestrado</option>
                                                   <option value="Pós Graduação">Pós Graduação</option>
                                                   <option value="Graduação">Graduação</option>
                                                   <option value="Técnico">Técnico</option>
                                                   <option value="Ensino Médio">Ensino Médio</option>
                                                   </optgroup>
                                                </select> 
                                             </div><!-- </form-group> -->                     
                                          </div><!-- </col-md-6> -->                           
                                       </div><!-- </row>-->
                                       <div class="row">
                                          <div class="col-md-4">
                                             <div class="form-group">
                                                <label class="sr-only" for="date_conclusion">Conclusion Date</label>
                                                <input type="text" name="conclusion_date" id="conclusion_date" placeholder="00/00/0000" class="form-conclusion_date form-control" value="<?php echo $this->request->post('conclusion_date') ?>" required>
                                             </div><!-- </form-group> -->
                                          </div>
                                          <div class="col-md-4 col-md-offset-4">
                                             <div class="form-group">
                                                <span data-repeater-delete class="btn btn-danger btn-sm">
                                                   <span class="glyphicon glyphicon-remove"></span> Delete
                                                </span>
                                             </div>                      
                                          </div><!-- </col-md-4> -->
                                       </div><!-- </row> -->
                        
                                       <div class="row">
                                          <div class="col-md-12 wrapper_radio">
                                             <div class="row">
                                                <div class="col-md-2 col-md-offset-3">
                                                   <input type="radio" id="radio01" name="radio" checked="checked" value="1" />
                                                   <label for="radio01"><span></span>Complete</label>
                                                </div>
                                                <div class="col-md-2">
                                                   <input type="radio" id="radio02" name="radio" value="2" />
                                                   <label for="radio02"><span></span>Progress</label>
                                                </div>
                                                <div class="col-md-2">
                                                   <input type="radio" id="radio03" name="radio" value="3" />
                                                   <label for="radio03"><span></span>Locked</label>
                                                </div>                                              
                                             </div>
                                          </div>
                                       </div>
                                    </div><!-- </data-repeater-item> -->
                                    <hr/>
                                 </div><!-- </data-repeater-list> -->
                                 <div class="row">
                                    <div class="col-md-4">
                                       <div class="form-group">
                                          <span data-repeater-create data-tooltip="Include new skills" name="add-academic" id="add-academic" class="btn btn-info btn-md">
                                             <span class="glyphicon glyphicon-plus"></span> add
                                          </span>
                                       </div>                      
                                    </div><!-- </col-md-4> -->  
                                 </div>      
                              </div><!-- </repeater-custom-show-hide> -->

                              <div class="row">
                                 <div class="col-md-12">
                                    <div class="form-group">
                                       <button type="button" class="btn-previous">
                                          <i class="fa fa-arrow-left"></i>
                                          <span>Previous</span>
                                       </button>
                                       <button type="button" class="btn-next">
                                          <i class="fa fa-arrow-right"></i>
                                          <span>Next</span>
                                       </button>
                                    </div><!-- </form-group> -->                     
                                 </div><!-- </col-md-12> -->
                              </div><!-- </row> -->
                           </div><!-- </form-bottom> -->
                        </fieldset><!-- </Academic Historic> -->

                       <fieldset>
                           <div class="form-top">
                              <div class="form-top-left">
                                 <h3>Step 6 / 7</h3>
                                 <p>Free Courses:</p>
                              </div>
                              <div class="form-top-right">
                                 <i class="fa-graduation-cap"></i>
                              </div>
                           </div>
                           <div class="form-bottom">
                              <div class="repeater-custom-show-hide">
                                 <div data-repeater-list="courses">                                 
                                    <div data-repeater-item name="repeater-courses" id="repeater-courses">
                                       <div class="row">
                                          <div class="col-md-12">
                                             <div class="form-group">
                                                <label class="sr-only" for="institution">Course Title</label>
                                                <input type="text" name="title" placeholder="Course Title..." class="form-title form-control" id="title">
                                             </div>
                                          </div><!-- </col-md-12> -->
                                       </div><!-- </row>-->
                                       <div class="row">
                                          <div class="col-md-8">
                                             <div class="form-group">
                                                <label class="sr-only" for="institution">Institution</label>
                                                <input type="text" name="institution" placeholder="Institution..." class="form-institution form-control" id="institution">
                                             </div>
                                          </div><!-- </col-md-8> -->
                                           <div class="col-md-4">
                                             <div class="form-group">
                                                <label class="sr-only" for="date_out">Segment</label>
                                                <select name="formation-list" class="register-select" form="form-academic">
                                                   <option class="opt-placeholder" value="-1" selected="">Segment
                                                   </option>
                                                   <optgroup label="Area">
                                                   <option value="Microsoft">Microsoft</option>
                                                   <option value="Linux">Linux</option>
                                                   <option value="Management">Management</option>
                                                   <option value="Specializations">Specializations</option>                                          
                                                   </optgroup>
                                                </select> 
                                             </div><!-- </form-group> -->                     
                                          </div><!-- </col-md-4> -->
                                       </div><!-- </row>-->
                                       <div class="row">
                                          <div class="col-md-5">
                                             <div class="form-group">
                                                <label class="sr-only" for="institution">Workload</label>
                                                <input type="text" name="workload" placeholder="Workload..." class="form-workload form-control" id="workload">
                                             </div>
                                          </div>
                                          <div class="col-md-4">
                                             <div class="form-group">
                                                <label class="sr-only" for="date_conclusion">Conclusion Date</label>
                                                <input type="text" name="conclusion_date" id="conclusion_date" placeholder="00/00/0000" class="form-conclusion_date form-control" value="<?php echo $this->request->post('conclusion_date') ?>" required>
                                             </div><!-- </form-group> -->
                                          </div>
                                          <div class="col-md-3 col-md-offset-0">
                                             <div class="form-group">
                                                <span data-repeater-delete class="btn btn-danger btn-sm">
                                                   <span class="glyphicon glyphicon-remove"></span> Delete
                                                </span>
                                             </div>                      
                                          </div><!-- </col-md-4> -->
                                       </div><!-- </row> -->
                                    </div><!-- </data-repeater-item> -->
                                    <hr/>
                                 </div><!-- </data-repeater-list> -->
                                 <div class="row">
                                    <div class="col-md-4">
                                       <div class="form-group">
                                          <span data-repeater-create data-tooltip="Include new skills" name="add-course" id="add-course" class="btn btn-info btn-md">
                                             <span class="glyphicon glyphicon-plus"></span> add
                                          </span>
                                       </div>                      
                                    </div><!-- </col-md-4> -->  
                                 </div>      
                              </div><!-- </repeater-custom-show-hide> -->
                              <div class="row">
                                 <div class="col-md-12">
                                    <div class="form-group">
                                       <button type="button" class="btn-previous">
                                          <i class="fa fa-arrow-left"></i>
                                          <span>Previous</span>
                                       </button>
                                       <button type="button" class="btn-next">
                                          <i class="fa fa-arrow-right"></i>
                                          <span>Next</span>
                                       </button>
                                    </div><!-- </form-group> -->                     
                                 </div><!-- </col-md-12> -->
                              </div><!-- </row> -->
                           </div><!-- </form-bottom> -->
                        </fieldset><!-- </Free Courses> -->
                        <fieldset>
                           <div class="form-top">
                              <div class="form-top-left">
                                 <h3>Step 6 / 7</h3>
                                 <p>Professional History:</p>
                              </div>
                              <div class="form-top-right">
                                 <i class="fa fa-th-list"></i>
                              </div>
                           </div>
                           <div class="form-bottom">
                              <div class="repeater-custom-show-hide">
                                 <div data-repeater-list="historic">                     
                                    <div data-repeater-item name="repeater-historic" id="repeater-historic">
                                       <div class="row">
                                          <div class="col-md-6">
                                             <div class="form-group">
                                                <label class="sr-only" for="company">Company</label>
                                                <input type="text" name="company" placeholder="Company..." class="form-company form-control" id="company">
                                             </div>
                                          </div><!-- </col-md-6> -->
                                          <div class="col-md-6">
                                             <div class="form-group">
                                                <label class="sr-only" for="function">Function</label>
                                                <input type="text" name="function" placeholder="Function..." class="form-function form-control" id="function">
                                             </div><!-- </form-group> -->                    
                                          </div><!-- </col-md-6> -->
                                       </div><!-- </row>-->
                                       <div class="row">
                                          <div class="col-md-4">
                                             <div class="form-group">
                                                <label class="sr-only" for="date_entry">Admission</label>
                                                <input type="text" name="date_entry" placeholder="Admission..." class="form-admission form-control" id="date_entry">
                                             </div><!-- </form-group> -->
                                          </div><!-- </col-md-4> -->
                                          <div class="col-md-4">
                                             <div class="form-group">
                                                <label class="sr-only" for="date_out">Out Put</label>
                                                <input type="text" name="date_out" id="date_out" placeholder="Out Put..." class="form-output form-control">
                                             </div><!-- </form-group> -->                     
                                          </div><!-- </col-md-4> -->                           
                                       </div><!-- </row>-->
                                       <div class="row">
                                          <div class="col-md-12">
                                             <div class="form-group">
                                                <label class="sr-only" for="assignments">About yourself</label>
                                                <textarea name="assignments" id="assignments" placeholder="About yourself..." class="form-about-yourself form-control" ></textarea>
                                             </div><!-- </form-group> -->
                                          </div><!-- </col-md-12> -->
                                       </div><!-- </row> -->
                                       <div class="row">
                                          <div class="col-md-12">
                                             <div class="row">
                                                <div class="col-md-4 col-md-offset-4">
                                                   <div class="form-group">
                                                      <span data-repeater-delete class="btn btn-danger btn-sm">
                                                         <span class="glyphicon glyphicon-remove"></span> Delete
                                                      </span>
                                                   </div>                      
                                                </div><!-- </col-md-4> -->                      
                                             </div><!-- </row>-->
                                          </div><!-- </col-md-12> -->
                                       </div>
                                    </div><!-- </data-repeater-item> -->
                                    <hr/>
                                 </div><!-- </data-repeater-list> -->
                                 <div class="row">
                                    <div class="col-md-4">
                                       <div class="form-group">
                                          <span data-repeater-create data-tooltip="Include new skills" name="add-historic" id="add-historic" class="btn btn-info btn-md">
                                             <span class="glyphicon glyphicon-plus"></span> add
                                          </span>
                                       </div>                      
                                    </div><!-- </col-md-4> --> 
                                 </div>
                              </div><!-- </repeater-custom-show-hide> -->
                              <div class="row">
                                 <div class="col-md-12">
                                    <div class="form-group">
                                       <button type="button" class="btn-previous">
                                          <i class="fa fa-arrow-left"></i>
                                          <span>Previous</span>
                                       </button>
                                       <button type="submit" value="Submit" class="disabled">   
                                          <i class="fa fa-user"></i>
                                          <span>Sign UP</span>
                                       </button>   
                                    </div><!-- </form-group> -->                     
                                 </div><!-- </col-md-12> -->
                              </div><!-- </row> -->
                           </div><!-- </form-bottom> -->
                        </fieldset>   
                     </form><!-- </registration-form> -->
                  </div><!-- </form-box> -->
               </div><!-- </row>  -->
            </div><!-- </container>  -->
         </div><!-- </inner-bg> -->
      </div><!-- </top-content> -->