		<!-- Top content -->
		<div class="top-content">
			<div class="inner-bg">
				<div class="container">
					<div class="row">
						<div class="col-sm-8 col-sm-offset-2 form-box">
							<?php echo (isset($this->alert) ? $this->alert : ''); ?>
							<form action="<?php echo BASE; ?>temp/academic/" method="post" id="registration-form" class="registration-form">
								<!--
								   Passo Formulario Dados Pessoais
								-->
								<fieldset id="stepPersonal">
									<div class="form-top">
										<div class="form-top-left">
											<h3>Passo 1 / 8</h3>
											<p>Dados Pessoais:</p>
										</div>
										<div class="form-top-right">
											<i class="fa fa-user"></i>
										</div>
									</div><!-- </form-top> -->
									<div class="form-bottom">
	                           <!--
	                           	1º Linha Formulario Dados Pessoais
	                           -->
	                           <div class="row">
	                           	<div class="col-md-4">
	                           		<div class="form-group">
	                           			<!--<label class="sr-only" for="name">Nome</label>-->
	                           			<input type="text" name="name" id="name" placeholder="Nome" class="form-control academic" value="<?php echo $this->request->post('name') ?>" >
	                           		</div><!-- </form-group> -->
	                           	</div><!-- </col-md-4> -->
	                           	<div class="col-md-8">
	                           		<div class="form-group">
	                           			<label class="sr-only" for="form_last_name">Sobrenome</label>
	                           			<input type="text" name="last_name" id="last_name" placeholder="Sobrenome" class="form-control academic">
	                           		</div><!-- </form-group> -->
	                           	</div><!-- </col-md-8> -->
	                           </div><!-- </row> -->

										<!--
											3º Linha Formulario Acadêmico
										-->
										<div class="row wraper_conclusion centered" id="wraper_conclusion">
											<div class="col-md-6" id="boxDataConclusion" >
												<div class="dataContainer" id="dataContainer">
													<label for="birth_date" class="sr-only">Data Aniversário:</label>
													<div class="input-group date">
														<input type="text" class="inputData" name="birth_date" id="birth_date" Placeholder="Aniversário" value="<?php echo $this->request->post('date_conclusion') ?>">
														<span class="input-group-addon">
															<i class="glyphicon glyphicon-th"></i>
														</span>
													</div><!-- </input-group date> -->
													
													<div class="msgFront1" name="msgFront">
														<span class="mensagem" name="mensagem"></span>
													</div>

												</div><!-- </col-md-6 centered> -->
											</div><!-- </boxDataConclusion>-->
											<div class="col-md-6">
												<div class="form-group">
													<label class="sr-only" for="celular">Celular</label>
													<input type="text" class="form-control academic" name="celular" id="celular" placeholder="(00) 90000-0000" value="<?php echo $this->request->post('celular') ?>" >
													<div class="help-block with-errors"></div>
												</div><!-- </form-group> -->
											</div><!-- </col-md-6> -->
										</div><!-- </row> -->
	                           <!--
	                           	3º Linha Formulario Dados Pessoais
	                           -->
										<div class="row">
											<div class="form-group">
												<div class="col-md-8 centered boxRadio" id="boxAniver">
													<div class="row">
														<div class="col-md-6">
															<div class="form-group">
																<input type="radio" name="scope" id="scope01" class="radio-academic" value="1">
																<span>Microsoft</span>
															</div><!-- </form-group> -->
														</div><!-- </col-md-6> -->
														<div class="col-md-6">
															<div class="form-group">
																<input type="radio" name="scope" id="scope01" class="radio-academic" value="2">
																<span>Linux</span>
															</div><!-- </form-group> -->
														</div><!-- </col-md-6> -->
													</div>
												</div><!-- </boxRadio> -->
											</div><!-- </form-group> -->									
										</div><!-- </row> Final 3º Linha -->
		                        <!--
		                        	4º Linha Formulario Dados Pessoais
		                        -->
		                        <div class="row">
		                        	<div class="col-md-12">
		                        		<div class="form-group">
		                        			<label class="sr-only" for="form-about-yourself">Resumo Sobre Mim</label>
		                        			<textarea name="about" id="about" placeholder="Resumo Sobre Mim..." class="form-about-yourself form-control"></textarea>
		                        		</div><!-- </form-group> -->
		                        	</div><!-- </col-md-12> -->
		                        </div><!-- </row> 4º Linha -->
		                        <!--
		                        	Linha de Contole Formulario Dados Pessoais
		                        -->
		                        <div class="row">
		                        	<div class="col-md-12">
		                        		<div class="form-group">
		                        			<button type="button" class="btn-next" id="step01" value="Validate!">
		                        				<i class="fa fa-arrow-right"></i>
		                        				<span>Próximo</span>
		                        			</button>
		                        		</div><!-- </form-group> -->
		                        		<div class="form-group">
		                        			<div class="msgbox" id="msg-step01">
						               			<span></span>
						            			</div>
						            		</div>	
		                        	</div><!-- </col-md-12> -->
		                        </div><!-- </row> -->
	                     	</div><!-- </form-bottom> -->
	                  	</fieldset>
								<!--
		                     Passo Formulario de Informações de Acesso
		                  -->
		                  <fieldset id="stepAccess">
		                  	<div class="form-top">
		                  		<div class="form-top-left">
		                  			<h3>Passo 2 / 8</h3>
		                  			<p>Acesssos e Senha:</p>
		                  		</div>
		                  		<div class="form-top-right">
		                  			<i class="fa fa-key"></i>
		                  		</div>
		                  	</div>
		                  	<div class="form-bottom">
		                        <!--
		                        	1º Linha Formulario  de Informações de Acesso
		                        -->
		                        <div class="row">
		                        	<div class="col-md-6">
		                        		<div class="form-group">
		                        			<label class="sr-only" for="username">Usuario</label>
		                        			<input type="text" name="username" id="username" placeholder="Nome Usuario" class="form-control academic" value="<?php echo $this->request->post('username') ?>">
		                        			<div class="help-block with-errors"></div>
		                        		</div>
		                        	</div>
		                        	<div class="col-md-6">
		                        		<div class="form-group">
		                        			<label class="sr-only" for="form-email">Email</label>
		                        			<input type="email" class="form-control academic" name="email" id="email" placeholder="Email" value="<?php echo $this->request->post('email') ?>" >
		                        			<div class="help-block with-errors"></div>
		                        		</div>
		                        	</div>
		                        </div>
		                        <!--
		                        	2º Linha Formulario  de Informações de Acesso
		                        -->
		                        <div class="row">
		                        	<div class="col-md-12">
		                        		<div class="form-group">
		                        			<label class="sr-only" for="form-senha">Senha</label>
		                        			<input type="password" class="form-control academic" name="password" id="password" placeholder="Senha">
		                        		</div><!-- </form-group> -->
		                        	</div><!-- </col-md-12> -->
		                        </div><!-- </row> -->
		                        <!--
		                        	3º Linha Formulario  de Informações de Acesso
		                        -->
		                        <div class="row">
		                        	<div class="col-md-12">
		                        		<div class="form-group">
		                        			<label class="sr-only" for="form-confirmPassword">Confirmar Senha</label>
		                        			<input type="password" class="form-control academic" id="confirmPassword" name="confirmPassword" placeholder="Confirmar Senha" >
		                        			<div class="help-block with-errors"></div>
		                        		</div><!-- </form-group> -->
		                        	</div><!-- </col-md-12> -->
		                        </div><!-- </row> -->
		                        <!--
		                        	Linha de Contole Formulario Dados Pessoais
		                        -->
		                        <div class="row">
		                        	<div class="col-md-12">
		                        		<div class="form-group">
		                        			<button type="button" class="btn-previous">
		                        				<i class="fa fa-arrow-left"></i>
		                        				<span>Anterior</span>
		                        			</button>	                        			
		                        			<button type="button" class="btn-next" id="step02" value="Validate!">
		                        				<i class="fa fa-arrow-right"></i>
		                        				<span>Próximo</span>
		                        			</button>
		                        		</div><!-- </form-group> -->
		                        		<div class="form-group">
		                        			<div class="msgbox" id="msg-step02">
						               			<span></span>
						            			</div>
						            		</div>	
		                        	</div><!-- </col-md-12> -->
		                        </div><!-- </row> -->
		                     </div><!-- </form-bottom> -->
		                  </fieldset><!-- </Access & Password> -->
								<!--
		                     Passo Formulario Certificações Oficiais
		                  -->
		                  <fieldset id="stepCertification">
		                  	<div class="form-top">
		                  		<div class="form-top-left">
		                  			<h3>Resumo</h3>
		                  			<p>Verifique Informações:</p>
		                  		</div>
		                  		<div class="form-top-right">
		                  			<i class="fa-graduation-cap"></i>
		                  		</div>
		                  	</div><!-- </form-top> Header and Title Fieldset -->
									<div class="form-bottom">
										<!--
                            		1º Linha Formulario Acadêmico
                            	-->
                            	<div class="row">
                            		<div class="col-md-6 select_input" >
                            			<div class="form-group">
   											   <label for="microsoft" class="sr-only" >Certification Microsoft:</label>
   								          	<select name="microsoft" id="microsoft" class="form-control register-select certification"/>
                            					<option class="opt-placeholder" value="-1" selected="">Microsoft
                            					</option>
                            					<optgroup label="Nível">
                         							<option value="Nao">Não Possui</option>
                         						   <option value="MCSE">MCSE</option>
                         						   <option value="MCSA">MCSA</option>
                         						   <option value="MCTS">MCTS</option>
                         						   <option value="MCP">MCP</option>
                            					</optgroup>
                               			</select>
                            				<div class="help-block with-errors"></div>
                                       <div class="msgFront" name="msgFront">
                                          <span></span>
                                       </div>                                         
                            			</div><!-- </form-group> -->
                            		</div><!-- </col-md-6> -->
                            	</div><!-- </row>-->
										
                            	<hr/><!-- Traço separador do Repeater -->
			                     <!--
			                     	Linha de Contole Formulario Historico Profissional
			                     -->
			                     <div class="row">
			                     	<div class="col-md-12">
			                     		<div class="form-group">
			                     			<button type="button" class="btn-previous">
			                     				<i class="fa fa-arrow-left"></i>
			                     				<span>Previous</span>
			                     			</button>
			                     			<button type="button" class="btn-finish">
			                     				<i class="fa fa-user"></i>
			                     				<span>Sign UP</span>
			                     			</button>
			                     		</div><!-- </form-group> -->
			                     	</div><!-- </col-md-12> -->
			                     </div><!-- </row> -->
		                     </div><!-- </form-bottom> -->
								</fieldset><!-- </Step Certificaões > -->

		               </form>
		            </div><!-- </form-box> -->
		         </div><!-- </row>  -->
		      </div><!-- </container>  -->
		   </div><!-- </inner-bg> -->
		</div><!-- </top-content> -->