			<!-- ==============================================
			Footer (Rodapé)
			=============================================== -->
			<footer>
				<section class="social-links">
				  	<div class="container">
				   	<div class="row">
				         <ul>
				            <li>
				            	<a href="https://www.facebook.com/profile.php?id=1800765934" target="_blank" title="">
				            		<span> <i class="fa fa-facebook"></i> </span>
				            	</a>
				            </li><!-- Icone Facebook -->
				            <li>
				            	<a href="https://twitter.com/elisandromello" target="_blank" title="">
				            		<span> <i class="fa fa-twitter"></i> </span>
				            	</a>
				            </li><!-- Icone Twitter -->
				            <li>
				            	<a href="http://www.linkedin.com/in/elisandromello" target="_blank" title="">
				            		<span> <i class="fa fa-linkedin"></i> </span>
				            	</a>
				            </li><!-- Icone LinkedIn -->
				            <li>
				            	<a href="http://www.instagram.com/iamelisandromello" target="_blank" title="">
				            		<span> <i class="fa fa-instagram"></i> </span>
				            	</a>
				            </li><!-- Icone Instagram -->
				            <li>
				            	<a href="https://github.com/iamelisandromello" target="_blank" title="">
				            		<span> <i class="fa fa-github"></i> </span>
				            	</a>
				            </li><!-- Icone GitHub -->
				            <li>
				            	<a href="mailto:iam@elisandromello.com.br?subject=Eu tenho um comentário para você..." title="">
				            		<span> <i class="fa fa-envelope"></i></span>
				            	</a>
				            </li><!-- Icone e-mail -->
				         </ul><!-- Lista de elementos Redes SOciais -->
				    	</div><!-- /row -->
				  	</div><!-- /container -->    
				</section><!-- </social-links> Final Sessão Redes Sociais -->

				<!-- ==============================================
				   Créditos (Credits)
				=============================================== --> 
				<section class="copyright">
				  	<div class="container">
				   	<div class="col-md-12">
				      	<div class="text-center"> 
				        	<!-- Logo Header -->
				        		<section id="fox_footer" class="fox_footer">
				          		<div>
				          			<img src="<?php echo IMAGES; ?>logofooter.png" alt="Foxin by Elisandro Mello"> - &copy;<script>document.write(new Date().getFullYear())</script> - Designer coded and designed by <i class="fa fa-cloud-upload"></i> Elisandro Mello
				          		</div><!-- Informações de Rodapé -->
				        		</section><!-- </fox_footer> Final Sesão Info's Desenvolvedor-->
				        	<!--/ Logo Header-->
				      	</div><!-- </text-center> -->
				    	</div><!-- <qcol-md-12> -->
				  	</div><!-- </container> -->
				</section><!-- </copyright> -->				
			</footer><!-- Final Área de Rodapé -->
			<!-- Back To Top -->
			<a id="back-to-top" href="#">
				<i class="font-icon-arrow-simple-up"></i>
			</a>
			<!-- End Back to Top -->

			<!-- ==============================================
			    Modal Contato (Contact)
			=============================================== -->
			<div class="modal fade" id="modal1" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
			    <div class="modal-dialog">
			    	<div class="modal-content modal-popup">
			        	<div class="modal-header">
		            	<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
		                <h2 class="modal-title">Contact-Me</h2>
			        	</div><!-- </modal-header> -->

			        	<div class="row">
				        	<div class="col-sm-3">
								<div class="modal-containerAvatar">
									<div class="container-avatarcontactme">
										<div class="avatar-molde">
											<img class="avatar-picture wow bounceIn" src="<?php echo IMAGES; ?>profiles/10.jpg" >
										</div><!-- </avatar-molde> -->
										<i class="fa fa-share"></i>
										<div class="avatar-molde">
											<img class="avatar-picture wow bounceIn" src="<?php echo IMAGES; ?>profiles/6.jpg" >
										</div><!-- </avatar-molde> -->
									</div><!-- </container-avatarcontactme> -->
								</div><!-- </modal-containerAvatar> -->
							</div><!-- </col-sm-3> Colunas Avatares-->
			        	</div><!-- </row> -->

    					<div class="row">
							<div class="col-md-10 centered">
								<div class="modal-containerStep">
									<span class="step-num">1</span>
									<div class="modal-text">
										Write your message
									</div><!-- </modal-text> -->
								</div><!-- </moldal-containerStep> -->
							</div><!-- </col-md-10> -->
						</div><!-- </row>  -->

		            <form action="#" method="post">
							<div class="modal-groupForm">
								<textarea class="textarea-modal" rows="5" placeholder="Leave your message to the user"></textarea>	
							</div>
		                <input name="submit" type="submit" class="form-control" id="submit" value="Send Message">
		            </form>
			      </div><!-- </modal-content> -->
			   </div><!-- </modal-dialog> -->
			</div><!-- </modal fade> -->

			<!-- ==============================================
			Modal Recommendation (add Recomendação)
			=============================================== -->
			<div class="modal fade" id="modal2" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
			   <div class="modal-dialog">
			    	<div class="modal-content modal-popup">
			        	<div class="modal-header">
		            	<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
		                <h2 class="modal-title">Recommendation</h2>
			        	</div><!-- </modal-header> -->

			        	<div class="row">
				        	<div class="col-sm-3">
								<div class="modal-containerAvatar">
									<div class="container-avatarcontactme">
										<div class="avatar-molde">
											<img class="avatar-picture wow bounceIn" src="<?php echo IMAGES; ?>/profiles/10.jpg" >
										</div><!-- </avatar-molde> -->
										<i class="fa fa-share"></i>
										<div class="avatar-molde">
											<img class="avatar-picture wow bounceIn" src="<?php echo IMAGES; ?>profiles/6.jpg" >
										</div><!-- </avatar-molde> -->							
									</div><!-- </container-avatarcontactme> -->
								</div><!-- </modal-containerAvatar> -->
							</div><!-- </col-sm-3> -->
			        	</div><!-- </row> -->

    					<div class="row">
							<div class="col-md-10 centered">
								<div class="modal-containerStep">
									<span class="step-num">1</span>
									<div class="modal-text">
										What is your relationship?
									</div><!-- </modal-text> -->
								</div><!-- </modal-containerStep> -->
							</div><!-- </col-md-10> -->
						</div><!-- </row> -->

						<!-- Inicio Form de Inclusão Recomendação -->
			         <form action="#" method="post">
							<!-- Inicio Grupo Componente -->
							<div class="modal-groupForm">
								<div class="grupo-input">
						  			<!-- Seleção Relacionamento -->
						  			<span class="grupo-input-img"><i class="fa fa-random"></i></span>
						  			<select name="state" class="select-modal selectpicker" >
										<option class="opt-placeholder" value="-1" selected="">Select…
										</option>
										<optgroup label="Profissional">
											<option>
												Você supervisionava Paloma diretamente.
											</option>
											<option>
												Você respondia a Paloma diretamente.
											</option>
											<option>
												Você era sênior em relação a Paloma, mas não o supervisionava diretamente.
											</option>
											<option>
												Paloma era sênior em relação a você, mas não o supervisionava diretamente.
											</option>
											<option>
												Você trabalhava com Paloma no mesmo grupo.
											</option>
											<option>
												Você trabalhava com Paloma em grupos diferentes.
											</option>
											<option>
												Você e Paloma trabalhavam juntos, mas em empresas diferentes.
											</option>
											<option>
												Paloma era seu cliente.
											</option>
											<option>
												Você era cliente de Paloma.
											</option>
										</optgroup>
										<optgroup label="Formação acadêmica">
											<option>
												Você era professor de Paloma.
											</option>
											<option>
												Você era mentor de Paloma.
											</option>
											<option>
												Vocês estudaram juntos.
											</option>
										</optgroup>
									</select>
								</div><!-- </grupo-inpu> -->
							</div><!-- </modal-groupForm> -->

							<!-- Subtitulo da Inclusão -->
							<div class="row">
								<div class="col-md-10 centered">
									<div class="modal-containerStep">
										<div class="modal-subText">
											What were your jobs at the time?
										</div><!-- </modal-subText> -->
									</div><!-- </modal-containerStep> -->
								</div><!-- </col-md-10> -->
							</div><!-- </row> -->
							
							<!-- Inicio Grupo Componente -->
							<div class="modal-groupForm">
								<div class="grupo-input">
									<!-- Seleção de Funções -->
									<span class="grupo-input-img"><i class="fa fa-user"></i></span>
									<select name="state" class="select-modal selectpicker" >
										<option class="opt-placeholder" value="-1" selected="" data-type="pos">
											You…
										</option>
										<option>
											Microsoft IT Analyst na InterOp
										</option>
										<option>
											Server Administrator Pleno na Processor
										</option>
										<option value="310229553" data-type="pos">
											Server Administrator na Constat Serviços em Informática - Brazil
										</option>
										<option>
											Analista de Redes Microsoft na Grupo VG
										</option>
										<option>
											Supervisor TI na Broker Glambert Nestlé
										</option>
										<option>
											Analista de Suporte na Zampieron e Dalacorte Ltda - Severo Roth
										</option>
										<option>
											Aluno na Universidade Luterana do Brasil
										</option>
										<option value="178533085" data-type="edu">
											Aluno na Pontifícia Universidade Católica do Rio Grande do Sul
										<option>
									</select>
								</div><!-- </grupo-input> -->
							</div><!-- </modal-groupForm> -->
							
							<!-- Inicio Grupo Componente -->
							<div class="modal-groupForm">
								<div class="grupo-input">
									<!-- Seleção de Funções -->
									<span class="grupo-input-img"><i class="fa fa-users"></i></span>
									<select name="state" class="select-modal selectpicker" >
										<option class="opt-placeholder" value="-1" selected="" data-type="pos">
											Paloma…
										</option>
										<option>
											Auxiliar Financeiro na Instituto Rio Branco Ltda
										</option>
										<option>
											Aluno na Universidade Luterana do Brasil
										</option>					
									</select>
								</div><!-- </grupo-input> -->
							</div><!-- </modal-groupForm> -->

	    					<!-- Marcador de Passo -->
	    					<div class="row">
								<div class="col-md-10 centered">
									<div class="modal-containerStep">
										<span class="step-num">2</span>
										<div class="modal-text">
											Write a recommendation
										</div><!-- </modal-text> -->
									</div><!-- </modal-containerStep> -->
								</div><!-- </col-md-10> -->
							</div><!-- </row> --> 
							
							<!-- Inicio Grupo Componente -->
							<div class="modal-groupForm">
								
								<div class="modal-groupForm">
									<textarea class="textarea-modal" rows="5" placeholder="Ex. Paloma is detail oriented and has obtained great results for the company ..."></textarea>	
								</div><!-- </grupo-input> -->
							</div><!-- </modal-groupForm> -->

			            <input name="submit" type="submit" class="form-control" id="submit" value="Add Recommendation">
			         </form>
			      </div><!-- </modal-content> -->
			   </div><!-- </modal-dialog> -->
			</div><!-- </modal fade> -->			
			<!-- ==============================================
			End Session Modal's (Final área de modal's)
			=============================================== -->
		</div><!-- /div Final Layout Geral -->

		<!-- ==============================================
		Javascripts
       ================================================== -->
		<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
		<script src="<?php echo BOWER; ?>jquery/dist/jquery.min.js"></script>
		<!-- Include all compiled plugins (below), or include individual files as needed -->		
		<script src="<?php echo BOWER; ?>bootstrap-sass/assets/javascripts/bootstrap.min.js"></script> <!-- Bootstrap -->
		<script src="<?php echo JS; ?>front/tmp/classie.js"></script>
		<!-- Contact JS -->
		<script src="<?php echo BOWER; ?>jqBootstrapValidation/src/jqBootstrapValidation.js"></script><!--BootstrapValidation-->
		<!-- Wow JS -->
		<script src="<?php echo BOWER; ?>wow/dist/wow.min.js"></script> <!-- WOW --> 
		<!--JS for MAGNIFIC POPUP & ALL SCRIPTS& CALLS-->
		<script src="<?php echo BOWER; ?>magnific-popup/dist/jquery.magnific-popup.min.js"></script> <!--  POP UP VIDEO -->
		<script src="<?php echo BOWER; ?>flexslider/jquery.flexslider-min.js"></script> <!-- FlexSlider JS (Slider Indicações) -->
		<script src="<?php echo BOWER; ?>jquery.scrollTo/jquery.scrollTo.min.js"></script> <!-- ScrollTo -->		
		<script src="<?php echo BOWER; ?>jquery.easing/js/jquery.easing.min.js"></script> <!-- Easing -->
		<script src="<?php echo BOWER; ?>jpreloader/js/jpreloader.min.js"></script> <!-- PreLoader -->	
		<script src="<?php echo JS; ?>front/smooth-scrolling.js"></script> <!-- Deslocamento Suave Sesões - One Page -->
		<script src="<?php echo JS; ?>front/main.js"></script> <!-- Default JS -->
		<script src="<?php echo JS; ?>front/timeline-loader.js"></script> <!-- Plus Timeline Item -->
		<script src="<?php echo JS; ?>front/tmp/maina.js"></script> 

		<!-- Tuner ACessibilidade de Cores -->
		<script src="<?php echo TUNER; ?>js/tuner.js"></script>

		<div id="tuner" class="tuner">
			<label>Theme Colors</label>
				<ul class="colors">
				<li data-color="orange" class="color-orange"><span></span></li>
				<li data-color="purple" class="color-purple"><span></span></li>
				<li data-color="green" class="color-green"><span></span></li>
				<li data-color="pink" class="color-pink"><span></span></li>
				<li data-color="blue" class="color-blue active"><span></span></li>
				<li data-color="cyan" class="color-cyan"><span></span></li>
			</ul><!-- </colors> -->
			<label>Layout Styles</label>
			<ul class="layouts">
				<li data-layout="boxed">Boxed</li>
				<li data-layout="widescreen" class="active">Widescreen</li>
			</ul><!-- </layouts> -->
			<i id="tuner-switcher" class="fa fa-cogs"></i>
		</div><!--/ tuner -->
	</body>
</html>