			<!-- ==============================================
			Footer (Rodapé)
			=============================================== -->
			<footer>
				<section class="social-links">
				  	<div class="container">
				   	<div class="row">
				         <ul>
								<?php if($view_user->network->facebook) : ?>
				            <li>
				            	<a href="<?php echo 'https://www.facebook.com/'. $view_user->network->facebook ?>" target="_blank" title="">
				            		<span> <i class="fa fa-facebook"></i> </span>
				            	</a>
				            </li><!-- Icone Facebook -->
				            <?php endif; ?>
				            <?php if($view_user->network->twitter) : ?>
				            <li>
				            	<a href="<?php echo 'https://www.twitter.com/'. $view_user->network->twitter ?>" target="_blank" title="">
				            		<span> <i class="fa fa-twitter"></i> </span>
				            	</a>
				            </li><!-- Icone Twitter -->
				            <?php endif; ?>
				            <?php if($view_user->network->linkedin) : ?>
				            <li>
				            	<a href="<?php echo 'https://www.linkedin.com/in/'. $view_user->network->linkedin ?>" target="_blank" title="">
				            		<span> <i class="fa fa-linkedin"></i> </span>
				            	</a>
				            </li><!-- Icone LinkedIn -->
				            <?php endif; ?>
				            <?php if($view_user->network->instagram) : ?>
				            <li>
				            	<a href="<?php echo 'https://www.instagram.com/'. $view_user->network->instagram ?>" target="_blank" title="">
				            		<span> <i class="fa fa-instagram"></i> </span>
				            	</a>
				            </li><!-- Icone Instagram -->
				            <?php endif; ?>
				            <?php if($view_user->network->github) : ?>
				            <li>
				            	<a href="<?php echo 'https://www.github.com/'. $view_user->network->github ?>" target="_blank" title="">
				            		<span> <i class="fa fa-github"></i> </span>
				            	</a>
				            </li><!-- Icone GitHub -->
				            <?php endif; ?>
				            <?php if($view_user->email) : ?>
				            <li>
				            	<a href="<?php echo 'mailto:'. $view_user->email . '?subject=Eu tenho um comentário para você...' ?>" title="">
				            		<span> <i class="fa fa-envelope"></i></span>
				            	</a>
				            </li><!-- Icone e-mail -->
				            <?php endif; ?>
				         </ul><!-- Lista de elementos Redes SOciais -->
				    	</div><!-- /row -->
				  	</div><!-- /container -->
				</section><!-- </social-links> Final Sessão Redes Sociais -->

				<!-- ==============================================
				   Créditos (Credits)
				=============================================== -->
				<section class="copyright">
				  	<div class="container">
				   	<div class="col-md-12">
				      	<div class="text-center">
				        	<!-- Logo Header -->
				        		<section id="fox_footer" class="fox_footer">
				          		<div>
				          			<img src="<?php echo IMAGES; ?>logofooter.png" alt="Foxin by Elisandro Mello"> - &copy;<script>document.write(new Date().getFullYear())</script> - Designer coded and designed by <i class="fa fa-cloud-upload"></i> Elisandro Mello
				          		</div><!-- Informações de Rodapé -->
				        		</section><!-- </fox_footer> Final Sesão Info's Desenvolvedor-->
				        	<!--/ Logo Header-->
				      	</div><!-- </text-center> -->
				    	</div><!-- <qcol-md-12> -->
				  	</div><!-- </container> -->
				</section><!-- </copyright> -->
			</footer><!-- Final Área de Rodapé -->
			<!-- Back To Top -->
			<a id="back-to-top" href="#">
				<i class="font-icon-arrow-simple-up"></i>
			</a>
			<!-- End Back to Top -->

			<!-- ==============================================
			    Modal Contato (Contact)
			=============================================== -->
			<div class="modal fade" id="modal1" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
			    <div class="modal-dialog">
			    	<div class="modal-content modal-popup">
			        	<div class="modal-header">
		            	<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
		                <h2 class="modal-title">Contact-Me</h2>
			        	</div><!-- </modal-header> -->

			        	<div class="row">
				        	<div class="col-sm-3">
								<div class="modal-containerAvatar">
									<div class="container-avatarcontactme">
										<div class="avatar-molde">
											<img class="avatar-picture wow bounceIn" src="<?php echo IMAGES; ?>profiles/10.jpg" >
										</div><!-- </avatar-molde> -->
										<i class="fa fa-share"></i>
										<div class="avatar-molde">

											<?php
						                   if (!is_null($view_user->image)) {
						                       echo '<img class="avatar-picture wow bounceIn" src="' . BASE . 'public/uploads/users/' . $view_user->id . '/' . $view_user->image . '" width="160">';
						                   }
						                   else{
						                       echo '<img class="avatar-picture wow bounceIn" src="' . BASE . 'public/uploads/users/' . 'default' . '/' . 'default.png' . '" width="160">';
						                   }
						               ?>

										</div><!-- </avatar-molde> -->
									</div><!-- </container-avatarcontactme> -->
								</div><!-- </modal-containerAvatar> -->
							</div><!-- </col-sm-3> Colunas Avatares-->
			        	</div><!-- </row> -->

    					<div class="row">
							<div class="col-md-10 centered">
								<div class="modal-containerStep">
									<span class="step-num">1</span>
									<div class="modal-text">
										Escreva sua mensagem
									</div><!-- </modal-text> -->
								</div><!-- </moldal-containerStep> -->
							</div><!-- </col-md-10> -->
						</div><!-- </row>  -->

		            <form action="#" method="post">
							<div class="modal-groupForm">
								<textarea class="textarea-modal" rows="5" placeholder="Leave your message to the user"></textarea>
							</div>
		                <input name="submit" type="submit" class="form-control" id="submit" value="Send Message">
		            </form>
			      </div><!-- </modal-content> -->
			   </div><!-- </modal-dialog> -->
			</div><!-- </modal fade> -->

			<!-- ==============================================
			Modal Recommendation (add Recomendação)
			=============================================== -->
			<div class="modal fade" id="modal2" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
			   <div class="modal-dialog">
			    	<div class="modal-content modal-popup">
			        	<div class="modal-header">
		            	<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
		               <h2 class="modal-title">Recomende <?php echo $view_user->name ?></h2>
							<span>Esta recomendação será exibida no perfil de <?php echo $view_user->name ?>.</span>
			        	</div><!-- </modal-header> -->

			        	<div class="row">
				        	<div class="col-sm-3">
								<div class="modal-containerAvatar">
									<div class="container-avatarcontactme">
										<div class="avatar-molde">
											<?php
						                  if (!is_null($view_user->image)) {
						                     echo '<img class="avatar-picture wow bounceIn" src="' . BASE . 'public/uploads/users/' . $view_user->id . '/' . $view_user->image . '" width="160">';
						                  }
						                  else{
						                     echo '<img class="avatar-picture wow bounceIn" src="' . BASE . 'public/uploads/users/' . 'default' . '/' . 'default.png' . '" width="160">';
						                  }
						               ?>
										</div><!-- </avatar-molde> -->
										<i class="fa fa-share"></i>
										<div class="avatar-molde">
											<img class="avatar-picture wow bounceIn" src="<?php echo IMAGES; ?>profiles/6.jpg" >
										</div><!-- </avatar-molde> -->
									</div><!-- </container-avatarcontactme> -->
								</div><!-- </modal-containerAvatar> -->
							</div><!-- </col-sm-3> -->
			        	</div><!-- </row> -->

    					<div class="row">
							<div class="col-md-10 centered">
								<div class="modal-containerStep">
									<span class="step-num">1</span>
									<div class="modal-text">
										Selecionar Relacionamento?
									</div><!-- </modal-text> -->
								</div><!-- </modal-containerStep> -->
							</div><!-- </col-md-10> -->
						</div><!-- </row> -->

						<!-- Inicio Form de Inclusão Recomendação -->
			         <form action="#" method="post">
							<!-- Inicio Grupo Componente -->
							<div class="modal-groupForm">
								<div class="grupo-input">
						  			<!-- Seleção Relacionamento -->
						  			<span class="grupo-input-img"><i class="fa fa-random"></i></span>
						  			<select name="state" class="select-modal selectpicker" >
										<option class="opt-placeholder" value="-1" selected="">Select…
										</option>
										<optgroup label="Profissional">
											<option>
												Você supervisionava <?php echo $view_user->name; ?> diretamente.
											</option>
											<option>
												Você respondia a <?php echo $view_user->name; ?> diretamente.
											</option>
											<option>
												Você era sênior em relação a <?php echo $view_user->name; ?>, mas não o supervisionava diretamente.
											</option>
											<option>
												<?php echo $view_user->name; ?> era sênior em relação a você, mas não o supervisionava diretamente.
											</option>
											<option>
												Você trabalhava com <?php echo $view_user->name; ?> no mesmo grupo.
											</option>
											<option>
												Você trabalhava com <?php echo $view_user->name; ?> em grupos diferentes.
											</option>
											<option>
												Você e <?php echo $view_user->name; ?> trabalhavam juntos, mas em empresas diferentes.
											</option>
											<option>
												<?php echo $view_user->name; ?> era seu cliente.
											</option>
											<option>
												Você era cliente de <?php echo $view_user->name; ?>.
											</option>
										</optgroup>
										<optgroup label="Formação acadêmica">
											<option>
												Você era professor de <?php echo $view_user->name; ?>.
											</option>
											<option>
												Você era mentor de <?php echo $view_user->name; ?>.
											</option>
											<option>
												Vocês estudaram juntos.
											</option>
										</optgroup>
									</select>
								</div><!-- </grupo-inpu> -->
							</div><!-- </modal-groupForm> -->

							<!-- Subtitulo da Inclusão -->
							<div class="row">
								<div class="col-md-10 centered">
									<div class="modal-containerStep">
										<div class="modal-subText">
											Quais eram seus empregos no época?
										</div><!-- </modal-subText> -->
									</div><!-- </modal-containerStep> -->
								</div><!-- </col-md-10> -->
							</div><!-- </row> -->

							<!-- Inicio Grupo Componente -->
							<div class="modal-groupForm">
								<div class="grupo-input">
									<!-- Seleção de Funções -->
									<span class="grupo-input-img"><i class="fa fa-user"></i></span>
									<select name="state" class="select-modal selectpicker" >
										<option class="opt-placeholder" value="-1" selected="" data-type="pos">
											Você…
										</option>

										<?php foreach ($view_user->professionals as $professional): ?>

										<option>
											<?php echo $professional->company ?>
										</option>
										<?php endforeach; ?>

									</select>
								</div><!-- </grupo-input> -->
							</div><!-- </modal-groupForm> -->

							<!-- Inicio Grupo Componente -->
							<div class="modal-groupForm">
								<div class="grupo-input">
									<!-- Seleção de Funções -->
									<span class="grupo-input-img"><i class="fa fa-users"></i></span>
									<select name="state" class="select-modal selectpicker" >
										<option class="opt-placeholder" value="-1" selected="" data-type="pos">
											Paloma…
										</option>
										<option>
											Auxiliar Financeiro na Instituto Rio Branco Ltda
										</option>
										<option>
											Aluno na Universidade Luterana do Brasil
										</option>
									</select>
								</div><!-- </grupo-input> -->
							</div><!-- </modal-groupForm> -->

	    					<!-- Marcador de Passo -->
	    					<div class="row">
								<div class="col-md-10 centered">
									<div class="modal-containerStep">
										<span class="step-num">2</span>
										<div class="modal-text">
											Write a recommendation
										</div><!-- </modal-text> -->
									</div><!-- </modal-containerStep> -->
								</div><!-- </col-md-10> -->
							</div><!-- </row> -->

							<!-- Inicio Grupo Componente -->
							<div class="modal-groupForm">

								<div class="modal-groupForm">
									<textarea class="textarea-modal" rows="5" placeholder="Ex. Paloma is detail oriented and has obtained great results for the company ..."></textarea>
								</div><!-- </grupo-input> -->
							</div><!-- </modal-groupForm> -->

			            <input name="submit" type="submit" class="form-control" id="submit" value="Add Recommendation">
			         </form>
			      </div><!-- </modal-content> -->
			   </div><!-- </modal-dialog> -->
			</div><!-- </modal fade> -->
			<!-- ==============================================
			End Session Modal's (Final área de modal's)
			=============================================== -->
		</div><!-- /div Final Layout Geral -->

		<!-- ==============================================
		Javascripts
       ================================================== -->
      <!-- Libs - Bibliotecas JQuery via Bower-->		
		<script src="<?php echo BOWER; ?>jquery/dist/jquery.min.js"></script>
		<script src="<?php echo BOWER; ?>bootstrap-sass/assets/javascripts/bootstrap.min.js"></script>
		<script src="<?php echo BOWER; ?>wow/dist/wow.min.js"></script>
		<script src="<?php echo BOWER; ?>magnific-popup/dist/jquery.magnific-popup.min.js"></script>
		<script src="<?php echo BOWER; ?>flexslider/jquery.flexslider-min.js"></script>
		<script src="<?php echo BOWER; ?>jquery.scrollTo/jquery.scrollTo.min.js"></script>
		<script src="<?php echo BOWER; ?>jquery.easing/js/jquery.easing.min.js"></script>
		<script src="<?php echo BOWER; ?>jpreloader/js/jpreloader.min.js"></script>
		<!-- Libs - Bibliotecas JQuery -->
		<script src="<?php echo JS; ?>libs/smooth-scrolling.js"></script>
		 <!-- Scripts JavaScript Personalizados-->
		<script src="<?php echo JS; ?>front/main.js"></script>
		<script src="<?php echo JS; ?>front/timeline-loader.js"></script>
		<!-- Janela Video de Apresentação Perfil Usuario -->
		<!--<script src="<?php echo JS; ?>front/videopopup.js"></script>-->
		<!-- Tuner ACessibilidade de Cores -->
		<script src="<?php echo TUNER; ?>js/tuner.js"></script>

		<div id="tuner" class="tuner">
			<label>Theme Colors</label>
				<ul class="colors">
				<li data-color="orange" class="color-orange"><span></span></li>
				<li data-color="purple" class="color-purple"><span></span></li>
				<li data-color="green" class="color-green"><span></span></li>
				<li data-color="pink" class="color-pink"><span></span></li>
				<li data-color="blue" class="color-blue active"><span></span></li>
				<li data-color="cyan" class="color-cyan"><span></span></li>
			</ul><!-- </colors> -->
			<label>Layout Styles</label>
			<ul class="layouts">
				<li data-layout="boxed">Boxed</li>
				<li data-layout="widescreen" class="active">Widescreen</li>
			</ul><!-- </layouts> -->
			<i id="tuner-switcher" class="fa fa-cogs"></i>
		</div><!--/ tuner -->
	</body>
</html>