<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8">
		<title>Profile User - ProfileIT</title>
		 <meta name="viewport" content="width=device-width, initial-scale=1">
		    		
		<link rel="stylesheet" type="text/css" href="<?php echo CSS; ?>profile/home.css" />
		<link rel="stylesheet" type="text/css" href="<?php echo CSS; ?>profile/general.css" />
		<link rel="stylesheet" type="text/css" href="<?php echo CSS; ?>profile/plugins.css" />
		<link rel="stylesheet" type="text/css" href="<?php echo CSS; ?>profile/controlnav.css" />
		<link rel="stylesheet" type="text/css" href="<?php echo CSS; ?>profile/fonts.css" />
		<link rel="stylesheet" type="text/css" href="<?php echo CSS; ?>profile/blockquotes.css" />
		<link rel="stylesheet" type="text/css" href="<?php echo CSS; ?>profile/tooltip.css" />
		<link rel="stylesheet" type="text/css" href="<?php echo CSS; ?>profile/nav.css" />

		<script src="<?php echo BOWER; ?>jquery/dist/jquery.min.js"></script>

	</head>
	<body>
		<!-- This section is for Splash Screen -->
		<section id="jSplash">
			<div id="circle"></div>
		</section>
		<!-- End of Splash Screen -->

		<!-- ==============================================
		        Navbar
		 =============================================== -->
		<div id="home-nav" class="navbar navbar-default navbar-fixed-top" role="navigation">
		  <div class="container">
		    <div class="navbar-header">
		      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1"> <span class="sr-only">Toggle navigation</span> <span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> </button>
		      <a class="navbar-brand" href="#home"> 
		        <!-- Logo Header -->
		        <section id="foxin" class="foxin">
		          <div> <img src="<?php echo IMG; ?>Logo_Navbar.png" alt="Foxin by Elisandro Mello"> </div>
		        </section>
		        <!--/ Logo Header--> 
		      </a>
		    </div>
		    <div class="navbar-collapse collapse" id="bs-example-navbar-collapse-1">
		      <ul class="nav navbar-nav navbar-right">
		        <li><a href="#home">Home</a></li>
		        <li><a href="#recommentandations">Quotes</a></li>
		        <li><a href="#history">History</a></li>
		        <li><a href="#skills">Skill</a></li>
		        <li><a href="#mural">Mural</a></li>
		        <li><a href="#portfolio">Portfolio</a></li>
		        <li><a href="<?php echo BASE . 'login/sair'; ?>">Sair</a></li>		        
		      </ul>
		    </div>
		  </div>
		</div>

		<div class="layout">
