	   <!-- ==============================================
	   Layout Content Site (Definição de Layout)
      ====================================-->
		<div class="layout">
			<!-- ==============================================
			Main Start (Inicio do Corpo de Conteúdo)
			=============================================== -->
			<main>
				<!-- ========================================= -->
				<!--Section Profile(Resumo Profile)                            -->
				<!-- ========================================= -->
				<section id="profile" class="main-block">
					<div class="container text-center">
						<!-- Profile Title -->
						<div class="title-main text-left wow fadeIn">
							<div class="main-title__inner">
								<div class="text-right main-title__left">
									<i class="fa fa-female mega"></i>
									<h1 class="title-session">perfil</h1>
									<em class="title-description">Informações Pessoais</em>
								</div><!-- </text-right main-title__left> -->
								<div class="main-title__right">
									<p class="resumo">
										<?php echo $view_user->registry->about; ?>
									</p><!-- </resumo> -->
								</div><!-- </main-title__right> -->
							</div><!-- </main-title__inner> -->
						</div><!-- </main-title> (Icone Session, Title, Description Title e Linha DivisóriaV) -->

						<!-- ========================================= -->
						<!-- Conteúdo Perfil                           -->
						<!-- ========================================= -->
						<div class="row main-block__padder text-left">
							<!-- Icones de Informações Visuais -->
							<div class="col-lg-4 col-sm-6 col-md-6 text-center wow fadeInUp">
								<div class="inline-block photo-column-inner">
									<div class="col-md-12">
										<div class="panel-view wraper-view">
											<!-- Icone Certificação Processos -->
											<a class="badge-idioma pointer-cursor <?php echo ($view_sugestoes['Processos'] == null) ? "icone-enabled" : "icone-disabled" ; ?>" data-tooltip="<?php echo ($view_sugestoes['Processos'] == null) ? 'Certificação em Processos' : 'Não Possui Certificação em Processos' ; ?>" href="home.html">
												<i class="fa fa-black-tie" alt="Edit Curriculo"></i>
											</a>
											<!-- Icone Tempo de Experiencia -->
											<?php if ($view_total[0] < 5)  { ?>
											<a class="badge-disabled icone-disabled pointer-cursor" href="home.html" data-tooltip="-5 anos de experiência.">
												<i class="fa fa-star-half-empty"></i>
											</a>
											<?php }
											else {
											?>
											<a class="badge-graduacao icone-enabled pointer-cursor" href="home.html" data-tooltip="+5 anos de experiência.">
												<i class="fa fa-star"></i>
											</a>
											<?php } ?>
											<!-- Icone Certificação Microsoft -->
											<a class="badge-experiencia icone-enabled pointer-cursor <?php echo ($view_resumos['Microsoft'] != "Nao") ? "icone-enabled" : "icone-disabled" ; ?>" data-tooltip="<?php echo ($view_resumos['Microsoft'] != "Nao") ? 'Certificação Microsoft' : 'Não Possui Certificação' ; ?>"" href="home.html">
												<i class="fa fa-windows" alt="Certificação Microsoft" ></i>
											</a>

										</div><!-- </panel-view> -->
									</div>
									<div class="col-md-12 wraper-viewBottom">
										<div class="panel-view">
											<!-- Icone Graduação Superior -->
											<a class="badge-idioma pointer-cursor <?php echo ($view_resumos['Graduacao'] != null) ? "icone-enabled" : "icone-disabled" ; ?>" data-tooltip="<?php echo ($view_resumos['Graduacao'] != null) ? 'Graduação Completa' : 'Não Possui Graduação' ; ?>" href="home.html">
												<i class="fa fa-graduation-cap" alt="Edit Curriculo"></i>
											</a>
											<!-- Icone Certificação Linux -->
											<a class="badge-dominio pointer-cursor <?php echo ($view_resumos['Linux'] != null) ? "icone-enabled" : "icone-disabled" ; ?>" href="home.html" data-tooltip="<?php echo ($view_resumos['Linux'] != null) ? 'Certificação Linux' : 'Não Possui Certificação' ; ?>">
												<i class="fa fa-linux" alt="Edit Curriculo"></i>
											</a>
											<!-- Icone Fluência Inglês -->
											<a class="badge-coracao pointer-cursor <?php echo ($view_resumos['Idioma'] == "Fluente") ? "icone-enabled" : "icone-disabled" ; ?>" data-tooltip="<?php echo ($view_resumos['Idioma'] != null) ? 'Inglês Fluente' : 'Sem Fluência no Inglês' ; ?>" href="home.html">
												<i class="fa fa-language" alt="Alterar Questionário" ></i>
											</a>
										</div><!-- </panl-view> -->
									</div>
									<div class="md-padder">
										<a class="btn btn-primary btn-lg margin-btm-30" data-tooltip="Download Resume Profile" href="update.html" target="_blank"> <i class="fa fa-user"></i> <span class="hidden-xs"> Download </span> Resume </a>
									</div>
								</div>
							</div><!-- Coluna Icones Visuais-->

							<!-- #Informações Perfis Pessoais -->
							<div class="col-lg-4 col-sm-6 col-md-6 text-center info-column wow fadeInUp">
								<div class="wrapper">
									<h5 class="text-subtitulo">Informações Pessoais</h5>
									<ul class="padder list-unstyled info-list">
										<li>Nome		: <?php echo $view_user->name; ?> <?php echo $view_user->last_name; ?> </li>
										<li>Idade : <?php echo $view_idade; ?> anos</li>
										<li>Fone		: <?php echo $view_celular; ?>				</li>
										<li>e-mail	: <a href="<?php echo 'mailto:'. $view_user->email ?>"><?php echo $view_user->email; ?></a></li>
									</ul>
									<ul class="list-inline list-gutter-xs padder h5 bare-social-menu">
										<?php if($view_user->network->linkedin) : ?>
										<li>
											<a href="<?php echo 'https://www.linkedin.com/in/'. $view_user->network->linkedin ?>" class="behance-color">
												<i class="fa fa-linkedin"></i>
											</a>
										</li>
										<?php endif; ?>
										<?php if($view_user->network->facebook) : ?>
										<li>
											<a href="<?php echo 'https://www.facebook.com/'. $view_user->network->facebook ?>" class="behance-color">
												<i class="fa fa-facebook"></i>
											</a>
										</li>
										<?php endif; ?>
										<?php if($view_user->network->twitter) : ?>
										<li>
											<a href="<?php echo 'https://www.twitter.com/'. $view_user->network->twitter ?>" class="behance-color">
												<i class="fa fa-twitter"></i>
											</a>
										</li>
										<?php endif; ?>
										<?php if($view_user->network->github) : ?>
										<li>
											<a href="<?php echo 'https://www.github.com/'. $view_user->network->github ?>" class="behance-color">
												<i class="fa fa-github"></i>
											</a>
										</li>
										<?php endif; ?>
										<?php if($view_user->network->instagram) : ?>
										<li>
											<a href="<?php echo 'https://www.instagram.com/'. $view_user->network->instagram ?>" class="behance-color">
												<i class="fa fa-instagram"></i>
											</a>
										</li>
										<?php endif; ?>
									</ul>
								</div><!-- </> -->
							</div><!-- Coluna Informações Pessoais -->

							<!-- Presentation ticket -->
							<div class="col-xs-12 col-sm-12 col-md-12 col-lg-4 text-center story-column wow fadeInUp">
								<div class="wrapper-resumo">
									<!--Horas de Projetos e Trabalhos-->
									<div class="wow fadeIn" data-wow-delay="2s">
										<div class="col-xs-9 col-sm-6 col-md-6 col-lg-12 centered">
											<div class="charge">
												<h2><span><?php echo $view_profile->profile; ?></span></h2>
											</div>
										</div>
										<div class="row">
											<div class="col-xs-9 col-sm-5 col-md-5 col-lg-12 centered">
												<div class="container-star">
													<div class="star-molde">
														<img class="star-picture wow bounceIn" src="<?php echo IMAGES; ?>estrela1_40.png" >
													</div>
													<div class="star-molde">
														<img class="star-picture wow bounceIn" src="<?php echo IMAGES; ?>estrela1_40.png" >
													</div>
													<div class="star-molde">
														<img class="star-picture wow bounceIn" src="<?php echo IMAGES; ?>estrela1_40.png" >
													</div>
													<div class="star-molde">
														<img class="star-picture wow bounceIn" src="<?php echo IMAGES; ?>estrela2_40.png" >
													</div>
													<div class="star-molde">
														<img class="star-picture wow bounceIn" src="<?php echo IMAGES; ?>estrela2_40.png" >
													</div>
												</div>
											</div>
										</div>
										<div class="row">
											<div class="col-xs-9 col-sm-6 col-md-6 col-lg-12 centered">
												<div class="description text-left">
						                     <!--My Profile - Dados Profissionais-->
						                     <div class="aboutme-title wow fadeIn" data-wow-delay="1s">
						                        <h5><?php echo $view_total[0] ?> anos e <?php echo $view_total[1] ?> meses<span>   - Experiência Efetiva </span> </h5>

						                        <?php if ($view_resumos['Microsoft'] != null) { ?>
						                        <h5><span> Profissional com </span> <?php echo $view_resumos['Microsoft'] ?>  </h5>
						                        <?php } ?>

														<?php if ($view_resumos['Linux'] != null) { ?>
						                        <h5><span> Profissional com </span> Certificação <?php echo $view_resumos['Linux'] ?>  </h5>
						                        <?php } ?>

						                        <h5><span> <?php echo $view_resumos['Academico'] ?> em  </span>  <?php echo $view_resumos['Curso']; ?> <?php echo ($view_resumos['Status'] == 1 || $view_resumos['Status'] == 2) ? "Incompleto" : 'Completo'; ?> </h5>

														<h5><span><?php echo (!$view_resumos['Empregado']) ? 'Empresa Atual: ' : 'Última Empresa' ; ?> </span> <?php echo $view_resumos['Empresa'];  ?> </h5>

														<h5><span><?php echo ($view_resumos['Empregado']) ? 'Saída: ' : null ; ?> </span> <?php echo ($view_resumos['Empregado']) ? $view_resumos['Empregado']->format('M/Y') : null ; ?> </h5>
						                     </div><!-- </aboutme-title> -->
												</div><!-- </description > -->
											</div><!-- </colunas>-->
										</div><!-- </row> -->
									</div>
								</div>
							</div><!-- Container Bilhete de Apresentação -->
						</div><!-- </main-block__padder> -->
					</div><!-- </container> -->
				</section><!-- </section> Profile -->
				<!-- ==============================================
       		Skill Técnico (Qualificações e Atributos Técnicos)
        		=============================================== -->
        		<?php if ($view_analiseQualificacoes) : ?>
				<section id="skills" class="main-block">
					<div class="container text-center">
						<div class="title-main text-left wow fadeIn">
							<div class="main-title__inner">
								<div class="text-right main-title__left">
									<i class="fa fa-area-chart"></i>
									<h1 class="title-session">Qualificações</h1>
									<em class="title-description">Competências e Habilidades</em>
								</div>
								<div class="main-title__right">
									<p class="resumo">
										Estas são minha principais qualificaões, competências e habilidades. Fico a disposição para colaborar e cooperar em projetos e tarefas nestes escopos. Também gostaria de me aperfeiçoar em conhecimentos que a comunidade possa estar agregando.
									</p>
								</div>
							</div>
						</div><!-- </main-title> (Icone Session, Title, Description Title e Linha DivisóriaV) -->

						<div class="container-skill">
							<div class="row">
						    	<div class="col-md-6 col-sm-12 wow bounceInLeft">
							        <div>
								        <p class="texto_profileit text-left">

											<?php
												echo($view_user->skills[0]->description);
											?>

								        </p>
								    </div>
						    	</div>
								<div class="col-md-6 col-sm-12 wow bounceInRight" data-wow-delay="0.3s">
									<div class="skill-bar">
								    	<ul>
											<?php
												foreach ($view_user->competencies as $competency): ?>
													<li>
														<div class="bar" data-value="" style="width: <?php echo $competency->level ?>0%;">
															<h5><?php echo $competency->qualification->qualification ?></h5>
														</div>
														<span><?php echo $competency->level ?> / 10</span>
													</li>
											<?php	endforeach
											?>
								      </ul><!-- </ul> Lista de Barras Skill -->
								   </div><!-- </skill-bar> -->
								</div><!-- </col-md-6 col-sm-12> -->
							</div><!-- </row> -->
							<div class="row">
								<div class="col-md-12">
									<a class="btn btn-primary btn-lg pull-right" data-tooltip="Professional summary" href="assets/elisandromelloresume.pdf" target="_blank"> <i class="fa fa-paper-plane"></i> <span class="hidden-xs">Download meu</span> Curriculo </a>
								</div><!-- </col-md-12> -->
							</div><!-- </row> Button De Dowload Competências Técnicas-->
						</div><!-- </container-skill -->
				  	</div><!-- </container> -->
				</section><!-- </section> Sessão Skill Técnico -->
				<?php endif; ?>
				<!-- ========================================= -->
				<!-- Resume Section (Acadêmico e Profissional) -->
				<!-- ========================================= -->
				<section id="resume" class="main-block">
					<div class="container text-center">
						<!-- Resume Title -->
						<div class="title-main text-left wow fadeIn">
							<div class="main-title__inner">
								<div class="text-right main-title__left">
									<i class="fa fa-book mega"></i>
									<h1 class="title-session">Resumo</h1>
									<em class="title-description">Histórico Acadêmico e Profissional</em>
								</div><!-- </ main-title__left> -->
								<div class="main-title__right">
									<p class="resumo">
										Sessão com descritivo de meu histórico acadêmico, listanto formação, curso e ano de conlusão. A seguir resumo profissional demonstrando atribuições, empresas e período de atuação.
									</p><!-- </resumo> -->
								</div><!-- </main-title__right> -->
							</div><!-- </main-title__inner> -->
						</div><!-- </main-title> (Icone Session, Title, Description Title e Linha DivisóriaV) -->

						<!-- ========================================= -->
						<!-- Section Academic(Resumo Acadêmico         -->
						<!-- ========================================= -->
						<div class="container-education text-left" id="education">
							<!-- Educaton title -->
							<div class="table wow fadeIn">
								<div class="icon-titleSession">
									<i class="fa fa-graduation-cap"></i>
								</div>
								<div class="title-sessionResume">
									<h5>Education</h5>
								</div>
								<div class="title-line"></div>
							</div><!-- Final Titulo Education (Icone, Title e Linha divisória) -->

							<!-- Timeline Education -->
							<div class="sub-containerEducation">
								<div class="timeline">

									<!-- Dashed Line -->
									<div class="timeline-rail">
										<span class="timeline-loader-btn plus-icon plus-icon-small"></span>
									</div><!--Linha do tempo tracejada -->

									<!-- Container Timeline Items -->
									<div class="timeline-items">

										<?php foreach ($view_user->academics as $academic): ?>
										<!-- Container Item Unitário -->
										<div class="clearfix timeline-item">
											<!-- Box Marcadores de Tempo e Status -->
											<div class="bullet-box clearfix">
												<!-- Marcador Tempo Timeline -->
												<div class="tolltipBullet">
													<!-- Marcador -->
													<div class="item-marker hidden-xs wow fadeInLeft">
														<span>
															<i class="fa fa-clock-o"></i>
														</span>
														<?php
															if ($academic->date_conclusion === Null){
																echo "-";
															}
															else {
																echo $academic->date_conclusion->format('Y');
															}
														?>
													</div><!--(Icon Clock e Data)  -->
													<div class="timeline-item-bullet"></div><!-- Espcaçamento e Icon Marcação -->
												</div><!-- Final Marcador Tempo e Icon Plus	-->
												<div class="timeline-box hidden-xs wow fadeInRight">
													<span>A+</span>
													<small>grade</small>
												</div>
											</div><!-- </bullet-box> Final Box de Marcador -->

											<!-- Conteúdo do Item - Timeline -->
											<div class="timeline-itemContent wow fadeInRight">
												<h6 class="text-subtitulo"><?php echo $academic->course ?></h6>
												<h5 ><?php echo $academic->level ?></h5>
												<ul class="text-subtituloItem">
													<li><?php echo $academic->institution ?></li>
													<li>&#8226;</li>
													<li><?php echo $academic->local ?></li>
												</ul>
											</div><!-- </timeline-itemContent> Conteúdo Item -->
										</div><!-- </timeline-item> Container Unitário Item -->
										<?php endforeach ?>

										<!-- Item Oculto -->
										<div class="clearfix timeline-item hidden">
											<!-- Box Marcadores de Tempo e Status -->
											<div class="bullet-box clearfix">
												<!-- Marcador Tempo Timeline -->
												<div class="tolltipBullet">
													<!-- Marcador -->
													<div class="item-marker hidden-xs wow fadeInLeft">
														<span>
															<i class="fa fa-clock-o"></i>
														</span>
														2008 - 2009
													</div><!--(Icon Clock e Data)  -->
													<div class="timeline-item-bullet"></div><!-- Espcaçamento e Icon Marcação -->
												</div><!-- Final Marcador Tempo e Icon Plus	-->
												<div class="timeline-box hidden-xs wow fadeInRight">
													<span>A+</span>
													<small>grade</small>
												</div>
											</div><!-- </bullet-box> Final Box de Marcador -->

											<!-- Conteúdo do Item - Timeline -->
											<div class="timeline-itemContent wow fadeInRight">
												<h6 class="text-subtitulo">master degree of design</h6>
												<ul class="text-subtituloItem">
													<li>name of university</li>
													<li>&#8226;</li>
													<li>USA</li>
												</ul>
											</div><!-- </timeline-itemContent> Conteúdo Item -->
										</div><!-- </timeline-item> Container Unitário Item Oculto -->
									</div><!-- </timeline-items> (Final Container Timeline Items-->
								</div><!-- </timeline> (Final Timeline Education-->
							</div><!-- </sub-containerEducation> -->
						</div><!-- </container-education> -->

						<!-- ========================================= -->
						<!-- Section Experience(Resumo Experiences)    -->
						<!-- ========================================= -->
						<div class="container-experience text-left" id="experience">
							<!-- Experince title -->
							<div class="table wow fadeIn">
								<div class="icon-titleSession">
									<i class="fa fa-flask"></i>
								</div>
								<div class="title-sessionResume">
									<h5>experience</h5>
								</div>
								<div class="title-line"></div>
							</div>

							<!-- @EXPERIENCE TIMELINE -->
							<div class="sub-containerExperience">
								<div class="timeline">
									<!-- Dashed Line -->
									<div class="timeline-rail">
										<span class="timeline-loader-btn plus-icon plus-icon-small"></span>
									</div><!--Linha do tempo tracejada -->
									<!-- Container Timeline Items -->
									<div class="timeline-items">
										<?php foreach ($view_user->professionals as $professional): ?>
										<!-- Container Item Unitário -->
										<div class="clearfix timeline-item">
											<!-- Box Marcadores de Tempo e Status -->
											<div class="bullet-box clearfix">
												<!-- Marcador Tempo Timeline -->
												<div class="tolltipBullet">
													<!-- Marcador -->
													<div class="item-marker hidden-xs wow fadeInLeft">
														<span>
															<i class="fa fa-clock-o"></i>
														</span>
														<?php echo $professional->date_entry->format('Y') ?> - Now
													</div><!--(Icon Clock e Data)  -->
													<div class="timeline-item-bullet"></div><!-- Espcaçamento e Icon Marcação -->
												</div><!-- Final Marcador Tempo e Icon Plus	-->
												<div class="timeline-box hidden-xs wow fadeInRight" style="background-image: url(<?php echo IMAGES; ?>clients/01.png)">
												</div>
											</div><!-- </bullet-box> Final Box de Marcador -->

											<!-- Conteúdo do Item - Timeline -->
											<div class="timeline-itemContent wow fadeInRightt">
												<h6 class="text-subtitulo"><?php echo $professional->function ?></h6>
												<ul class="text-subtituloItem">
													<li><?php echo $professional->company ?></li>
													<li>&#8226;</li>
													<li><?php echo $professional->location ?></li>
												</ul>
												<p class="texto_profileit">
													<?php echo $professional->assignments ?>
												</p>
											</div><!-- </timeline-itemContent> Conteúdo Item -->
										</div><!-- </timeline-item> Container Unitário Item -->
										<?php endforeach ?>


										<!-- Container Item Unitário -->
										<div class="clearfix timeline-item  hidden">
											<!-- Box Marcadores de Tempo e Status -->
											<div class="bullet-box clearfix">
												<!-- Marcador Tempo Timeline -->
												<div class="tolltipBullet">
													<!-- Marcador -->
													<div class="item-marker hidden-xs wow fadeInLeft">
														<span>
															<i class="fa fa-clock-o"></i>
														</span>
														2010 - 2012
													</div><!--(Icon Clock e Data)  -->
													<div class="timeline-item-bullet"></div><!-- Espcaçamento e Icon Marcação -->
												</div><!-- Final Marcador Tempo e Icon Plus	-->
												<div class="timeline-box hidden-xs wow fadeInRight" style="background-image: url(images/clients/07.png)">
												</div>
											</div><!-- </bullet-box> Final Box de Marcador -->

											<!-- Conteúdo do Item - Timeline -->
											<div class="timeline-itemContent wow fadeInRightt">
												<h6 class="text-subtitulo">lead web developer</h6>
												<ul class="text-subtituloItem">
													<li>name of company</li>
													<li>&#8226;</li>
													<li>USA</li>
												</ul>
												<p class="texto_profileit">
													Coordinates for abs positioning use the closest positioned parent box of the positioned element. So assuming that your div creating the corner(s) has no parent elements that are rel or abs positioned it will default up the chain to the html element which is at 0,0 of the viewport.
												</p>
											</div><!-- </timeline-itemContent> Conteúdo Item Oculto-->
										</div><!-- </timeline-item> Container Unitário Item Oculto-->
									</div><!-- </timeline-items> (Final Container Timeline Items-->
								</div><!-- </timeline> (Final Timeline Education-->
							</div><!-- </sub-containerEducation> -->
						</div><!-- </container-education> -->
					</div><!-- </container> -->
				</section><!-- </session> -->
				<!-- ==============================================
				Recomendations (Recomendações Recebidas)
		        =============================================== -->
				<section class="recommendation" id="recommendations" data-stellar-background-ratio="0.6">
					<div class="overlay"></div>
				   <div class="above-overlay">
				   	<div class="container">
					      <div class="row">
					        <div class="col-md-12">
					         	<h1 class="text-center margin-btm-30"> Recomendações<span class="cursor-tag">_</span> </h1>
					        </div><!-- </col-md-12> -->
					      </div><!-- </row> -->
					      <div class="row">
					        <div class="col-md-12">
					         	<div class="text-center quote-icon"> <i class="fa fa-quote-left"></i> </div>
					        </div><!-- </col-md-12> -->
					      </div><!-- </row> -->
					      <div class="row">
					         <div class="col-md-8 col-md-offset-2">
					         	<div class="quote-slider">
					            	<ul class="slides">
					              		<?php
					              		foreach ($view_user->recommendations as $recommendation):
					              			if ($recommendation->approved == 1) {
                             		?>
							              		<li>
									               <div class="quote-slider-slide-container">
															<p class="quote-slider-name"><?php echo $recommendation->relationship ?>. </p>
										               <?php
										                   $adviser = User::find($recommendation->adviser_id);
										                   if (!is_null($view_user->image)) {
										                       echo '<img class="avatar-md quote-slider-img" src="' . BASE . 'public/uploads/users/' .  $recommendation->adviser_id . '/' . $adviser->image . '" >';
										                   }
										                   else{
										                       echo '<img class="avatar-md quote-slider-img" src="' . BASE . 'public/uploads/users/' . 'default' . '/' . 'default.png' . '">';
										                   }
										               ?>
									                  <p class="quote-slider-single"> <?php echo $recommendation->description ?>. </p>
									                  <p class="quote-slider-name"><?php echo $adviser->name?> - <?php echo $recommendation->charge_recommendation ?>. </p>
									               </div><!-- </quote-slider-slide-container> -->
									            </li>
							            <?php
							            	}
							            endforeach
							            ?>
					            	</ul><!--</slides> Slides de Recomendação -->
					          	</div><!-- </quote-slider> -->
					        	</div><!-- </col-md-8 col-md-offset-2> -->
					      </div><!-- </row> -->
				    	</div><!-- </container> -->
				  	</div><!-- </above-overlay> -->
				</section><!-- </recommendation> Sessão Apresentação Recomendações-->

				<!-- ==============================================
				Contact-Me (Contate-me ou add uma Recomendação)
		        =============================================== -->
				<section id="contact-area">
				    <div class="overlay-contactme"></div>
				    <div class="container">
				        <div class="row">
				            <div class="col-md-offset-2 col-md-8 col-sm-12">
			                  <div class="wow bounceIn section-title">
		                        <div class="text-center">
			                        <h2>Contate-me ou me recomende </h2>
			                        <p class="texto_profileit wow fadeInUp" data-wow-delay="0.5s">Envie-me uma mensagem caso queira que eu retorne o contato. Ou adicione uma recomendação sobre minhas qualificações e habilidades, eu ficaria muito grato..</p>
			                     </div><!-- </text-center -->
		                     </div><!-- </section-title> -->
		                     <div class="wow fadeInUp contatc-form" data-wow-delay="0.8s">
		                        <form action="#" method="post">
		                           <div class="col-md-6 col-xs-12 text-center">
												<a class="btn envio disabled" href="#" data-toggle="modal" data-target="#modal1"> <i class="fa fa-paper-plane"></i> <span class="hidden-xs">Envie </span> Mensagem </a>
		                           </div><!-- </col-md-6 col-xs-12> -->
		                           <div class="col-md-6 col-xs-12 text-center">
												<a class="btn envio disabled" href="#" data-toggle="modal" data-target="#modal2"> <i class="fa fa-paper-plane"></i> <span class="hidden-xs">Adicionar  </span> Recomendação </a>
		                           </div><!-- </col-md-6 col-xs-12> -->
		                        </form>
		                     </div><!-- </contatc-form> -->
				            </div><!-- </col-md-offset-2 col-md-8 col-sm-12> -->
				        </div><!-- </row> -->
				    </div><!-- </container -->
				</section><!-- </contact-me> Final Sessão de Contate-me -->
			</main><!-- Main End (Final do Corpo de Conteúdo) -->