      <footer>
         <!-- ==============================================
             Footer (Rodapé)
         =============================================== -->
         <section class="social-links">
            <div class="container">
               <div class="row">
                  <ul>
                     <li>
                        <a href="https://www.facebook.com/profile.php?id=1800765934" target="_blank" title="">
                           <span>
                              <i class="fa fa-facebook"></i>
                           </span>
                        </a>
                     </li>
                     <li>
                        <a href="https://twitter.com/elisandromello" target="_blank" title="">
                           <span>
                              <i class="fa fa-twitter"></i>
                           </span>
                        </a>
                     </li>
                     <li>
                        <a href="http://www.linkedin.com/in/elisandromello" target="_blank" title="">
                           <span>
                              <i class="fa fa-linkedin"></i>
                           </span>
                        </a>
                     </li>
                     <li>
                        <a href="http://www.instagram.com/iamelisandromello" target="_blank" title="">
                           <span>
                              <i class="fa fa-instagram"></i>
                           </span>
                        </a>
                     </li>
                     <li>
                        <a href="https://github.com/iamelisandromello" target="_blank" title="">
                           <span>
                              <i class="fa fa-github"></i>
                           </span>
                        </a>
                     </li>
                     <li>
                        <a href="mailto:iam@elisandromello.com.br?subject=Eu tenho um comentário para você..." title="">
                           <span>
                              <i class="fa fa-envelope"></i>
                           </span>
                        </a>
                     </li>
                  </ul>
               </div><!-- /row -->
            </div><!-- /container -->
         </section>

         <!-- ==============================================
            Créditos (Credits)
          =============================================== -->
         <section class="copyright">
           <div class="container">
             <div class="col-md-12">
               <div class="text-center">
                  <!-- Logo Header -->
                  <section id="fox_footer" class="fox_footer">
                     <div>
                        <img src="<?php echo IMAGES; ?>logofooter_login.png" alt="Foxin by Elisandro Mello">   -  &copy;<?php echo date("Y")  ?> - Design and Development Encoded by
                        <i class="fa fa-cloud-upload"></i>
                        Elisandro Mello
                     </div>
                  </section>
                  <!--/ Logo Header-->
               </div>
             </div>
           </div><!-- </> -->
         </section><!-- </copyright> -->
      </footer>
      <!-- ==============================================
      Javascripts
       ================================================== -->
      <!-- Libs - Bibliotecas JQuery via Bower-->
      <script src="<?php echo BOWER; ?>jquery/dist/jquery.min.js"></script>
      <script src="<?php echo BOWER; ?>bootstrap-sass/assets/javascripts/bootstrap.min.js"></script>
      <script src="<?php echo BOWER; ?>retina.js/dist/retina.min.js"></script>
      <script src="<?php echo BOWER; ?>jquery-backstretch/jquery.backstretch.min.js"></script>
       <!-- Scripts JavaScript Personalizados-->
      <script src="<?php echo JS; ?>login/scripts.js"></script>
   </body>
</html>