	   <!-- ==============================================
	   Layout Content Site (Definição de Layout)
      ====================================-->
		<div class="layout">
			<main>
				<!-- ==============================================================
			    Update Questionário de Análise Pefil Profissional (Perguntas Avaliativas)
			   =============================================================== -->
				<section class="quiz-questions" id="quiz-questions">
					<div class="container">
					   <div class="container-fluid">   
					      <div class="row">
					      	<div class="col-lg-4 col-md-5">
					      		<div class="card card-user">
					      			<div class="backgroundHeader">
					      				<img src="<?php echo IMAGES; ?>background.jpg" alt="..."/>
					      			</div><!-- </div>image> -->
					      			<div class="content">
					      				<div class="author">
					      					<!--<img class="avatar border-white" src="<?php echo IMAGES; ?>elisandromello.jpg" alt="..."/>-->

							               <?php
							                   if (!is_null($view_user->image)) {
							                       echo '<img class="avatar border-white" src="' . BASE . 'public/uploads/users/' . $view_user->id . '/' . $view_user->image . '" width="160">';
							                   }
							                   else{
							                       echo '<img class="avatar border-white" src="' . BASE . 'public/uploads/users/' . 'default' . '/' . 'default.png' . '" width="160">';
							                   }
							               ?>

					      					<h4 class="title"><?php echo $view_user->name; ?><br />
					      						<a href="#"><small><?php echo $view_user->email; ?></small></a>
					      					</h4>
					      				</div><!-- </author> -->
					      				<p class="description text-center">
					      					"I like the way you work it <br>
					      					No diggity <br>
					      					I wanna bag it up"
					      				</p>
					      			</div><!-- <!/content> -->
					      			<hr>
					      			<div class="text-center">
					      				<div class="row">
					      					<div class="col-md-3 col-md-offset-1">
					      						<h5>12<br /><small>Files</small></h5>
					      					</div><!-- </col-md-4 col-md-offset-1> -->
					      					<div class="col-md-4">
					      						<h5>2GB<br /><small>Used</small></h5>
					      					</div><!-- </col-md-4> -->
					      					<div class="col-md-3">
					      						<h5>24,6$<br /><small>Spent</small></h5>
					      					</div><!-- </col-md-3> --> 
					      				</div><!-- </row> -->
					      			</div><!-- </text-center> -->
					      		</div><!-- </card card-user> -->
					      		<div class="card">
					      			<div class="header">
					      				<h4 class="title">Social Media</h4>
					      			</div><!-- </header> -->
					      			<div class="content">
					      				<ul class="list-unstyled team-members">
					      					<li>
					      						<div class="row">
					      							<div class="col-xs-3">
															<div class="pull-left icone-fa icone-fa-card text-center">
																<i class="fa fa-linkedin"></i>
															</div>
					      							</div>
					      							<div class="col-xs-9">
					      								in/<?php echo $view_user->network->linkedin; ?>
					      								<br />
					      								<span class="text-muted"><small>Offline</small></span>
					      							</div>
					      						</div>
					      					</li>
					      					<li>
					      						<div class="row">
					      							<div class="col-xs-3">
															<div class="pull-left icone-fa icone-fa-card text-center">
																<i class="fa fa-facebook"></i>
															</div>
					      							</div>
					      							<div class="col-xs-9">
					      								facebook.com/<?php echo $view_user->network->facebook; ?>
					      								<br />
					      								<span class="text-success"><small>Available</small></span>
					      							</div>
					      						</div>
					      					</li>
					      					<li>
					      						<div class="row">
					      							<div class="col-xs-3">
															<div class="pull-left icone-fa icone-fa-card text-center">
																<i class="fa fa-twitter"></i>
															</div>
					      							</div>
					      							<div class="col-xs-9">
					      								@<?php echo $view_user->network->twitter; ?>
					      								<br />
					      								<span class="text-danger"><small>Busy</small></span>
					      							</div><!-- </col-xs-9> -->
					      						</div><!-- </row> -->
					      					</li><!-- </li> -->
					      				</ul><!-- </list-unstyled team-members> -->
					      			</div><!-- </content> -->
					      		</div><!-- </card> -->
					         </div><!-- <col-lg-4 col-md-5 -->
					         <div class="col-lg-8 col-md-7">
					         	<div class="card">
					         		<div class="header">
					         			<h4 class="title">Questionário Microsoft</h4>
					         		</div>
					         		<div class="content">
											<form action="<?php echo BASE; ?>upquestionario/editar/" method="post" id="editquiz-form" class="editquiz-form">					         			
					         				<div class="row">
					         					<div class="col-md-3">
					         						<div class="form-group">
					         							<label>Username</label>
					         							<input type="text" class="form-control border-input" disabled placeholder="Company" value="<?php echo $view_user->name;  ?>">
					         						</div><!-- </form-group> -->
					         					</div><!-- </col-md-5> --> 
					         					<div class="col-md-4">
					         						<div class="form-group">
					         							<label for="exampleInputEmail1">Email address</label>
					         							<input type="email" class="form-control border-input" disabled placeholder="Email" value="<?php echo $view_user->email; ?>">
					         						</div><!-- </form-group> -->
					         					</div><!-- </col-md-3> -->
					         				</div><!-- </row> 1º Linha do formulario -->
			         						<div class="questions">
			         							<!--
			         								1º Pergunta Questionário
			         							-->
			         							<div class="row">
						         					<div class="col-md-12 linha_branca">
						         						<div class="form-group">
																<div class="row">
																	<div class="col-md-12">
																		<label class="label_impar">1) Qual seu nível de Inglês?</label>
																		<label>
																			<?php echo $view_reply->question_1; ?>
																			<?php echo $view_user->name; ?>
																		</label>
																	</div>
																</div>
																<div class="row">
																	<div class="col-md-3">
																		<input type="radio" class="valida_teste" value="1" <?php echo ($view_reply->question_1 == "1") ? "checked" : null; ?> id="radio01" name="question_1" />
																		<label for="radio01"><span></span>Leitura, Escrita e Conversação  </label>
																	</div>

																	<div class="col-md-3">
																		<input type="radio" class="valida_teste" value="2" <?php echo ($view_reply->question_1 == "2") ? "checked" : null; ?> id="radio02" name="question_1" />
																		<label for="radio02"><span></span>Leitura e Escrita  </label>	
																	</div>												
																	<div class="col-md-2">
																		<input type="radio" class="valida_teste" value="3" <?php echo ($view_reply->question_1 == "3") ? "checked" : null; ?> id="radio03" name="question_1" />
																		<label for="radio03"><span></span>Escrita   </label>	
																	</div>												
																	<div class="col-md-2">
																		<input type="radio" class="valida_teste" value="4" <?php echo ($view_reply->question_1 == "4") ? "checked" : null; ?> id="radio04" name="question_1" />
																		<label for="radio04"><span></span>Leitura   </label>	
																	</div>
																	<div class="col-md-2">
																		<input type="radio" class="valida_teste" value="5" <?php echo ($view_reply->question_1 == "5") ? "checked" : null; ?> id="radio05" name="question_1" />
																		<label for="radio05"><span></span>Não possui</label>	
																	</div>
																</div>
						         						</div><!-- </form-group> -->
						         					</div><!-- </col-md-4> -->
						         				</div><!-- </row> 1º Pergunta Questionário-->
			         							<!--
			         								2º Pergunta Questionário
			         							-->
			         							<div class="row">
						         					<div class="col-md-12 linha_cinza">
						         						<div class="form-group">
																<div class="row">
																	<div class="col-md-12">
																		<label class="label_par">2) Quantos anos de eperiência na área de tecnologia?</label>
																	</div>
																</div>
																<div class="row">
																	<div class="col-md-2">
																		<input type="radio" class="valida_teste" value="1" <?php echo ($view_reply->question_2 == "1") ? "checked" : null; ?> id="radio06" name="question_2" />
																		<label for="radio06"><span></span>+ 8 anos</label>
																	</div>

																	<div class="col-md-3">
																		<input type="radio" class="valida_teste" value="2" <?php echo ($view_reply->question_2 == "2") ? "checked" : null; ?> id="radio07" name="question_2" />
																		<label for="radio07"><span></span>Entre 5 e 8 anos</label>	
																	</div>												

																	<div class="col-md-2">
																		<input type="radio" class="valida_teste" value="3" <?php echo ($view_reply->question_2 == "3") ? "checked" : null; ?> id="radio08" name="question_2" />
																		<label for="radio08"><span></span>Entre 3 e 5 anos</label>	
																	</div>												
																	<div class="col-md-2">
																		<input type="radio" class="valida_teste" value="4" <?php echo ($view_reply->question_2 == "4") ? "checked" : null; ?> id="radio09" name="question_2" />
																		<label for="radio09"><span></span>Entre 1 e 3 anos </label>	
																	</div>

																	<div class="col-md-2">
																		<input type="radio" class="valida_teste" value="5" <?php echo ($view_reply->question_2 == "5") ? "checked" : null; ?> id="radio10" name="question_2" />
																		<label for="radio10"><span></span>- 1 ano</label>	
																	</div>
																</div>
						         						</div><!-- </form-group> -->
						         					</div><!-- </col-md-4> -->
						         				</div><!-- </row> 2º Pergunta Questionário-->
			         							<!--
			         								3º Pergunta Questionário
			         							-->
			         							<div class="row">
						         					<div class="col-md-12 linha_branca">
						         						<div class="form-group">
																<div class="row">
																	<div class="col-md-12">
																		<label class="label_par">3) Possui Certificação Oficial Microsoft?</label>
																	</div>
																</div>
																<div class="row">
																	<div class="col-md-2">
																		<input type="radio" class="valida_teste" value="1" <?php echo ($view_reply->question_3 == "1") ? "checked" : null; ?> id="radio11" name="question_3" />
																		<label for="radio11"><span></span>MCSE</label>
																	</div>

																	<div class="col-md-3">
																		<input type="radio" class="valida_teste" value="2" <?php echo ($view_reply->question_3 == "2") ? "checked" : null; ?> id="radio12" name="question_3" />
																		<label for="radio12"><span></span>MCSA</label>	
																	</div>												
																	<div class="col-md-2">
																		<input type="radio" class="valida_teste" value="3" <?php echo ($view_reply->question_3 == "3") ? "checked" : null; ?> id="radio13" name="question_3" />
																		<label for="radio13"><span></span>MCTIP</label>	
																	</div>												
																	<div class="col-md-2">
																		<input type="radio" class="valida_teste" value="4" <?php echo ($view_reply->question_3 == "4") ? "checked" : null; ?> id="radio14" name="question_3" />
																		<label for="radio14"><span></span>MCT</label>	
																	</div>

																	<div class="col-md-2">
																		<input type="radio" class="valida_teste" value="5" <?php echo ($view_reply->question_3 == "5") ? "checked" : null; ?> id="radio15" name="question_3" />
																		<label for="radio15"><span></span>MCP</label>	
																	</div>
																</div>
						         						</div><!-- </form-group> -->
						         					</div><!-- </col-md-4> -->
						         				</div><!-- </row> 3º Pergunta Questionário-->
			         							<!--
			         								4º Pergunta Questionário
			         							-->
			         							<div class="row">
						         					<div class="col-md-12 linha_cinza">
						         						<div class="form-group">
																<div class="row">
																	<div class="col-md-12">
																		<label class="label_par">4) Qual seu Nível Formação Acadêmica?</label>
																	</div>
																</div>
																<div class="row">
																	<div class="col-md-3">
																		<input type="radio" class="valida_teste" value="1" <?php echo ($view_reply->question_4 == "1") ? "checked" : null; ?> id="radio16" name="question_4" />
																		<label for="radio16"><span></span>Bacharel</label>
																	</div>

																	<div class="col-md-3">
																		<input type="radio" class="valida_teste" value="2" <?php echo ($view_reply->question_4 == "2") ? "checked" : null; ?> id="radio17" name="question_4" />
																		<label for="radio17"><span></span>Tecnólogo</label>	
																	</div>												
																	<div class="col-md-2">
																		<input type="radio" class="valida_teste" value="3" <?php echo ($view_reply->question_4 == "3") ? "checked" : null; ?> id="radio18" name="question_4" />
																		<label for="radio18"><span></span>Técnico</label>	
																	</div>												
																	<div class="col-md-2">
																		<input type="radio" class="valida_teste" value="4" <?php echo ($view_reply->question_4 == "4") ? "checked" : null; ?> id="radio19" name="question_4" />
																		<label for="radio19"><span></span>Médio</label>	
																	</div>

																	<div class="col-md-2">
																		<input type="radio" class="valida_teste" value="5" <?php echo ($view_reply->question_4 == "5") ? "checked" : null; ?> id="radio20" name="question_4" />
																		<label for="radio20"><span></span>Primário</label>	
																	</div>
																</div>
						         						</div><!-- </form-group> -->
						         					</div><!-- </col-md-4> -->
						         				</div><!-- </row> 4º Pergunta Questionário-->
													<!--
			         								5º Pergunta Questionário
			         							-->
			         							<div class="row">
						         					<div class="col-md-12 linha_branca">
						         						<div class="form-group">
																<div class="row">
																	<div class="col-md-12">
																		<label class="label_impar">5) Situação Acadêmica?</label>
																	</div>
																</div>
																<div class="row">
																	<div class="col-md-4">
																		<input type="radio" class="valida_teste" value="1" <?php echo ($view_reply->question_5 == "1") ? "checked" : null; ?> id="radio21" name="question_5" />
																		<label for="radio21"><span></span>Completo</label>
																	</div>

																	<div class="col-md-4">
																		<input type="radio" class="valida_teste" value="2" <?php echo ($view_reply->question_5 == "2") ? "checked" : null; ?> id="radio22" name="question_5" />
																		<label for="radio22"><span></span>Cursando</label>	
																	</div>												
																	<div class="col-md-4">
																		<input type="radio" class="valida_teste" value="3" <?php echo ($view_reply->question_5 == "3") ? "checked" : null; ?> id="radio23" name="question_5" />
																		<label for="radio23"><span></span>Incompleto</label>	
																	</div>												
																</div>
						         						</div><!-- </form-group> -->
						         					</div><!-- </col-md-4> -->
						         				</div><!-- </row> 5º Pergunta Questionário-->
			         							<!--
			         								6º Pergunta Questionário
			         							-->
			         							<div class="row">
						         					<div class="col-md-12 linha_cinza">
						         						<div class="form-group">
																<div class="row">
																	<div class="col-md-12">
																		<label class="label_par">6) Possui algum Nível de Pós Graduação?</label>
																	</div>
																</div>
																<div class="row">
																	<div class="col-md-2">
																		<input type="radio" class="valida_teste" value="1" <?php echo ($view_reply->question_6 == "1") ? "checked" : null; ?> id="radio24" name="question_6" />
																		<label for="radio24"><span></span>PHD</label>
																	</div>

																	<div class="col-md-3">
																		<input type="radio" class="valida_teste" value="2" <?php echo ($view_reply->question_6 == "2") ? "checked" : null; ?> id="radio25" name="question_6" />
																		<label for="radio25"><span></span>Doutorado</label>	
																	</div>												
																	<div class="col-md-3">
																		<input type="radio" class="valida_teste" value="3" <?php echo ($view_reply->question_6 == "3") ? "checked" : null; ?> id="radio26" name="question_6" />
																		<label for="radio26"><span></span>Mestrado</label>	
																	</div>												
																	<div class="col-md-2">
																		<input type="radio" class="valida_teste" value="4" <?php echo ($view_reply->question_6 == "4") ? "checked" : null; ?> id="radio27" name="question_6" />
																		<label for="radio27"><span></span>MBA</label>	
																	</div>

																	<div class="col-md-2">
																		<input type="radio" class="valida_teste" value="5" <?php echo ($view_reply->question_6 == "5") ? "checked" : null; ?> id="radio28" name="question_6" />
																		<label for="radio28"><span></span>Não Possui</label>	
																	</div>
																</div>
						         						</div><!-- </form-group> -->
						         					</div><!-- </col-md-4> -->
						         				</div><!-- </row> 6º Pergunta Questionário-->
													<!--
			         								7º Pergunta Questionário
			         							-->
			         							<div class="row">
						         					<div class="col-md-12 linha_branca">
						         						<div class="form-group">
																<div class="row">
																	<div class="col-md-12">
																		<label class="label_impar">7) Situação Pós Graduação?</label>
																	</div>
																</div>
																<div class="row">
																	<div class="col-md-3">
																		<input type="radio" class="valida_teste" value="1" <?php echo ($view_reply->question_7 == "1") ? "checked" : null; ?> id="radio29" name="question_7" />
																		<label for="radio29"><span></span>Completo</label>
																	</div>

																	<div class="col-md-3">
																		<input type="radio" class="valida_teste" value="2" <?php echo ($view_reply->question_7 == "2") ? "checked" : null; ?> id="radio30" name="question_7" />
																		<label for="radio30"><span></span>Cursando</label>	
																	</div>												
																	<div class="col-md-3">
																		<input type="radio" class="valida_teste" value="3" <?php echo ($view_reply->question_7 == "3") ? "checked" : null; ?> id="radio31" name="question_7" />
																		<label for="radio31"><span></span>Incompleto</label>	
																	</div>

																	<div class="col-md-3">
																		<input type="radio" class="valida_teste" value="4" <?php echo ($view_reply->question_7 == "4") ? "checked" : null; ?> id="radio32" name="question_7" />
																		<label for="radio32"><span></span>Não Iniciado</label>	
																	</div>				
																</div>
						         						</div><!-- </form-group> -->
						         					</div><!-- </col-md-4> -->
						         				</div><!-- </row> 7º Pergunta Questionário-->
			         							<!--
			         								8º Pergunta Questionário
			         							-->
			         							<div class="row">
						         					<div class="col-md-12 linha_cinza">
						         						<div class="form-group">
																<div class="row">
																	<div class="col-md-12">
																		<label class="label_par">8) Conhecimento em Dominio Microsoft?</label>
																	</div>
																</div>
																<div class="row">
																	<div class="col-md-2">
																		<input type="radio" class="valida_teste" value="1" <?php echo ($view_reply->question_8 == "1") ? "checked" : null; ?> id="radio33" name="question_8" />
																		<label for="radio33"><span></span>Design Florestas</label>
																	</div>

																	<div class="col-md-3">
																		<input type="radio" class="valida_teste" value="2" <?php echo ($view_reply->question_8 == "2") ? "checked" : null; ?> id="radio34" name="question_8" />
																		<label for="radio34"><span></span>Arquiteto de Dominio</label>	
																	</div>												
																	<div class="col-md-3">
																		<input type="radio" class="valida_teste" value="3" <?php echo ($view_reply->question_8 == "3") ? "checked" : null; ?> id="radio35" name="question_8" />
																		<label for="radio35"><span></span>Administrador</label>	
																	</div>												
																	<div class="col-md-2">
																		<input type="radio" class="valida_teste" value="4" <?php echo ($view_reply->question_8 == "4") ? "checked" : null; ?> id="radio36" name="question_8" />
																		<label for="radio36"><span></span>Operador</label>	
																	</div>

																	<div class="col-md-2">
																		<input type="radio" class="valida_teste" value="5" <?php echo ($view_reply->question_8 == "5") ? "checked" : null; ?> id="radio37" name="question_8" />
																		<label for="radio37"><span></span>Cliente</label>	
																	</div>
																</div>
						         						</div><!-- </form-group> -->
						         					</div><!-- </col-md-4> -->
						         				</div><!-- </row> 8º Pergunta Questionário-->
			         							<!--
			         								9º Pergunta Questionário
			         							-->
			         							<div class="row">
						         					<div class="col-md-12 linha_branca">
						         						<div class="form-group">
																<div class="row">
																	<div class="col-md-12">
																		<label class="label_par">9) Nível de conhecimento Microsoft Exchange?</label>
																	</div>
																</div>
																<div class="row">
																	<div class="col-md-2">
																		<input type="radio" class="valida_teste" value="1" <?php echo ($view_reply->question_9 == "1") ? "checked" : null; ?> id="radio38" name="question_9" />
																		<label for="radio38"><span></span>Projetista</label>
																	</div>

																	<div class="col-md-3">
																		<input type="radio" class="valida_teste" value="2" <?php echo ($view_reply->question_9 == "2") ? "checked" : null; ?> id="radio39" name="question_9" />
																		<label for="radio39"><span></span>Administrador</label>	
																	</div>												
																	<div class="col-md-2">
																		<input type="radio" class="valida_teste" value="3" <?php echo ($view_reply->question_9 == "3") ? "checked" : null; ?> id="radio40" name="question_9" />
																		<label for="radio40"><span></span>Operador</label>	
																	</div>												
																	<div class="col-md-2">
																		<input type="radio" class="valida_teste" value="4" <?php echo ($view_reply->question_9 == "4") ? "checked" : null; ?> id="radio41" name="question_9" />
																		<label for="radio41"><span></span>Cliente</label>	
																	</div>

																</div>
						         						</div><!-- </form-group> -->
						         					</div><!-- </col-md-4> -->
						         				</div><!-- </row> 9º Pergunta Questionário-->
			         							<!--
			         								10º Pergunta Questionário
			         							-->
			         							<div class="row">
						         					<div class="col-md-12 linha_cinza">
						         						<div class="form-group">
																<div class="row">
																	<div class="col-md-12">
																		<label class="label_par">10) Conhecimento em Virtualização?</label>
																	</div>
																</div>
																<div class="row">
																	<div class="col-md-4">
																		<input type="radio" class="valida_teste" value="1" <?php echo ($view_reply->question_10 == "1") ? "checked" : null; ?> id="radio42" name="question_10" />
																		<label for="radio42"><span></span>Profissional Certificado</label>
																	</div>

																	<div class="col-md-3">
																		<input type="radio" class="valida_teste" value="2" <?php echo ($view_reply->question_10 == "2") ? "checked" : null; ?> id="radio43" name="question_10" />
																		<label for="radio43"><span></span>Avançado</label>	
																	</div>												
																	<div class="col-md-3">
																		<input type="radio" class="valida_teste" value="3" <?php echo ($view_reply->question_10 == "3") ? "checked" : null; ?> id="radio44" name="question_10" />
																		<label for="radio44"><span></span>Intermediário</label>	
																	</div>												
																	<div class="col-md-2">
																		<input type="radio" class="valida_teste" value="4" <?php echo ($view_reply->question_10 == "4") ? "checked" : null; ?> id="radio45" name="question_10" />
																		<label for="radio45"><span></span>Básico</label>	
																	</div>
																</div>
						         						</div><!-- </form-group> -->
						         					</div><!-- </col-md-4> -->
						         				</div><!-- </row> 10º Pergunta Questionário-->
													<!--
			         								11º Pergunta Questionário
			         							-->
			         							<div class="row">
						         					<div class="col-md-12 linha_branca">
						         						<div class="form-group">
																<div class="row">
																	<div class="col-md-12">
																		<label class="label_impar">11) Conhecimento em Roteadores?</label>
																	</div>
																</div>
																<div class="row">
																	<div class="col-md-4">
																		<input type="radio" class="valida_teste" value="1" <?php echo ($view_reply->question_11 == "1") ? "checked" : null; ?> id="radio46" name="question_11" />
																		<label for="radio46"><span></span>Profissional Certificado</label>
																	</div>

																	<div class="col-md-3">
																		<input type="radio" class="valida_teste" value="2" <?php echo ($view_reply->question_11 == "2") ? "checked" : null; ?> id="radio47" name="question_11" />
																		<label for="radio47"><span></span>Avançado</label>	
																	</div>												
																	<div class="col-md-3">
																		<input type="radio" class="valida_teste" value="3" <?php echo ($view_reply->question_11 == "3") ? "checked" : null; ?> id="radio48" name="question_11" />
																		<label for="radio48"><span></span>Intermediário</label>	
																	</div>																								<div class="col-md-2">
																		<input type="radio" class="valida_teste" value="4" <?php echo ($view_reply->question_11 == "4") ? "checked" : null; ?> id="radio49" name="question_11" />
																		<label for="radio49"><span></span>Básico</label>	
																	</div>	
																</div>
						         						</div><!-- </form-group> -->
						         					</div><!-- </col-md-4> -->
						         				</div><!-- </row> 11º Pergunta Questionário-->
			         							<!--
			         								12º Pergunta Questionário
			         							-->
			         							<div class="row">
						         					<div class="col-md-12 linha_cinza">
						         						<div class="form-group">
																<div class="row">
																	<div class="col-md-12">
																		<label class="label_par">12) Possui algum Nível de Pós Graduação?</label>
																	</div>
																</div>
																<div class="row">
																	<div class="col-md-2">
																		<input type="radio" class="valida_teste" value="1" <?php echo ($view_reply->question_12 == "1") ? "checked" : null; ?> id="radio50" name="question_12" />
																		<label for="radio50"><span></span>PHD</label>
																	</div>

																	<div class="col-md-3">
																		<input type="radio" class="valida_teste" value="2" <?php echo ($view_reply->question_12 == "2") ? "checked" : null; ?> id="radio51" name="question_12" />
																		<label for="radio51"><span></span>Doutorado</label>	
																	</div>												
																	<div class="col-md-3">
																		<input type="radio" class="valida_teste" value="3" <?php echo ($view_reply->question_12 == "3") ? "checked" : null; ?> id="radio52" name="question_12" />
																		<label for="radio52"><span></span>Mestrado</label>	
																	</div>												
																	<div class="col-md-2">
																		<input type="radio" class="valida_teste" value="4" <?php echo ($view_reply->question_12 == "4") ? "checked" : null; ?> id="radio53" name="question_12" />
																		<label for="radio53"><span></span>MBA</label>	
																	</div>

																	<div class="col-md-2">
																		<input type="radio" class="valida_teste" value="5" <?php echo ($view_reply->question_12 == "5") ? "checked" : null; ?> id="radio54" name="question_12" />
																		<label for="radio54"><span></span>Não Possui</label>	
																	</div>
																</div>
						         						</div><!-- </form-group> -->
						         					</div><!-- </col-md-4> -->
						         				</div><!-- </row> 12º Pergunta Questionário-->
													<!--
			         								13º Pergunta Questionário
			         							-->
			         							<div class="row">
						         					<div class="col-md-12 linha_branca">
						         						<div class="form-group">
																<div class="row">
																	<div class="col-md-12">
																		<label class="label_impar">13) Situação Pós Graduação?</label>
																	</div>
																</div>
																<div class="row">
																	<div class="col-md-3">
																		<input type="radio" class="valida_teste" value="1" <?php echo ($view_reply->question_13 == "1") ? "checked" : null; ?> id="radio55" name="question_13" />
																		<label for="radio55"><span></span>Completo</label>
																	</div>

																	<div class="col-md-3">
																		<input type="radio" class="valida_teste" value="2" <?php echo ($view_reply->question_13 == "2") ? "checked" : null; ?> id="radio56" name="question_13" />
																		<label for="radio56"><span></span>Cursando</label>	
																	</div>												
																	<div class="col-md-3">
																		<input type="radio" class="valida_teste" value="3" <?php echo ($view_reply->question_13 == "3") ? "checked" : null; ?> id="radio57" name="question_13" />
																		<label for="radio57"><span></span>Incompleto</label>	
																	</div>

																	<div class="col-md-3">
																		<input type="radio" class="valida_teste" value="4" <?php echo ($view_reply->question_13 == "4") ? "checked" : null; ?> id="radio58" name="question_13" />
																		<label for="radio58"><span></span>Não Iniciado</label>	
																	</div>	
																</div>
						         						</div><!-- </form-group> -->
						         					</div><!-- </col-md-4> -->
						         				</div><!-- </row> 13º Pergunta Questionário-->
													<!--
			         								14º Pergunta Questionário
			         							-->
			         							<div class="row">
						         					<div class="col-md-12 linha_cinza">
						         						<div class="form-group">
																<div class="row">
																	<div class="col-md-12">
																		<label class="label_par">14) Possui algum Nível de Pós Graduação?</label>
																	</div>
																</div>
																<div class="row">
																	<div class="col-md-2">
																		<input type="radio" class="valida_teste" value="1" id="radio59" name="question_14" />
																		<label for="radio59"><span></span>PHD</label>
																	</div>

																	<div class="col-md-3">
																		<input type="radio" class="valida_teste" value="2" <?php echo ($view_reply->question_14 == "1") ? "checked" : null; ?> id="radio60" name="question_14" />
																		<label for="radio60"><span></span>Doutorado</label>	
																	</div>												
																	<div class="col-md-3">
																		<input type="radio" class="valida_teste" value="3" <?php echo ($view_reply->question_14 == "2") ? "checked" : null; ?> id="radio61" name="question_14" />
																		<label for="radio61"><span></span>Mestrado</label>	
																	</div>												
																	<div class="col-md-2">
																		<input type="radio" class="valida_teste" value="4" <?php echo ($view_reply->question_14 == "3") ? "checked" : null; ?> id="radio62" name="question_14" />
																		<label for="radio62"><span></span>MBA</label>	
																	</div>

																	<div class="col-md-2">
																		<input type="radio" class="valida_teste" value="5" <?php echo ($view_reply->question_14 == "4") ? "checked" : null; ?> id="radio63" name="question_14" />
																		<label for="radio63"><span></span>Não Possui</label>	
																	</div>
																</div>
						         						</div><!-- </form-group> -->
						         					</div><!-- </col-md-4> -->
						         				</div><!-- </row> 14º Pergunta Questionário-->
													<!--
			         								15º Pergunta Questionário
			         							-->
			         							<div class="row">
						         					<div class="col-md-12 linha_branca">
						         						<div class="form-group">
																<div class="row">
																	<div class="col-md-12">
																		<label class="label_impar">15) Situação Pós Graduação?</label>
																	</div>
																</div>
																<div class="row">
																	<div class="col-md-3">
																		<input type="radio" class="valida_teste" value="1" <?php echo ($view_reply->question_15 == "1") ? "checked" : null; ?> id="radio64" name="question_15" />
																		<label for="radio64"><span></span>Completo</label>
																	</div>

																	<div class="col-md-3">
																		<input type="radio" class="valida_teste" value="2" <?php echo ($view_reply->question_15 == "2") ? "checked" : null; ?> id="radio65" name="question_15" />
																		<label for="radio65"><span></span>Cursando</label>	
																	</div>												
																	<div class="col-md-3">
																		<input type="radio" class="valida_teste" value="3" <?php echo ($view_reply->question_15 == "3") ? "checked" : null; ?> id="radio66" name="question_15" />
																		<label for="radio66"><span></span>Incompleto</label>	
																	</div>

																	<div class="col-md-3">
																		<input type="radio" class="valida_teste" value="4" <?php echo ($view_reply->question_15 == "4") ? "checked" : null; ?> id="radio67" name="question_15" />
																		<label for="radio67"><span></span>Não Iniciado</label>	
																	</div>		
																</div>
						         						</div><!-- </form-group> -->
						         					</div><!-- </col-md-4> -->
						         				</div><!-- </row> 15º Pergunta Questionário-->						         								
												</div><!-- </questions> -->
				         					<div class="md-padder text-center">
				 									<button type="submit" value="Submit" class="btn btn-primary btn-lg margin-btm-30 btn-send> <i class="fa fa-user"></i> <span class="hidden-xs"> Send </span> Quiz </button>

		                        			<button type="button" class="btn-next">
		                        				<i class="fa fa-arrow-right"></i>
		                        				<span>Next</span>
		                        			</button>

				 								</div>
					         				<div class="clearfix"></div>
					         			</form>
					         		</div><!-- </content> -->
					         	</div>
					         </div>				
					      </div><!-- </row> -->
					   </div><!-- </container-fluid> -->
					</div><!-- </container> -->
				</section>			   			
			</main><!-- </main> Final Corpo de Conteúdo-->		