			<footer>
			<!-- ==============================================
			    Footer (Rodapé)
			    =============================================== -->
				<section class="social-links">
				  <div class="container">
				    <div class="row">
				          <ul>
				            <li> <a href="https://www.facebook.com/profile.php?id=1800765934" target="_blank" title=""> <span> <i class="fa fa-facebook"></i> </span> </a> </li>
				            <li> <a href="https://twitter.com/elisandromello" target="_blank" title=""> <span> <i class="fa fa-twitter"></i> </span> </a> </li>
				            <li> <a href="http://www.linkedin.com/in/elisandromello" target="_blank" title=""> <span> <i class="fa fa-linkedin"></i> </span> </a> </li>
				            <li> <a href="http://www.instagram.com/iamelisandromello" target="_blank" title=""> <span> <i class="fa fa-instagram"></i> </span> </a> </li>
				            <li> <a href="https://github.com/iamelisandromello" target="_blank" title=""> <span> <i class="fa fa-github"></i> </span> </a> </li>
				            <li> <a href="mailto:iam@elisandromello.com.br?subject=Eu tenho um comentário para você..." title=""><span> <i class="fa fa-envelope"></i></span></a></li>
				          </ul>
				    </div><!-- /row -->
				  </div><!-- /container -->
				</section><!-- </social-links> Final Sessão Redes Sociais -->

				<!-- ==============================================
				   Créditos (Credits)
				=============================================== -->
				<section class="copyright">
				  <div class="container">
				    <div class="col-md-12">
				      <div class="text-center">
				        <!-- Logo Header -->
				        <section id="fox_footer" class="fox_footer">
				          <div> <img src="<?php echo IMAGES; ?>logofooter.png" alt="Foxin by Elisandro Mello"> - &copy;<script>document.write(new Date().getFullYear())</script> - Designer coded and designed by  <i class="fa fa-cloud-upload"></i> Elisandro Mello</div>

				        </section>
				        <!--/ Logo Header-->
				      </div>
				    </div><!-- </col-md-12> -->
				  </div><!-- </container> -->
				</section><!-- </copyright> Final Section Copyright -->
			</footer>
			<!-- Back To Top -->
			<a id="back-to-top" href="#">
				<i class="font-icon-arrow-simple-up"></i>
			</a>
			<!-- End Back to Top -->


			<!--==============================================
			Modal User Search (Busca Usuarios)
			===============================================-->
		   <div class="modal fade" id="modal5" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
		    	<div class="modal-dialog">
		    		<div class="modal-content modal-popup">
		    			<div class="modal-header">
		    				<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
		    				<h2 class="modal-title">Teste de Retorno Ajax</h2>
		    			</div>

		    			<div class="row">
		    				<div class="col-md-10 centered">
		    					<div class="modal-containerStep">
		    						<span class="step-num">1</span>
		    						<div class="modal-text">
		    							<span class="hidden-xs">Find users on</span> your network
		    						</div><!-- </modal-text> -->
		    					</div><!-- </modal-containerStep> -->
		    				</div><!-- </col-md-10> -->
		    			</div><!-- </row> -->

						<form action="<?php echo BASE; ?>home/ajax/" id="js-ajax-php-json" method="post" accept-charset="utf-8">
							<input type="text" id="vinho" name="beverage" value="" placeholder="Favorite restaurant" />
							<input type="text" id="restaurante" name="restaurant" value="" placeholder="Favorite beverage" />
							<select name="sexo" id="sexo" >
							<option value="male">Male</option>
							<option value="female">Female</option>
							</select>
							<input type="submit" id="enviar" placeholder="Enviar"  />
							<input type="hidden" id="metodo" value="formulario-ajax">
						</form>

						<div class="row">
							<div class="col-md-8">
								<button type="btn btn-primary" id="validar">Validar</button>
								<ul class="list-users"></ul>
							</div>
						</div>

		    		</div><!-- </modal-content> -->
		    	</div><!-- </modal-dialog> -->
		   </div><!-- </modal> -->

			<!--==============================================
			Modal User Search (Busca Usuarios)
			===============================================-->
		   <div class="modal fade" id="modal3" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
		    	<div class="modal-dialog">
		    		<div class="modal-content modal-popup">
		    			<div class="modal-header">
		    				<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
		    				<h2 class="modal-title">Search System without Refresh</h2>
		    			</div>

		    			<div class="row">
		    				<div class="col-md-10 centered">
		    					<div class="modal-containerStep">
		    						<span class="step-num">1</span>
		    						<div class="modal-text">
		    							<span class="hidden-xs">Find users on</span> your network
		    						</div><!-- </modal-text> -->
		    					</div><!-- </modal-containerStep> -->
		    				</div><!-- </col-md-10> -->
		    			</div><!-- </row> -->

		    			<form action="<?php echo BASE; ?>usuario/pesquisar/" class="form-user clearfix" method="post">
		    				<div class="modal-groupForm">
		    					<div class="grupo-input">
		    						<span class="grupo-input-img"><i class="fa fa-user-plus"></i></span>
									<input class="input-modal" type="text" name="campo" id="campo" placeholder="O que você está procurando?">
		    					</div>
		    				</div><!-- </modal-groupForm> -->

							<div class="col-md-12 text-center">
								<input name="enviar" type="submit" class="form-control" id="submit" value="Pesquisar">
							</div><!-- </col-md-12> -->

		    			</form>
						<?php
							if ($view_users) :
								foreach ($view_users as $user) :
						?>
									<div class="col-md-12 search-user">
										<div class="row">
											<div class="col-md-2">

												<div class="avatar-wrapper">
													<?php
								                  if (!is_null($view_user->image)) {
								                       echo '<img class="avatar-busca wow bounceIn" src="' . BASE . 'public/uploads/users/' . $user->id . '/' . $user->image . '" width="160">';
								                  }
								                  else{
								                       echo '<img class="avatar-busca" src="' . BASE . 'public/uploads/users/' . 'default' . '/' . 'default.png' . '" width="160">';
								                  }
							               	?>
												</div><!-- </> -->
											</div><!-- </> -->
											<div class="col-md-10 ">
												<div class="row">
													<div class="col-md-12 search-name">
														<h5><?php echo $user->name; ?></h5>
													</div>
												</div>
												<div class="row">
													<div class="col-md-12 search-charge">
														<h5><?php echo $view_user->professionals[0]->function; ?></h5>
													</div>
												</div>
											</div><!-- </> -->
										</div><!-- </row> -->

									</div>
						<?php
								endforeach;
							endif;
						?>

		    		</div><!-- </modal-content> -->
		    	</div><!-- </modal-dialog> -->
		   </div><!-- </modal> -->

			<!--==============================================
			Modal Delete (Delete Opportunity )
			===============================================-->
		   <div class="modal fade" id="modal1" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
		    	<div class="modal-dialog">
		    		<div class="modal-content modal-popup">
		    			<div class="modal-header">
		    				<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
		    				<h2 class="modal-title">Gerenciamneto de Oportunidade</h2>
		    			</div>

		    			<div class="row">
		    				<div class="col-md-10 centered">
		    					<div class="modal-containerStep">
		    						<span class="step-num">1</span>
		    						<div class="modal-text">
		    							<span class="hidden-xs">Sobre </span> Oportunidade
		    						</div>
		    					</div>
		    				</div>
		    			</div>

		    			<form action="#" method="post">
		    				<div class="modal-groupForm">
		    					<div class="grupo-input">
		    						<span class="grupo-input-img"><i class="fa fa-user-plus"></i></span>
		    						<input type="text" name="comment" class="input-modal" placeholder="Ex. Analista Jr" >
		    					</div>
		    				</div>

							<div class="modal-groupForm">
								<textarea class="textarea-modal" rows="5" placeholder="Describe the job opportunity assignments"></textarea>
							</div>

							<div class="col-md-12 text-center">
								<input name="submit" type="submit" class="form-control" id="submit" value="Delete">
							</div>

		    			</form>
		    		</div><!-- </modal-content> -->
		    	</div><!-- </modal-dialog> -->
		   </div><!-- </modal> -->

			<!--==============================================
			Modal Add Opportunitty (Add Nova Oportunidade )
			===============================================-->
		   <div class="modal fade" id="modal10" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
		    	<div class="modal-dialog modal-lg">
		    		<div class="modal-content modal-popup">
		    			<div class="modal-header">
		    				<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
		    				<h2 class="modal-title">Inclusão de Oportunidade</h2>
		    			</div>

						<div class="row">
		    				<div class="col-md-10 centered">
		    					<div class="modal-containerStep">
		    						<span class="step-num">1</span>
		    						<div class="modal-text">
										Perfil da Vaga
		    						</div>
		    					</div>
		    				</div>
		    			</div>

	    				<div class="modal-groupForm">
	    					<div class="row">
	    						<div class="col-md-10 centered">
		    						<div class="col-md-4">
		    							<input type="radio" value="1" name="checkboxProfile" id="checkboxSenior" class="css-radiobox senior" checked="checked" />
										<label for="checkboxSenior" class="css-label">Sênior</label>
		    						</div>

		    						<div class="col-md-4">
										<input type="radio" value="2" name="checkboxProfile" id="checkboxPleno" class="css-radiobox pleno" />
										<label for="checkboxPleno" class="css-label">Pleno</label>
		    						</div>

		    						<div class="col-md-4">
	    								<input type="radio" value="3" name="checkboxProfile" id="checkboxJunior" class="css-radiobox	junior" />
										<label for="checkboxJunior" class="css-label">Júnior</label>
		    						</div>
	    						</div><!--</col-md-10 centered>-->
	    					</div><!--</row>-->
	    				</div><!-- </modal-groupForm>-->
		    			<!-- =================================
						Formulario de Inclusão de Oportunidade
						Pelo Usuario
		    			===================================-->
		    			<form class="registration-charge" id="registration-charge" action="<?php echo BASE; ?>home/cadastrarvaga/" method="post" />

							<div class="row">
			    				<div class="col-md-10 centered">
			    					<div class="modal-containerStep">
			    						<span class="step-num">2</span>
			    						<div class="modal-text">
			    							Requirementos
			    						</div>
			    					</div>
			    				</div>
			    			</div>
							<div class="containerRequerimento">
				    			<div class="row">
				    				<div class="col-xs-12 col-sm-6 col-md-3 col-lg-3 col-xl-3">
				    					<!-- Seleção de Funções -->
										<label for="requerimentoFormacao">Formação</label>
										<select name="attribute_1" id="requerimentoFormacao" class="select-modal selectpicker" >
											<option value="1">
												Bacharel
											</option>
											<option value="2">
												Tecnólogo
											</option>
											<option value="3">
												Técnico
											</option>
											<option value="4">
												Médio
											</option>
											<option value="5">
												Primário
											</option>
										</select>
				    				</div>
				    				<div class="col-xs-12 col-sm-6 col-md-3 col-lg-3 col-xl-3">
				    					<!-- Seleção de Funções -->
										<label for="requerimentoStatusF">Situação Acadêmica</label>
										<select name="attribute_2" id="requerimentoStatusF" class="select-modal selectpicker" >
											<option value="1">
												Completo
											</option>
											<option value="2">
												Cursando
											</option>
											<option value="3">
												Trancado
											</option>
										</select>
				    				</div>
				    				<div class="col-xs-12 col-sm-6 col-md-3 col-lg-3 col-xl-3">
				    					<!-- Seleção de Funções -->
										<label for="requerimentoPos">Pós Graduação</label>
										<select name="attribute_3" id="requerimentoPos" class="select-modal selectpicker" >
											<option value="1">
												PHD
											</option>
											<option value="2">
												Doutorado
											</option>
											<option value="3">
												Mestrado
											</option>
											<option value="4">
												MBA
											</option>
											<option value="5">
												Não Possui
											</option>
										</select>
				    				</div>
				    				<div class="col-xs-12 col-sm-6 col-md-3 col-lg-3 col-xl-3">
				    					<!-- Seleção de Funções -->
										<label for="requerimentoStatusP">Situação Pós</label>
										<select name="attribute_4" id="requerimentoStatusP" class="select-modal selectpicker" >
											<option value="1">
												Completo
											</option>
											<option value="2">
												Cursando
											</option>
											<option value="3">
												Trancado
											</option>
											<option value="4">
												Não Iniciado
											</option>
										</select>
				    				</div>
				    			</div><!-- <row> -->
								<!-- 2º Linha de Requerimentos Vaga-->
				    			<div class="row">
				    				<div class="col-xs-12 col-sm-6 col-md-3 col-lg-3 col-xl-3">
				    					<!-- Seleção de Funções -->
										<label for="requerimentoInglês">Inglês</label>
										<select name="attribute_5" id="requerimentoInglês" class="select-modal selectpicker" >
											<option value="1">
												Fluente
											</option>
											<option value="2">
												Leitura e Escrita
											</option>
											<option value="3">
												Leitura
											</option>
											<option value="4">
												Não Possui
											</option>
										</select>
				    				</div>
				    				<div class="col-xs-12 col-sm-6 col-md-3 col-lg-3 col-xl-3">
				    					<!-- Seleção de Funções -->
										<label for="requerimentoExperiencia">Experiência</label>
										<select name="attribute_6" id="requerimentoExperiencia" class="select-modal selectpicker" >
											<option value="1">
												+ de 8 anos
											</option>
											<option value="2">
												Entre 5 e 8 anos
											</option>
											<option value="3">
												Entre 3 e 5 anos
											</option>
											<option value="4">
												Entre 1 e 3 anos
											</option>
											<option value="5">
												- de 1 ano
											</option>
										</select>
				    				</div>
				    				<div class="col-xs-12 col-sm-6 col-md-3 col-lg-3 col-xl-3">
				    					<!-- Seleção de Funções -->
										<label for="requerimentoCertificacao">Certificação</label>
										<select name="attribute_7" id="requerimentoCertificacao" class="select-modal selectpicker" >
											<option value="1">
												MCSE
											</option>
											<option value="2">
												MCSA
											</option>
											<option value="3">
												MCTIP
											</option>
											<option value="4">
												MCT
											</option>
											<option value="5">
												MCP
											</option>
										</select>
				    				</div>
				    				<div class="col-xs-12 col-sm-6 col-md-3 col-lg-3 col-xl-3">
				    					<!-- Seleção de Funções -->
										<label for="requerimentoDominio">Domínio</label>
										<select name="attribute_8" id="requerimentoDominio" class="select-modal selectpicker" >
											<option value="1">
												Design de Florestas
											</option>
											<option value="2">
												Arquiteto de Domínio
											</option>
											<option value="3">
												Administrador
											</option>
											<option value="4">
												Operador
											</option>
											<option value="5">
												Cliente
											</option>
										</select>
				    				</div>
				    			</div>

								<!-- 3º Linha de Requerimentos Vaga-->
				    			<div class="row">
				    				<div class="col-xs-12 col-sm-6 col-md-3 col-lg-3 col-xl-3">
				    					<!-- Seleção de Funções -->
										<label for="requerimentoExchange">Microsoft Exchange</label>
										<select name="attribute_9=" id="requerimentoExchange" class="select-modal selectpicker" >
											<option value="1">
												Projetista
											</option>
											<option value="2">
												Administrador
											</option>
											<option value="3">
												Operador
											</option>
											<option value="4">
												Cliente
											</option>
										</select>
				    				</div>
				    				<div class="col-xs-12 col-sm-6 col-md-3 col-lg-3 col-xl-3">
				    					<!-- Seleção de Funções -->
										<label for="requerimentoVirtualizacao">Virtualização</label>
										<select name="attribute_10" id="requerimentoVirtualizacao" class="select-modal selectpicker" >
											<option value="1">
												Profissional Certificado
											</option>
											<option value="2">
												Avançado
											</option>
											<option value="3">
												Intermediário
											</option>
											<option value="4">
												Básico
											</option>
										</select>
				    				</div>
				    				<div class="col-xs-12 col-sm-6 col-md-3 col-lg-3 col-xl-3">
				    					<!-- Seleção de Funções -->
										<label for="requerimentoRoteadores">Roteadores</label>
										<select name="attribute_11" id="requerimentoRoteadores" class="select-modal selectpicker" >
											<option value="1">
												Profissional Certificado
											</option>
											<option value="2">
												Avançado
											</option>
											<option value="3">
												Intermediário
											</option>
											<option value="4">
												Básico
											</option>
										</select>
				    				</div>
				    				<div class="col-xs-12 col-sm-6 col-md-3 col-lg-3 col-xl-3">
				    					<!-- Seleção de Funções -->
										<label for="requerimentoItil">ITIL</label>
										<select name="attribute_12" id="requerimentoItil" class="select-modal selectpicker" >
											<option value="1">
												Certificação Master
											</option>
											<option value="2">
												Profissional Certificado
											</option>
											<option value="3">
												Cursos ITIL
											</option>
											<option value="4">
												Conhecimento dos Processos
											</option>
											<option value="5">
												Não Possui
											</option>
										</select>
				    				</div>
				    			</div>
								<!-- 4º Linha de Requerimentos Vaga-->
				    			<div class="row">
				    				<div class="col-xs-12 col-sm-6 col-md-3 col-lg-3 col-xl-3">
				    					<!-- Seleção de Funções -->
										<label for="requerimentoAgile">Agile</label>
										<select name="attribute_13" id="requerimentoAgile" class="select-modal selectpicker" >
											<option value="1">
												Certificação
											</option>
											<option value="2">
												Cursos Scrum
											</option>
											<option value="3">
												Experiência de Execução
											</option>
											<option value="4">
												Não Possui
											</option>
										</select>
				    				</div>
				    				<div class="col-xs-12 col-sm-6 col-md-3 col-lg-3 col-xl-3">
				    					<!-- Seleção de Funções -->
										<label for="requerimentoProjetos">Projetos</label>
										<select name="attribute_14" id="requerimentoProjetos" class="select-modal selectpicker" >
											<option value="1">
												Certificação PMP
											</option>
											<option value="2">
												Cursos PMP
											</option>
											<option value="3">
												Experiência de Execução
											</option>
											<option value="4">
												Não Possui
											</option>
										</select>
				    				</div>
				    				<div class="col-xs-12 col-sm-6 col-md-3 col-lg-3 col-xl-3">
				    					<!-- Seleção de Funções -->
										<label for="requerimentoHabilitacao">Carteira de Habilitação</label>
										<select name="attribute_15" id="requerimentoHabilitacao" class="select-modal selectpicker" >
											<option value="1">
												+ de 5 anos
											</option>
											<option value="2">
												Entre 2 e 3 anos
											</option>
											<option value="3">
												Provisória
											</option>
											<option value="4">
												Não Possui
											</option>
										</select>
				    				</div>
				    			</div>
							</div><!-- </containerRequerimento>-->
							<div class="row">
			    				<div class="col-md-10 centered">
			    					<div class="modal-containerStep">
			    						<span class="step-num">3</span>
			    						<div class="modal-text">
			    							Beneficíos Adicionais
			    						</div>
			    					</div>
			    				</div>
			    			</div>

			    			<div class="row">
			    				<div class="col-md-12 col-sm-12 col-xs-12">
									<div class="containerBeneficios">
										<div class="row">
											<div class="col-md-3 col-sm-6 col-xs-12">
												<input type="checkbox" name="transport" id="checkbox-bnf08" class="css-checkbox" checked="checked" />
												<label for="checkbox-bnf08" class="css-label">Vale Transporte</label>
											</div>
											<div class="col-md-3 col-sm-6 col-xs-12 ">
												<input type="checkbox" name="health" id="checkbox-bnf01" class="css-checkbox" checked="checked" />
												<label for="checkbox-bnf01" class="css-label">Plano de Saúde</label>
											</div>
											<div class="col-md-3 col-sm-6 col-xs-12">
												<input type="checkbox" name="dental" id="checkbox-bnf02" class="css-checkbox" />
												<label for="checkbox-bnf02" class="css-label">Plano Dental</label>
											</div>
											<div class="col-md-3 col-sm-6 col-xs-12 ">
												<input type="checkbox" name="feeding" id="checkbox-bnf05" class="css-checkbox" />
												<label for="checkbox-bnf05" class="css-label">Vale Alimentação</label>
											</div>
										</div><!-- </row> -->
										<div class="row">
											<div class="col-md-3 col-sm-6 col-xs-12">
												<input type="checkbox" name="meal" id="checkbox-bnf06" class="css-checkbox" checked="checked" />
												<label for="checkbox-bnf06" class="css-label">Vale Refeição</label>
											</div>
											<div class="col-md-3 col-sm-6 col-xs-12">
												<input type="checkbox" name="fuel" id="checkbox-bnf03" class="css-checkbox" />
												<label for="checkbox-bnf03" class="css-label">Ajuda Combustível</label>
											</div>
											<div class="col-md-3 col-sm-6 col-xs-12">
												<input type="checkbox" name="foresight" id="checkbox-bnf07" class="css-checkbox" />
												<label for="checkbox-bnf07" class="css-label">Previdência Privada</label>
											</div>
											<div class="col-md-3 col-sm-6 col-xs-12">
												<input type="checkbox" name="parking" id="checkbox-bnf04" class="css-checkbox" />
												<label for="checkbox-bnf04" class="css-label">Estacionamento</label>
											</div>
										</div><!-- </row> -->
									</div><!-- </containerBeneficios> -->

							<div class="modal-groupForm">
								<textarea class="textarea-modal" rows="3" name="assignments" placeholder="Descreva as atribuições de oportunidade de trabalho"></textarea>
							</div>
							<div class="the-return">
  								[HTML is replaced when successful.]
							</div>

							<div class="col-md-12 text-center">
								<input name="submit" type="submit" class="form-control" id="submit" value=" Add Oportunidade ">
							</div>

		    			</form>
		    		</div><!-- </modal-content> -->
		    	</div><!-- </modal-dialog> -->
		   </div><!-- </modal> -->
		</div><!-- /div de Layout Geral -->

		<!-- ==============================================
		Javascripts
		================================================== -->
		<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
		<script src="<?php echo BOWER; ?>jquery/dist/jquery.min.js"></script>
		<!-- Include all compiled plugins (below), or include individual files as needed -->
		<script src="<?php echo BOWER; ?>bootstrap-sass/assets/javascripts/bootstrap.min.js"></script> <!-- Bootstrap -->
		<!-- Contact JS -->
		<!-- Wow JS -->
		<script src="<?php echo BOWER; ?>wow/dist/wow.min.js"></script> <!-- WOW -->
		<script src="<?php echo BOWER; ?>flexslider/jquery.flexslider-min.js"></script> <!-- FlexSlider JS (Slider Indicações) -->
		<script src="<?php echo BOWER; ?>jquery.scrollTo/jquery.scrollTo.min.js"></script> <!-- ScrollTo -->
		<script src="<?php echo BOWER; ?>jquery.easing/js/jquery.easing.min.js"></script> <!-- Easing -->
		<script src="<?php echo BOWER; ?>jpreloader/js/jpreloader.min.js"></script> <!-- PreLoader -->
		<script src="<?php echo JS; ?>front/smooth-scrolling.js"></script> <!-- Deslocamento Suave Sesões - One Page -->
		<script src="<?php echo JS; ?>front/main.js"></script> <!-- Default JS -->
		<script src="<?php echo JS; ?>boxmessage.js"></script> <!-- Default JS -->
		<script src="<?php echo JS; ?>front/timeline-loader.js"></script> <!-- Plus Timeline Item -->
		<!-- Função Repeater -->
		<script src="<?php echo JS; ?>front/jquery.repeater.min.js"></script>
		<!-- Default JS Pagina Update-->
		<script src="<?php echo JS; ?>profile.js"></script> <!-- Plus Timeline Item -->
		<script src="<?php echo JS; ?>front/use-repeater.js"></script>
		<script src="<?php echo JS; ?>competency.js"></script>
		<script src="<?php echo JS; ?>home/skill.js"></script>
		<script src="<?php echo JS; ?>home/testeAjax.js"></script>

		<!-- Tuner ACessibilidade de Cores -->
		<script src="<?php echo TUNER; ?>js/tuner.js"></script>
		<div id="tuner" class="tuner">
			<label>Theme Colors</label>
			<ul class="colors">
				<li data-color="orange" class="color-orange"><span></span></li>
				<li data-color="purple" class="color-purple"><span></span></li>
				<li data-color="green" class="color-green"><span></span></li>
				<li data-color="pink" class="color-pink"><span></span></li>
				<li data-color="blue" class="color-blue active"><span></span></li>
				<li data-color="cyan" class="color-cyan"><span></span></li>
			</ul><!-- </ colors> -->
			<label>Layout Styles</label>
			<ul class="layouts">
				<li data-layout="boxed">Boxed</li>
				<li data-layout="widescreen" class="active">Widescreen</li>
			</ul>
			<i id="tuner-switcher" class="fa fa-cogs"></i>
		</div><!-- </tuner> -->
		<!--/ tuner -->
	</body>
</html>