			<footer>
			<!-- ==============================================
			    Footer (Rodapé)
			    =============================================== -->
				<section class="social-links">
				  <div class="container">
				    <div class="row">
				          <ul>
				            <li> <a href="https://www.facebook.com/profile.php?id=1800765934" target="_blank" title=""> <span> <i class="fa fa-facebook"></i> </span> </a> </li>
				            <li> <a href="https://twitter.com/elisandromello" target="_blank" title=""> <span> <i class="fa fa-twitter"></i> </span> </a> </li>
				            <li> <a href="http://www.linkedin.com/in/elisandromello" target="_blank" title=""> <span> <i class="fa fa-linkedin"></i> </span> </a> </li>
				            <li> <a href="http://www.instagram.com/iamelisandromello" target="_blank" title=""> <span> <i class="fa fa-instagram"></i> </span> </a> </li>
				            <li> <a href="https://github.com/iamelisandromello" target="_blank" title=""> <span> <i class="fa fa-github"></i> </span> </a> </li>
				            <li> <a href="mailto:iam@elisandromello.com.br?subject=Eu tenho um comentário para você..." title=""><span> <i class="fa fa-envelope"></i></span></a></li>
				          </ul>
				    </div><!-- /row -->
				  </div><!-- /container -->    
				</section><!-- </social-links> Final Sessão Redes Sociais -->

				<!-- ==============================================
				   Créditos (Credits)
				=============================================== --> 
				<section class="copyright">
				  <div class="container">
				    <div class="col-md-12">
				      <div class="text-center"> 
				        <!-- Logo Header -->
				        <section id="fox_footer" class="fox_footer">
				          <div> <img src="<?php echo IMAGES; ?>logofooter.png" alt="Foxin by Elisandro Mello"> - &copy;<script>document.write(new Date().getFullYear())</script> - Designer coded and designed by  <i class="fa fa-cloud-upload"></i> Elisandro Mello</div>
				          
				        </section>
				        <!--/ Logo Header-->
				      </div>
				    </div><!-- </col-md-12> -->
				  </div><!-- </container> -->
				</section><!-- </copyright> Final Section Copyright -->
			</footer>
			<!-- Back To Top -->
			<a id="back-to-top" href="#">
				<i class="font-icon-arrow-simple-up"></i>
			</a>
			<!-- End Back to Top -->

			<!--==============================================
			Modal User Search (Busca Usuarios)
			===============================================-->
		   <div class="modal fade" id="modal3" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
		    	<div class="modal-dialog">
		    		<div class="modal-content modal-popup">
		    			<div class="modal-header">
		    				<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
		    				<h2 class="modal-title">Search System without Refresh</h2>
		    			</div>
		    			
		    			<div class="row">
		    				<div class="col-md-10 centered">
		    					<div class="modal-containerStep">
		    						<span class="step-num">1</span>
		    						<div class="modal-text">
		    							<span class="hidden-xs">Find users on</span> your network
		    						</div><!-- </modal-text> -->
		    					</div><!-- </modal-containerStep> -->
		    				</div><!-- </col-md-10> -->
		    			</div><!-- </row> -->

		    			<form action="<?php echo BASE; ?>usuario/pesquisar/" class="form-user clearfix" method="post">	
		    				<div class="modal-groupForm">
		    					<div class="grupo-input">
		    						<span class="grupo-input-img"><i class="fa fa-user-plus"></i></span>
									<input class="input-modal" type="text" name="campo" id="campo" placeholder="O que você está procurando?">
		    					</div>
		    				</div><!-- </modal-groupForm> -->
 
							<div class="col-md-12 text-center">
								<input name="enviar" type="submit" class="form-control" id="submit" value="Pesquisar">
							</div><!-- </col-md-12> -->

		    			</form>
						<?php 
							if ($view_users) : 
								foreach ($view_users as $user) : 
						?>
									<div class="col-md-12 search-user">
										<div class="row">
											<div class="col-md-2">

												<div class="avatar-wrapper">
													<?php
								                  if (!is_null($view_user->image)) {
								                       echo '<img class="avatar-busca wow bounceIn" src="' . BASE . 'public/uploads/users/' . $user->id . '/' . $user->image . '" width="160">';
								                  }
								                  else{
								                       echo '<img class="avatar-busca" src="' . BASE . 'public/uploads/users/' . 'default' . '/' . 'default.png' . '" width="160">';
								                  }
							               	?>
												</div><!-- </> -->										
												
											</div><!-- </> -->
											<div class="col-md-10 ">
												<div class="row">
													<div class="col-md-12 search-name">
														<h5><?php echo $user->name; ?></h5>
													</div>
												</div>
												<div class="row">
													<div class="col-md-12 search-charge">
														<h5><?php echo $view_user->professionals[0]->function; ?></h5>
													</div>
												</div>
											</div><!-- </> -->
										</div><!-- </row> -->

									</div>
						<?php 
								endforeach;
							endif;
						?>

		    		</div><!-- </modal-content> -->
		    	</div><!-- </modal-dialog> -->
		   </div><!-- </modal> -->

			<!--==============================================
			Modal Delete (Delete Opportunity )
			===============================================-->
		   <div class="modal fade" id="modal1" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
		    	<div class="modal-dialog">
		    		<div class="modal-content modal-popup">
		    			<div class="modal-header">
		    				<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
		    				<h2 class="modal-title">Opportunities Management</h2>
		    			</div>

		    			<div class="row">
		    				<div class="col-md-10 centered">
		    					<div class="modal-containerStep">
		    						<span class="step-num">1</span>
		    						<div class="modal-text">
		    							<span class="hidden-xs">About the </span> opportunity
		    						</div>
		    					</div>
		    				</div>
		    			</div>

		    			<form action="#" method="post">
		    				<div class="modal-groupForm">
		    					<div class="grupo-input">
		    						<span class="grupo-input-img"><i class="fa fa-user-plus"></i></span>
		    						<input type="text" name="comment" class="input-modal" placeholder="Ex. Analista Jr" >
		    					</div>
		    				</div>

							<div class="modal-groupForm">
								<textarea class="textarea-modal" rows="5" placeholder="Describe the job opportunity assignments"></textarea>
							</div>

							<div class="col-md-12 text-center">
								<input name="submit" type="submit" class="form-control" id="submit" value="Delete">
							</div>

		    			</form>
		    		</div><!-- </modal-content> -->
		    	</div><!-- </modal-dialog> -->
		   </div><!-- </modal> -->

			<!--==============================================
			Modal Add Opportunitty (Add Nova Oportunidade )
			===============================================-->
		   <div class="modal fade" id="modal10" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
		    	<div class="modal-dialog">
		    		<div class="modal-content modal-popup">
		    			<div class="modal-header">
		    				<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
		    				<h2 class="modal-title">Inclusion of Opportunity</h2>
		    			</div>

		    			<div class="row">
		    				<div class="col-md-10 centered">
		    					<div class="modal-containerStep">
		    						<span class="step-num">1</span>
		    						<div class="modal-text">
		    							<span class="hidden-xs">About the </span> opportunity
		    						</div>
		    					</div>
		    				</div>
		    			</div>

		    			<form action="#" method="post">
		    				<div class="modal-groupForm">
		    					<div class="grupo-input">
		    						<span class="grupo-input-img"><i class="fa fa-user-plus"></i></span>
		    						<input type="text" name="comment" class="input-modal" placeholder="Ex. Analista Jr" >
		    					</div>
		    				</div>

							<div class="modal-groupForm">
								<textarea class="textarea-modal" rows="5" placeholder="Describe the job opportunity assignments"></textarea>	
							</div>

							<div class="row">
			    				<div class="col-md-10 centered">
			    					<div class="modal-containerStep">
			    						<span class="step-num">2</span>
			    						<div class="modal-text">
			    							Requirements
			    						</div>
			    					</div>
			    				</div>
			    			</div>

		    				<div class="modal-groupForm">
								<table>
									<tr>
										<td>
											<input type="checkbox" name="checkbox-bnf01" id="checkbox-rqs01" class="css-checkbox" checked="checked" />
											<label for="checkbox-rqs01" class="css-label">Servers</label>
										</td>
										<td>
											<input type="checkbox" name="checkbox-rqs02" id="checkbox-rqs02" class="css-checkbox" />
											<label for="checkbox-rqs02" class="css-label">Cloud</label>
										</td>
										<td>
											<input type="checkbox" name="checkbox-rqs03" id="checkbox-rqs03" class="css-checkbox" />
											<label for="checkbox-rqs03" class="css-label">Virtualization</label>
										</td>
										<td>
											<input type="checkbox" name="checkbox-rqs04" id="checkbox-rqs04" class="css-checkbox" />
											<label for="checkbox-rqs04" class="css-label">Routers</label>
										</td>
									</tr>
								</table>
		    				</div>

		    				<div class="modal-groupForm">
		    					<table>
									<tr>
										<td>
											<input type="checkbox" name="checkbox-rqs05" id="checkbox-rqs05" class="css-checkbox" />
											<label for="checkbox-rqs05" class="css-label">Firewalls</label>
										</td>
										<td>
											<input type="checkbox" name="checkbox-rqs06" id="checkbox-rqs06" class="css-checkbox" />
											<label for="checkbox-rqs06" class="css-label">Backup</label>
										</td>
										<td>
											<input type="checkbox" name="checkbox-rqs07" id="checkbox-rqs07" class="css-checkbox" />
											<label for="checkbox-rqs07" class="css-label">Sotorage</label>
										</td>
									</tr>
								</table>
		    				</div>

							<div class="row">
			    				<div class="col-md-10 centered">
			    					<div class="modal-containerStep">
			    						<span class="step-num">3</span>
			    						<div class="modal-text">
			    							Additional Benefits
			    						</div>
			    					</div>
			    				</div>
			    			</div>

							<div class="modal-groupForm">
								<table>
									<tr>
										<td>
											<input type="checkbox" name="checkbox-bnf01" id="checkbox-bnf01" class="css-checkbox" checked="checked" />
											<label for="checkbox-bnf01" class="css-label">Health Care</label>
										</td>
										<td>
											<input type="checkbox" name="checkbox-bnf02" id="checkbox-bnf02" class="css-checkbox" />
											<label for="checkbox-bnf02" class="css-label">Dental Care</label>
										</td>
										<td>
											<input type="checkbox" name="checkbox-bnf03" id="checkbox-bnf03" class="css-checkbox" />
											<label for="checkbox-bnf03" class="css-label">Fuel Aidon</label>
										</td>
										<td>
											<input type="checkbox" name="checkbox-bnf04" id="checkbox-bnf04" class="css-checkbox" />
											<label for="checkbox-bnf04" class="css-label">Parking</label>
										</td>
									</tr>
								</table>
		    				</div>

		    				<div class="modal-groupForm">
		    					<table>
									<tr>
										<td>
											<input type="checkbox" name="checkbox-bnf05" id="checkbox-bnf05" class="css-checkbox" />
											<label for="checkbox-bnf05" class="css-label">Meal Ticket</label>
										</td>
										<td>
											<input type="checkbox" name="checkbox-bnf06" id="checkbox-bnf06" class="css-checkbox" /><label for="checkbox-bnf06" class="css-label">Food Stamps</label>
										</td>
										<td>
											<input type="checkbox" name="checkbox-bnf07" id="checkbox-bnf07" class="css-checkbox" />
											<label for="checkbox-bnf07" class="css-label">Private Pension</label>
										</td>
									</tr>
								</table>
		    				</div>

							<div class="col-md-12 text-center">
								<input name="submit" type="submit" class="form-control" id="submit" value=" Add Opportunity ">
							</div>

		    			</form>
		    		</div><!-- </modal-content> -->
		    	</div><!-- </modal-dialog> -->
		   </div><!-- </modal> -->
		</div><!-- /div de Layout Geral -->

		<!-- ==============================================
		Javascripts
		================================================== -->
		<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
		<script src="<?php echo BOWER; ?>jquery/dist/jquery.min.js"></script>
		<!-- Include all compiled plugins (below), or include individual files as needed -->
		<script src="<?php echo BOWER; ?>bootstrap-sass/assets/javascripts/bootstrap.min.js"></script> <!-- Bootstrap -->
		<script type="text/javascript" src="js/tmp/classie.js"></script>
		<!-- Contact JS -->
		<script src="<?php echo BOWER; ?>jqBootstrapValidation/src/jqBootstrapValidation.js"></script><!--BootstrapValidation-->
		<!-- Wow JS -->
		<script src="<?php echo BOWER; ?>wow/dist/wow.min.js"></script> <!-- WOW --> 
		<script src="<?php echo BOWER; ?>flexslider/jquery.flexslider-min.js"></script> <!-- FlexSlider JS (Slider Indicações) -->
		<script src="<?php echo BOWER; ?>jquery.scrollTo/jquery.scrollTo.min.js"></script> <!-- ScrollTo -->		
		<script src="<?php echo BOWER; ?>jquery.easing/js/jquery.easing.min.js"></script> <!-- Easing -->
		<script src="<?php echo BOWER; ?>jpreloader/js/jpreloader.min.js"></script> <!-- PreLoader -->	
		<script src="<?php echo JS; ?>front/smooth-scrolling.js"></script> <!-- Deslocamento Suave Sesões - One Page -->
		<script src="<?php echo JS; ?>front/main.js"></script> <!-- Default JS -->
		<script src="<?php echo JS; ?>boxmessage.js"></script> <!-- Default JS -->
		<script src="<?php echo JS; ?>front/timeline-loader.js"></script> <!-- Plus Timeline Item -->

		<!-- Tuner ACessibilidade de Cores -->
		<script src="<?php echo TUNER; ?>js/tuner.js"></script>
		<div id="tuner" class="tuner">
			<label>Theme Colors</label>
			<ul class="colors">
				<li data-color="orange" class="color-orange"><span></span></li>
				<li data-color="purple" class="color-purple"><span></span></li>
				<li data-color="green" class="color-green"><span></span></li>
				<li data-color="pink" class="color-pink"><span></span></li>
				<li data-color="blue" class="color-blue active"><span></span></li>
				<li data-color="cyan" class="color-cyan"><span></span></li>
			</ul><!-- </ colors> -->
			<label>Layout Styles</label>
			<ul class="layouts">
				<li data-layout="boxed">Boxed</li>
				<li data-layout="widescreen" class="active">Widescreen</li>
			</ul>
			<i id="tuner-switcher" class="fa fa-cogs"></i>
		</div><!-- </tuner> -->
		<!--/ tuner -->
	</body>
</html>