<!DOCTYPE html>
<html lang="pt-br">
	<head>
		<meta charset="UTF-8">
		<title>Home User - ProfileIT</title>
		<meta name="viewport" content="width=device-width, initial-scale=1">

      <!-- Stylesheet
      ================================================== -->
		<!-- Styles -->
		<link rel="stylesheet" type="text/css" href="<?php echo CSS; ?>general.css" />
		<link rel="stylesheet" type="text/css" href="<?php echo CSS; ?>home.css">
		<link rel="stylesheet" type="text/css" href="<?php echo CSS; ?>plugins.css">
		<link rel="stylesheet" type="text/css" href="<?php echo CSS; ?>fonts.css">
		<link rel="stylesheet" type="text/css" href="<?php echo CSS; ?>nav.css">
		<!--<link rel="stylesheet" type="text/css" href="<?php echo CSS; ?>fonticon">
		<link rel="stylesheet" type="text/css" href="<?php echo CSS; ?>msgbox.css">-->

		<link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,700" rel="stylesheet">

		<!-- Switcher Tuner Only -->
		<link rel="stylesheet" type="text/css" href="<?php echo TUNER; ?>css/tuner.css">

      <!-- Bootstrap
      ================================================== -->
      <link rel="stylesheet" type="text/css" href="css/public/fonts/ionicons/css/ionicons.css">

      <!-- Pre-Define Custom Style Sheet
      ================================================== -->
		<link rel="stylesheet" href="<?php echo CSS; ?>themes/color-cyan.css" title="color-cyan" media="all" property="">
    	<link rel="alternate stylesheet" href="<?php echo CSS; ?>themes/color-blue.css" title="color-blue" media="all" property="">
		<link rel="alternate stylesheet" href="<?php echo CSS; ?>themes/color-green.css" title="color-green" media="all" property="">
		<link rel="alternate stylesheet" href="<?php echo CSS; ?>themes/color-orange.css" title="color-orange" media="all" property="">
		<link rel="alternate stylesheet" href="<?php echo CSS; ?>themes/color-pink.css" title="color-pink" media="all" property="">
		<link rel="alternate stylesheet" href="<?php echo CSS; ?>themes/color-purple.css" title="color-purple" media="all" property="">

	</head>
	<body id="home" data-spy="scroll" data-target="#home-nav" data-offset="300">
		<!-- This section is for Splash Screen -->
		<section id="jSplash">
			<div id="circle"></div>
		</section>
		<!-- End of Splash Screen -->

		<!-- ==============================================
		Navbar (Menu Principal de Navegação)
		=============================================== -->
		<div id="home-nav" class="navbar navbar-default navbar-fixed-top" role="navigation">
		  <div class="container">
				<div class="navbar-header">
					<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
						<span class="sr-only">Toggle navigation</span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</button>
					<a class="navbar-brand" href="#home">
						<!-- Logo Header -->
						<section id="foxin" class="foxin">
							<div>
								<img src="<?php echo IMAGES; ?>Logo_Navbar.png" alt="Foxin by Elisandro Mello">
							</div>
						</section>
						<!--/ Logo Header -->
					</a><!-- </navbar-brand> -->
				</div><!-- </navbar-header> -->
				<div class="navbar-collapse collapse" id="bs-example-navbar-collapse-1">
					<ul class="nav navbar-nav navbar-right">
						<li><a href="#profile">Sobre</a></li>
						<li><a href="#opportunities">Oportunidades</a></li>
						<li><a href="#acc-recommendation">+ Recomendação</a></li>
						<li><a href="#contact-area">+ Oportunidades</a></li>

							<?php if ($view_user->role_id == 1) : ?>
								<li><a href="<?php echo BASE . 'usuarios'; ?>" title="Administrar Usuários" >
									<span> <i class="fa fa-user-secret"></i> </span>
								</a></li>
							<?php endif; ?>

						<li><a href="<?php echo BASE . 'login/sair'; ?>" title="Logout Sistema">
				      	<span> <i class="fa fa-sign-out"></i> </span>
				   	</a></li>
					</ul><!-- </nav navbar-nav navbar-right> -->
				</div><!-- </navbar-collapse collapse> -->
			</div><!-- </container> -->
		</div><!-- </home-nav> -->