	    <!-- ==============================================
	    Layout Content Site (Definição de Layout)
        ====================================-->
		<div class="layout">
			<!-- ==============================================
			Main Start (Inicio do Corpo de Conteúdo)
			=============================================== -->
			<main>												
				<!-- ========================================= -->
				<!--Section Profile(Resumo Profile)                            -->
				<!-- ========================================= -->
				<section id="profile" class="main-block">
					<div class="container text-center">
						<!-- Profile Title -->					
						<div class="title-main text-left wow fadeIn">
							<div class="main-title__inner">
								<div class="text-right main-title__left">
									<i class="fa fa-female mega"></i>
									<h1 class="title-session">profile</h1>
									<em class="title-description">my personal info</em>
								</div>
								<div class="main-title__right">
									<p class="resumo">
										Hi! My name is Kabir Doe. Erat deleniti quasi. Optio maecenas iaculis cubilia, tellus elementum eiusmod laborum occaecat. Laoreet iure, doloremque earum sint diam asperiores condimentum est ac vitae inceptos, maecenas ullam vel curae repellat voluptatem placeat purus, dolore ullam eius excepteur! Magnam beatae suspendisse ut. maecenas ullam vel curae repellat voluptatem placeat purus, dolore ullam eius excepteur! Magnam maecenas ullam vel curae beatae suspendisse ut.
									</p>
								</div>
							</div>
						</div><!-- </main-title> (Icone Session, Title, Description Title e Linha DivisóriaV) -->

						<!-- ========================================= -->
						<!-- Conteúdo Perfil                           -->
						<!-- ========================================= -->
						<div class="row main-block__padder text-left">
							<!-- Foto Perfil -->
							<div class="col-lg-4 col-md-6 col-lg-push-4 text-center wow fadeInUp">
								<div class="inline-block photo-column-inner">
									<div class="photo-profile">
										<img src="<?php echo IMAGES; ?>photo.png" class="img-responsive" alt="#">
									</div>
									<div class="md-padder">
										<a class="btn btn-primary btn-lg margin-btm-30" data-tooltip="Download Resume Profile" href="update.html" target="_blank"> <i class="fa fa-user"></i> <span class="hidden-xs"> Download </span> Resume </a>
									</div>
								</div>
							</div><!-- Container Foto Perfil -->

							<!-- #Informações Perfis Pessoais -->
							<div class="col-lg-4 col-md-6 col-lg-push-4 info-column wow fadeInUp">
								<div>
									<h5 class="text-subtitulo">personal info</h5>
									<ul class="padder list-unstyled info-list">
										<li>Name : Anglea Goble Doe</li>
										<li>Age : 23 Years Old</li>
										<li>Phone : +123-456-7890</li>
										<li>Email : <a href="mailto:email@site.com">email@site.com</a></li>
										<li>Adress : 1732 Monroe Street Houston, TX 77055</li>
									</ul>
									<ul class="list-inline list-gutter-xs padder h5 bare-social-menu">
										<li>
											<a href="#" class="twitter-color">
												<i class="fa fa-twitter"></i>
											</a>
										</li>
										<li>
											<a href="#" class="google-plus-color">
												<i class="fa fa-google-plus"></i>
											</a>
										</li>
										<li>
											<a href="#" class="behance-color">
												<i class="fa fa-behance"></i>
											</a>
										</li>
										<li>
											<a href="#" class="dribbble-color">
												<i class="fa fa-dribbble"></i>
											</a>
										</li>
										<li>
											<a href="#" class="github-color">
												<i class="fa fa-github"></i>
											</a>
										</li>
									</ul>
								</div>
							</div><!-- Container Informações Perfil -->

							<!-- Presentation ticket -->
							<div class="col-xs-12 col-lg-4 col-lg-pull-8 text-left story-column wow fadeInUp">
								<div class="container-temp">
									<!--Horas de Projetos e Trabalhos-->
									<div class="wow fadeIn" data-wow-delay="2s">       
										<div class="col-md-12">
											<div class="charge">
												<h2>Analista Microsoft<br/><span>Pleno</span></h2> 	
											</div>
										</div>
										<div class="row">
											<div class="col-sm-12">
												<div class="container-star centered">
													<div class="star-molde">
														<img class="star-picture wow bounceIn" src="<?php echo IMAGES; ?>estrela1_40.png" >
													</div>
													<div class="star-molde">
														<img class="star-picture wow bounceIn" src="<?php echo IMAGES; ?>estrela1_40.png" >
													</div>
													<div class="star-molde">
														<img class="star-picture wow bounceIn" src="<?php echo IMAGES; ?>estrela1_40.png" >
													</div>
													<div class="star-molde">
														<img class="star-picture wow bounceIn" src="<?php echo IMAGES; ?>estrela2_40.png" >
													</div>
													<div class="star-molde">
														<img class="star-picture wow bounceIn" src="<?php echo IMAGES; ?>estrela2_40.png" >
													</div>
												</div>
										
											</div>										
										</div>
										<div class="row">
											<div class="col-sm-12">
												<div class="description text-left">
						                     <!--My Profile - Dados Profissionais-->
						                     <div class="aboutme-title wow fadeIn" data-wow-delay="1s">
						                        <h5>+ than 5 years<span>  of experience </span> </h5>
						                        <h5><span> Certified Professional </span> MCSA  </h5>
						                        <h5><span> Bachelor of  </span> Ciêcia da Computação </h5>
														<h5><span> Last Company  </span> Dana Albarus </h5>
														<h5><span> </span> Available Professional </h5>
						                     </div>
												</div>
											</div>
										</div>
									</div>
								</div>
							</div><!-- Container Bilhete de Apresentação -->
						</div><!-- </main-block__padder> -->
					</div><!-- </container> -->
				</section><!-- </section> Profile -->
				<!-- ==============================================
       			Skill Técnico (Qualificações e Atributos Técnicos)
        		=============================================== -->
				<section id="skills" class="main-block">
					<div class="container text-center">					
						<div class="title-main text-left wow fadeIn">
							<div class="main-title__inner">
								<div class="text-right main-title__left">
									<i class="fa fa-book mega"></i>
									<h1 class="title-session">skill</h1>
									<em class="title-description">Qualifications and Competences</em>
								</div>
								<div class="main-title__right">
									<p class="resumo">
										Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer.
									</p>
								</div>
							</div>
						</div><!-- </main-title> (Icone Session, Title, Description Title e Linha DivisóriaV) -->

						<div class="container-skill">

							<div class="row">
						    	<div class="col-md-6 col-sm-12 wow bounceInLeft">
							        <div>
								        <p class="texto_profileit text-left">Designer e Projeto de arquitetura de floresta e domínio; considerando relações de confiança, níveis funcionais, atualização de domínio, migração de domínio e reestruturação de floresta;	Configuração de topologia de vários sites e servidores de transporte; implementando topologia de diversos servidores, incluindo servidores autônomos e WDS (Serviços de Implantação do Windows) integrados com o Active Directory; Projeto e implantação de Office 365, e Lync Server 2013; focado no desenvolvimento de soluções de migração de correio utilizando o Microsoft Exchange e Office 365; Planejamento e designer de cenários OnPremises (local) X Online e Hibridos.</p>
								    </div>
						    	</div>
								<div class="col-md-6 col-sm-12 wow bounceInRight" data-wow-delay="0.3s">
									<div class="skill-bar">
								    	<ul>
									        <li>
									          <div class="bar" data-value="" style="width: 90%;">
									            <h5>HTML5/CSS3</h5>
									          </div>
									          <span>9 / 10</span> </li>
									        <li>
									          <div class="bar" data-value="" style="width: 90%;">
									            <h5>Adobe Photoshop</h5>
									          </div>
									          <span>9 / 10</span> </li>
									        <li>
									          <div class="bar" data-value="" style="width: 80%;">
									            <h5>PHP</h5>
									          </div>
									          <span>8 / 10</span> </li>
									        <li>
									          <div class="bar" data-value="" style="width: 90%;">
									            <h5>Plataforma Windows</h5>
									          </div>
									          <span>9 / 10</span> </li>           
									        <li>
									          <div class="bar" data-value="" style="width: 80%;">
									            <h5>Cloud Computing</h5>
									          </div>
									          <span>8 / 10</span>
									    	</li>               
								      	</ul>
								    </div>
								</div>
							</div>
							<div class="row">
								<div class="col-md-12">
									<a class="btn btn-primary btn-lg pull-right" data-tooltip="Professional summary" href="assets/elisandromelloresume.pdf" target="_blank"> <i class="fa fa-paper-plane"></i> <span class="hidden-xs">Download My</span> Curriculum </a>				
								</div>
							</div>
							
						</div>
				  	</div>
				</section>
				<!-- ========================================= -->
				<!-- Resume Section (Acadêmico e Profissional) -->
				<!-- ========================================= -->
				<section id="resume" class="main-block">
					<div class="container text-center">
						<!-- Resume Title -->
						<div class="title-main text-left wow fadeIn">
							<div class="main-title__inner">
								<div class="text-right main-title__left">
									<i class="fa fa-book mega"></i>
									<h1 class="title-session">resume</h1>
									<em class="title-description">know who i'm</em>
								</div>
								<div class="main-title__right">
									<p class="resumo">
										Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer.
									</p>
								</div>
							</div>
						</div><!-- </main-title> (Icone Session, Title, Description Title e Linha DivisóriaV) -->
						
						<!-- ========================================= -->
						<!-- Section Academic(Resumo Acadêmico         -->
						<!-- ========================================= -->
						<div class="container-education text-left" id="education">
							<!-- Educaton title -->
							<div class="table wow fadeIn">
								<div class="icon-titleSession">
									<i class="fa fa-graduation-cap"></i>
								</div>
								<div class="title-sessionResume">
									<h5>Education</h5>
								</div>
								<div class="title-line"></div>
							</div><!-- Final Titulo Education (Icone, Title e Linha divisória) -->

							<!-- Timeline Education -->
							<div class="sub-containerEducation">
								<div class="timeline">

									<!-- Dashed Line -->
									<div class="timeline-rail">
										<span class="timeline-loader-btn plus-icon plus-icon-small"></span>
									</div><!--Linha do tempo tracejada -->
									
									<!-- Container Timeline Items -->
									<div class="timeline-items">										
										<!-- Container Item Unitário -->
										<div class="clearfix timeline-item">					
											<!-- Box Marcadores de Tempo e Status -->
											<div class="bullet-box clearfix">												
												<!-- Marcador Tempo Timeline -->
												<div class="tolltipBullet">														
													<!-- Marcador -->
													<div class="item-marker hidden-xs wow fadeInLeft">
														<span>
															<i class="fa fa-clock-o"></i>
														</span>
														2008 - 2009
													</div><!--(Icon Clock e Data)  -->
													<div class="timeline-item-bullet"></div><!-- Espcaçamento e Icon Marcação -->
												</div><!-- Final Marcador Tempo e Icon Plus	-->
												<div class="timeline-box hidden-xs wow fadeInRight">
													<span>A+</span>
													<small>grade</small>
												</div>
											</div><!-- </bullet-box> Final Box de Marcador -->

											<!-- Conteúdo do Item - Timeline -->
											<div class="timeline-itemContent wow fadeInRight">
												<h6 class="text-subtitulo">master degree of design</h6>
												<ul class="text-subtituloItem">
													<li>name of university</li>
													<li>&#8226;</li>
													<li>USA</li>
												</ul>
												<p class="texto_profileit">
													Coordinates for abs positioning use the closest positioned parent box of the positioned element. So assuming that your div creating the corner(s) has no parent elements that are rel or abs positioned it will default up the chain to the html element which is at 0,0 of the viewport. The only problem here is this may be hard to accomplish depending on your layout.
												</p>
											</div><!-- </timeline-itemContent> Conteúdo Item -->
										</div><!-- </timeline-item> Container Unitário Item -->

										<!-- Container Item Unitário -->
										<div class="clearfix timeline-item">					
											<!-- Box Marcadores de Tempo e Status -->
											<div class="bullet-box clearfix">												
												<!-- Marcador Tempo Timeline -->
												<div class="tolltipBullet">														
													<!-- Marcador -->
													<div class="item-marker hidden-xs wow fadeInLeft">
														<span>
															<i class="fa fa-clock-o"></i>
														</span>
														2008 - 2009
													</div><!--(Icon Clock e Data)  -->
													<div class="timeline-item-bullet"></div><!-- Espcaçamento e Icon Marcação -->
												</div><!-- Final Marcador Tempo e Icon Plus	-->
												<div class="timeline-box hidden-xs wow fadeInRight">
													<span>A+</span>
													<small>grade</small>
												</div>
											</div><!-- </bullet-box> Final Box de Marcador -->

											<!-- Conteúdo do Item - Timeline -->
											<div class="timeline-itemContent wow fadeInRight">
												<h6 class="text-subtitulo">master degree of design</h6>
												<ul class="text-subtituloItem">
													<li>name of university</li>
													<li>&#8226;</li>
													<li>USA</li>
												</ul>
												<p class="texto_profileit">
													Coordinates for abs positioning use the closest positioned parent box of the positioned element. So assuming that your div creating the corner(s) has no parent elements that are rel or abs positioned it will default up the chain to the html element which is at 0,0 of the viewport. The only problem here is this may be hard to accomplish depending on your layout.
												</p>
											</div><!-- </timeline-itemContent> Conteúdo Item -->
										</div><!-- </timeline-item> Container Unitário Item -->									
				
										<!-- Item Oculto -->
										<div class="clearfix timeline-item hidden">					
											<!-- Box Marcadores de Tempo e Status -->
											<div class="bullet-box clearfix">												
												<!-- Marcador Tempo Timeline -->
												<div class="tolltipBullet">														
													<!-- Marcador -->
													<div class="item-marker hidden-xs wow fadeInLeft">
														<span>
															<i class="fa fa-clock-o"></i>
														</span>
														2008 - 2009
													</div><!--(Icon Clock e Data)  -->
													<div class="timeline-item-bullet"></div><!-- Espcaçamento e Icon Marcação -->
												</div><!-- Final Marcador Tempo e Icon Plus	-->
												<div class="timeline-box hidden-xs wow fadeInRight">
													<span>A+</span>
													<small>grade</small>
												</div>
											</div><!-- </bullet-box> Final Box de Marcador -->

											<!-- Conteúdo do Item - Timeline -->
											<div class="timeline-itemContent wow fadeInRight">
												<h6 class="text-subtitulo">master degree of design</h6>
												<ul class="text-subtituloItem">
													<li>name of university</li>
													<li>&#8226;</li>
													<li>USA</li>
												</ul>
												<p class="texto_profileit">
													Coordinates for abs positioning use the closest positioned parent box of the positioned element. So assuming that your div creating the corner(s) has no parent elements that are rel or abs positioned it will default up the chain to the html element which is at 0,0 of the viewport. The only problem here is this may be hard to accomplish depending on your layout.
												</p>
											</div><!-- </timeline-itemContent> Conteúdo Item -->
										</div><!-- </timeline-item> Container Unitário Item Oculto -->	
									</div><!-- </timeline-items> (Final Container Timeline Items-->
								</div><!-- </timeline> (Final Timeline Education-->
							</div><!-- </sub-containerEducation> -->
						</div><!-- </container-education> -->

						<!-- ========================================= -->
						<!-- Section Experience(Resumo Experiences)    -->
						<!-- ========================================= -->
						<div class="container-experience text-left" id="experience">
							<!-- Experince title -->
							<div class="table wow fadeIn">
								<div class="icon-titleSession">
									<i class="fa fa-flask"></i>
								</div>
								<div class="title-sessionResume">
									<h5>experience</h5>
								</div>
								<div class="title-line"></div>
							</div>

							<!-- @EXPERIENCE TIMELINE -->
							<div class="sub-containerExperience">
								<div class="timeline">
									<!-- Dashed Line -->
									<div class="timeline-rail">
										<span class="timeline-loader-btn plus-icon plus-icon-small"></span>
									</div><!--Linha do tempo tracejada -->
									<!-- Container Timeline Items -->
									<div class="timeline-items">										
										<!-- Container Item Unitário -->
										<div class="clearfix timeline-item">
											<!-- Box Marcadores de Tempo e Status -->
											<div class="bullet-box clearfix">												
												<!-- Marcador Tempo Timeline -->
												<div class="tolltipBullet">														
													<!-- Marcador -->
													<div class="item-marker hidden-xs wow fadeInLeft">
														<span>
															<i class="fa fa-clock-o"></i>
														</span>
														2013 - Now
													</div><!--(Icon Clock e Data)  -->
													<div class="timeline-item-bullet"></div><!-- Espcaçamento e Icon Marcação -->
												</div><!-- Final Marcador Tempo e Icon Plus	-->
												<div class="timeline-box hidden-xs wow fadeInRight" style="background-image: url(<?php echo IMAGES; ?>clients/01.png)">
												</div>
											</div><!-- </bullet-box> Final Box de Marcador -->

											<!-- Conteúdo do Item - Timeline -->
											<div class="timeline-itemContent wow fadeInRightt">
												<h6 class="text-subtitulo">lead web developer</h6>
												<ul class="text-subtituloItem">
													<li>name of company</li>
													<li>&#8226;</li>
													<li>USA</li>
												</ul>
												<p class="texto_profileit">
													Coordinates for abs positioning use the closest positioned parent box of the positioned element. So assuming that your div creating the corner(s) has no parent elements that are rel or abs positioned it will default up the chain to the html element which is at 0,0 of the viewport.
												</p>
											</div><!-- </timeline-itemContent> Conteúdo Item -->
										</div><!-- </timeline-item> Container Unitário Item -->		

										<!-- Container Item Unitário -->
										<div class="clearfix timeline-item">
											<!-- Box Marcadores de Tempo e Status -->
											<div class="bullet-box clearfix">												
												<!-- Marcador Tempo Timeline -->
												<div class="tolltipBullet">														
													<!-- Marcador -->
													<div class="item-marker hidden-xs wow fadeInLeft">
														<span>
															<i class="fa fa-clock-o"></i>
														</span>
														2010 - 2012
													</div><!--(Icon Clock e Data)  -->
													<div class="timeline-item-bullet"></div><!-- Espcaçamento e Icon Marcação -->
												</div><!-- Final Marcador Tempo e Icon Plus	-->
												<div class="timeline-box hidden-xs wow fadeInRight" style="background-image: url(<?php echo IMAGES; ?>clients/02.png)">
												</div>
											</div><!-- </bullet-box> Final Box de Marcador -->

											<!-- Conteúdo do Item - Timeline -->
											<div class="timeline-itemContent wow fadeInRightt">
												<h6 class="text-subtitulo">lead web developer</h6>
												<ul class="text-subtituloItem">
													<li>name of company</li>
													<li>&#8226;</li>
													<li>USA</li>
												</ul>
												<p class="texto_profileit">
													Coordinates for abs positioning use the closest positioned parent box of the positioned element. So assuming that your div creating the corner(s) has no parent elements that are rel or abs positioned it will default up the chain to the html element which is at 0,0 of the viewport.
												</p>
											</div><!-- </timeline-itemContent> Conteúdo Item -->
										</div><!-- </timeline-item> Container Unitário Item -->	
										
										<!-- Container Item Unitário -->
										<div class="clearfix timeline-item  hidden">
											<!-- Box Marcadores de Tempo e Status -->
											<div class="bullet-box clearfix">												
												<!-- Marcador Tempo Timeline -->
												<div class="tolltipBullet">														
													<!-- Marcador -->
													<div class="item-marker hidden-xs wow fadeInLeft">
														<span>
															<i class="fa fa-clock-o"></i>
														</span>
														2010 - 2012
													</div><!--(Icon Clock e Data)  -->
													<div class="timeline-item-bullet"></div><!-- Espcaçamento e Icon Marcação -->
												</div><!-- Final Marcador Tempo e Icon Plus	-->
												<div class="timeline-box hidden-xs wow fadeInRight" style="background-image: url(images/clients/07.png)">
												</div>
											</div><!-- </bullet-box> Final Box de Marcador -->

											<!-- Conteúdo do Item - Timeline -->
											<div class="timeline-itemContent wow fadeInRightt">
												<h6 class="text-subtitulo">lead web developer</h6>
												<ul class="text-subtituloItem">
													<li>name of company</li>
													<li>&#8226;</li>
													<li>USA</li>
												</ul>
												<p class="texto_profileit">
													Coordinates for abs positioning use the closest positioned parent box of the positioned element. So assuming that your div creating the corner(s) has no parent elements that are rel or abs positioned it will default up the chain to the html element which is at 0,0 of the viewport.
												</p>
											</div><!-- </timeline-itemContent> Conteúdo Item Oculto-->
										</div><!-- </timeline-item> Container Unitário Item Oculto-->	
									</div><!-- </timeline-items> (Final Container Timeline Items-->
								</div><!-- </timeline> (Final Timeline Education-->
							</div><!-- </sub-containerEducation> -->
						</div><!-- </container-education> -->					
					</div><!-- </container> -->
				</section><!-- </session> -->		
				<!-- ==============================================
				Recomendations (Recomendações Recebidas)
		        =============================================== -->
				<section class="recommendation" id="recommendations" data-stellar-background-ratio="0.6">
				  <div class="overlay"></div>
				  <div class="above-overlay">
				    <div class="container">
				      <div class="row">
				        <div class="col-md-12">
				          <h1 class="text-center margin-btm-30"> Recommendations<span class="cursor-tag">_</span> </h1>
				        </div>
				      </div>
				      <div class="row">
				        <div class="col-md-12">
				          <div class="text-center quote-icon"> <i class="fa fa-quote-left"></i> </div>
				        </div>
				      </div>
				      <div class="row">
				        <div class="col-md-8 col-md-offset-2">
				          <div class="quote-slider">
				            <ul class="slides">
				              <li>
				                <div class="quote-slider-slide-container"> <img class="avatar-md quote-slider-img" src="<?php echo IMAGES; ?>elisandro-mello-profile.jpg" alt="">
				                  <p class="quote-slider-single"> Um líder pode errar por tentativa, nunca por omissão. </p>
				                  <p class="quote-slider-name"> - Elisandro Mello / Consultor TI. </p>
				                </div>
				              </li>
				              <li>
				                <div class="quote-slider-slide-container"> <img class="avatar-md quote-slider-img" src="<?php echo IMAGES; ?>albert-einstein-profile.jpg" alt="">
				                  <p class="quote-slider-single"> A mente que abre uma nova janela, jamais volta ao seu tamanho original. </p>
				                  <p class="quote-slider-name"> - Albert Einstein / Físico Teórico </p>
				                </div>
				              </li>
				              <li>
				                <div class="quote-slider-slide-container"> <img class="avatar-md quote-slider-img" src="<?php echo IMAGES; ?>steve-jobs1-profile.jpg" alt="">
				                  <p class="quote-slider-single"> Concentre-se naquilo que você é bom, delegue todo o resto! </p>
				                  <p class="quote-slider-name"> - Steve Jobs / Fundador Apple </p>
				                </div>
				              </li>
				              <li>
				                <div class="quote-slider-slide-container"> <img class="avatar-md quote-slider-img" src="<?php echo IMAGES; ?>kevin-de-young.jpg" alt="">
				                  <p class="quote-slider-single"> Quer ouvir o Espírito Santo? Abra a Bíblia! </p>
				                  <p class="quote-slider-name"> - Kevin DeYoung / Pregador Cristão. </p>
				                </div>
				              </li>
				              <li>
				                <div class="quote-slider-slide-container"> <img class="avatar-md quote-slider-img" src="<?php echo IMAGES; ?>abraham-lincoln-profile.jpg" alt="">
				                  <p class="quote-slider-single"> Você pode agradar algumas pessoas o tempo todo, você pode agradar a todas as pessoas por algum tempo, mas você não pode agradar a todas as pessoas o tempo todo. </p>
				                  <p class="quote-slider-name"> - Abraham Lincoln / 16º Presidente EUA. </p>
				                </div>
				              </li>
				              <li>
				                <div class="quote-slider-slide-container"> <img class="avatar-md quote-slider-img" src="<?php echo IMAGES; ?>martin-luther-king.jpg" alt="">
				                  <p class="quote-slider-single"> Se não puder voar, corra. Se não puder correr, ande. Se não puder andar, rasteje, mas continue em frente de qualquer jeito. </p>
				                  <p class="quote-slider-name"> - Martin Luther King Jr. / Reverendo e Líder </p>
				                </div>
				              </li>
				            </ul>
				          </div>
				        </div>
				      </div>
				    </div>
				  </div>
				</section>

				<!-- ==============================================
				Contact-Me (Contate-me ou add uma Recomendação)
		        =============================================== -->
				<section id="contact-area">
				    <div class="overlay-contactme"></div>
				    <div class="container">
				        <div class="row">
				            <div class="col-md-offset-2 col-md-8 col-sm-12">
			                    <div class="wow bounceIn section-title">
			                        <div class="text-center">
				                        <h2>Contact-Me or Recommendation </h2>
				                        <p class="texto_profileit wow fadeInUp" data-wow-delay="0.5s">Send me a message if you would like to get in touch. Or add a recommendation about my qualifications and skills, I would be very grateful.</p>
				                    </div>    
			                    </div>
			                    <div class="wow fadeInUp contatc-form" data-wow-delay="0.8s">
			                        <form action="#" method="post">
			                            <div class="col-md-6 col-xs-12 text-center">
			                                <a class="btn envio" href="#" data-toggle="modal" data-target="#modal1"> <i class="fa fa-paper-plane"></i> <span class="hidden-xs">Send </span> Message </a>
			                           	</div>
			                            <div class="col-md-6 col-xs-12 text-center">
											<a class="btn envio" href="#" data-toggle="modal" data-target="#modal2"> <i class="fa fa-paper-plane"></i> <span class="hidden-xs">Add  </span> Recommendation </a>	
			                            </div>
			                        </form>
			                    </div>
				            </div>
				        </div><!-- </row> -->
				    </div><!-- </container -->
				</section><!-- </contact-me> Final Sessão de Contate-me -->
			</main><!-- Main End (Final do Corpo de Conteúdo) -->