		<!-- ==============================================
		Layout Content Site (Definição de Layout)
		====================================-->
		<div class="layout">
			<!-- ==============================================
			Main Start (Inicio do Corpo de Conteúdo)
			=============================================== -->
			<main>
				<!-- ========================================= -->
				<!--Section Menu Access(Menu de Acesso Rápido)                            -->
				<!-- ========================================= -->
				<section class="update-menu">
					<div class="container">
						<div class="options-menu">
							<a class="item-central pointer-cursor" href="<?php echo BASE . 'cadastro/voltar/'; ?>">
								<img src="<?php echo IMAGES; ?>curriculo-tag-miolo.png" alt="Curriculo TAG">
							</a>

							<a class="icone-lapis pointer-cursor" href="<?php echo BASE . 'perfil'; ?>">
								<i class="fa fa-pencil" alt="Update Profile"></i>
							</a>

							<a class="icone-codigo pointer-cursor" href="home.html">
								<i class="fa fa-industry"></i>
							</a>

							<a class="icone-coracao pointer-cursor" href="<?php echo BASE . 'upquestionario/'; ?>" >
								<i class="fa fa-file-text"></i>
							</a>

							<a class="icone-compartilhar pointer-cursor" href="#" data-toggle="modal" data-target="#modal3">
								<i class="fa fa-users"></i>
							</a>
						</div><!-- </options-menu> -->
					</div><!-- </container> -->
				</section><!-- </update-menu> -->
				<!-- ========================================= -->
				<!--Section Profile(Resumo Profile)            -->
				<!-- ========================================= -->
				<section id="profile" class="head-block">
					<div class="container text-center">
						<!-- ========================================= -->
						<!-- Conteúdo Perfil                           -->
						<!-- ========================================= -->
						<div class="row head-block__padder text-left">
							<!-- Foto Perfil -->
							<div class="col-lg-4 col-md-6 col-lg-push-4 text-center wow fadeInUp">
								<div class="inline-block photo-column-inner">
									<div class="photo-profile">
										<!--<img src="<?php echo IMAGES; ?>photo.png" class="img-responsive" alt="#">-->
					               <?php
					                   if (!is_null($view_user->image)) {
					                       echo '<img class="img-responsive" src="' . BASE . 'public/uploads/users/' . $view_user->id . '/' . $view_user->image . '">';
					                   }
					                   else{
					                       echo '<img class="img-responsive" src="' . BASE . 'public/uploads/users/' . 'default' . '/' . 'default.png' . '">';
					                   }
					               ?>
					               <h2><?php echo $view_profile->profile; ?></h2>
            						<p>#<?php echo (!$view_preference) ? null : $view_preference->function ; ?> #<?php echo (!$view_preference) ? null : $view_preference->area ; ?> #<?php echo (!$view_preference) ? null : $view_preference->especially ; ?></p>
									</div><!-- </photo-profile> -->
									<div class="md-padder">
										<a class="btn btn-primary btn-lg margin-btm-30" <a href="<?php echo BASE . 'usuario'; ?>" > <i class="fa fa-user"></i> <span class="hidden-xs"> Visualizar </span> Perfil </a>
									</div><!-- </md-padder> -->
								</div><!-- </inline-block photo-column-inner> -->
							</div><!-- Container Foto Perfil -->

							<!-- #Informações Perfis Pessoais -->
							<div class="col-lg-4 col-md-6 col-lg-pull-4 info-column wow fadeInUp">
								<div>
									<h5 class="text-subtitulo">Informações Pessoais</h5>
									<ul class="padder list-unstyled home-infolist">
										<li><span><?php echo $view_total[0] ?> anos e <?php echo $view_total[1] ?> meses </span>- Experiência Efetiva</li>
										<h5 class="text-subtitulo">Sugestão de atualizações</h5>
										<?php
											foreach ($view_sugestoes as $sugestao) :
												if ($sugestao != null) { ?>
													<li><span>
														<?php echo ($sugestao == null) ? null : $sugestao; ?>
													</span></li>
												<?php
												}
												//else { echo $sugestao;}
											endforeach;
										?>
										<h5 class="text-subtitulo">Itens Não Informados </h5>
										<li>
										<?php
											if ($view_analiseQualificacoes == null) {
										?>
												<span>
													<?php echo ('/ Perfil de Competências'); ?>
												</span>
										<?php
											}
											if ($view_analiseRecomendacoes == null) {
										?>
												<span>
													<?php echo (' / Recomendações'); ?>
												</span>
										<?php
											}
										if ($view_analiseRecomendador == null) {
										?>
												<span>
													<?php echo ('/ Recomende Colegas'); ?>
												</span>
										<?php
											}
											if ($view_analisePreferencias == null) {
										?>
												<span>
													<?php echo (' / Informe Áreas de atuação'); ?>
												</span>
										<?php
											}
										?>
										</li>
									</ul><!-- </list-unstyled home-infolist> -->
									<div class="col-md-12 col-md-offset-0 text-uppercase">
										<!-- SKILL TITLE -->
										<h5 class="text-subtitulo">Perfil Percentual </h5>
										<!-- Force Meter -->
										<div class="force-meter xs-padder">
											<?php
											for ($i=0; $i < $view_ctrMeter; $i++) {
											?>
												<div class="on"></div>

											<?php
												}
											?>
											<?php
											for ($i=5; $i > $view_ctrMeter; $i--) {
											?>
												<div></div>

											<?php
												}
											?>
										</div><!-- </Force Meter> -->
									</div><!-- </> Final Barra Força Perfil-->
								</div>
							</div><!-- Container Informações Perfil -->

							<!-- Presentation ticket -->
							<div class="col-lg-offset-0 col-lg-4 col-sm-8 col-sm-offset-2 col-md-6 col-md-offset-3 col-xs-offset-1 col-xs-10 ">
								<div class="community_wrapper">
									<h5 class="text-subtitulo text-center">Comunidade</h5>
									<div class="community_hive">


									<?php
									if ($view_comunidade) :
										foreach ($view_comunidade as $colega) :
											if ($colega->role_id == 1 || $colega->role_id == 2) :
											if ($colega->id != $view_user->id) :
											?>
											<a class="pointer-cursor" href="<?php echo BASE . 'comunidade/load/' . $colega->id; ?>">
												<?php echo '<img class="avatar-comunidade wow bounceIn" src="' . BASE . 'public/uploads/users/' . $colega->id . '/' . $colega->image . '">'; ?>
											</a>
									<?php
											endif;
											endif;
										endforeach;
									endif;
									?>

										<img class="avatar-comunidade wow bounceIn" src="<?php echo IMAGES; ?>profiles/13.jpg" >

										<img class="avatar-comunidade wow bounceIn" src="<?php echo IMAGES; ?>profiles/5.jpg" >

										<img class="avatar-comunidade wow bounceIn" src="<?php echo IMAGES; ?>profiles/2.jpg" >

										<img class="avatar-comunidade wow bounceIn" src="<?php echo IMAGES; ?>profiles/12.jpg" >

										<img class="avatar-comunidade wow bounceIn" src="<?php echo IMAGES; ?>profiles/13.jpg" >

										<img class="avatar-comunidade wow bounceIn" src="<?php echo IMAGES; ?>profiles/5.jpg" >

										<img class="avatar-comunidade wow bounceIn" src="<?php echo IMAGES; ?>profiles/2.jpg" >

										<img class="avatar-comunidade wow bounceIn" src="<?php echo IMAGES; ?>profiles/12.jpg" >
									</div><!-- </comunidade>-->
								</div>
							</div><!-- Container Bilhete de Apresentação -->
						</div><!-- </main-block__padder> -->
					</div><!-- </container> -->
				</section><!-- </section> Profile -->
				<!-- =====================================================
			   add Preferências (Função, Especialidade e Área de Atuação)
			   ====================================================== -->
				<?php if (!$view_analisePreferencias): ?>
				<section id="adc-charges" class="main-block adc-charges">
					<div class="container text-center">
						<!-- Opportunities Title -->
						<div class="title-main text-left wow fadeIn">
							<div class="main-title__inner">
								<div class="main-title__left text-right">
									<i class="fa fa-cog mega"></i>
									<h1 class="title-session">Preferências</h1>
									<em class="title-description">Áreas de Atuação</em>
								</div><!-- </main-title__left> -->
								<div class="main-title__right">
               				<div class="msgbox" id="msg-preference">
            						<span></span>
         						</div>
								</div><!-- </main-title__right> -->
							</div><!-- </main-title__inner> -->
						</div><!-- </title-main> -->
						<div class="row">
							<div class="col-md-12">
								<form method="POST" action="<?php echo BASE; ?>home/addpreference/"  name="addPreference" id="registration-preference" class="registration-preference form-horizontal wrapper-repeater" >
									<fieldset>
										<div class="row">
											<div class="col-xs-10 col-sm-6 col-md-4 col-lg-4">
												<div class="box-input">
													<select name="function" id="function" class="form-control">
														<option class="opt-placeholder" value="-1" selected="">Select…
														</option>
														<optgroup label="Operacional">
															<option>Administrador de banco de dados (DBA)</option>
															<option>Administrador de rede</option>
															<option>Analista de dados</option>
															<option>Analista de Infra</option>
															<option>Analista de microinformática</option>
															<option>Analista de negócios</option>
															<option>Analista de processos</option>
															<option>Analista de projetos de sistemas</option>
															<option>Analista de segurança de informações</option>
															<option>Analista de sistemas</option>
															<option>Analista de sistemas de internet</option>
															<option>Analista de suporte ERP</option>
															<option>Analista de suporte Linux</option>
															<option>Analista de suporte Redes</option>
															<option>Analista de suporte Windows</option>
															<option>Analista de telecomunicações</option>
															<option>Analista de testes</option>
															<option>Analista segurança de sistemas</option>
															<option>Arquiteto de testes</option></option>
														</optgroup>
														<optgroup label="Gestão">
															<option>Auditor de sistemas</option>
															<option>Consultor TI especializado</option>
															<option>Consultor TI funcional</option>
															<option>Coordenador de projetos de sistemas</option>
															<option>Coordenador de suporte técnico</option>
															<option>Gerente de processos</option>
															<option>Gerente de produção de operações</option>
															<option>Gerente de projetos de sistemas</option>
															<option>Gerente de sistemas</option>
															<option>Gerente de suporte técnico</option>
															<option>Gerente de telecomunicações</option>
														</optgroup>
														<optgroup label="Desenvolvimento">
															<option>Programador .NET</option>
															<option>Programador Abap</option>
															<option>Programador ASP</option>
															<option>Programador Delphi</option>
															<option>Programador Java</option>
															<option>Programador PHP</option>
															<option>Técnico de suporte</option>
															<option>Técnico de telecomunicações</option>
															<option>Webdesigner</option>
															<option>Webmaster</option>
														</optgroup>
													</select>
												</div><!--</box-input> -->
											</div><!--</col-md-4> -->
											<div class="col-xs-10 col-sm-6 col-md-4 col-lg-4">
												<div class="box-input">
													<select name="area" id="area" class="form-control">
														<option class="opt-placeholder" value="-1" selected="">Select…
														</option>
														<optgroup label="Area">
															<option>Consultoria</option>
															<option>Freelancer</option>
															<option>Especialista</option>
															<option>Influenciador</option>
															<option>Evangelista</option>
														</optgroup>
													</select>
												</div><!--</box-input> -->
											</div><!--</col-md-4> -->
											<div class="col-xs-10 col-sm-6 col-md-4 col-lg-4">
												<div class="box-input">
													<select name="especially" id="especially" class="form-control">
														<option class="opt-placeholder" value="-1" selected="">Select…
														</option>
														<optgroup label="Especialidade">
															<option>Desenvolvimento</option>
															<option>Segurança</option>
															<option>Web Developer</option>
															<option>DevOps</option>
															<option>Cloud</option>
															<option>Virtualização</option>
															<option>Network</option>
															<option>Routers</option>
															<option>BigData</option>
														</optgroup>
													</select>
												</div><!--</box-input> -->
											</div><!--</col-md-4> -->
										</div><!-- </row> -->
										<div class="row">
											<div class="md-padder text-center col-xs-4 col-sm-4 col-md-4 col-lg-4 centered">
			                  			<button type="submit" class="btn btn-primary btn-lg margin-btm-30" id="btnPreference">
			                  				<i class="fa fa-arrow-right"></i>
			                  				<span>Salvar</span>
			                  			</button>
		 									</div>
										</div><!-- </row> -->
									</fieldset>
								</form>
							</div><!-- </col-md-12> -->
						</div><!-- </row> -->
					</div><!-- </container> -->
				</section>
				<?php endif; ?>
				<!-- =================================================
			   add Competências (Resumo Profissional e Qualificações)
			   ================================================== -->
				<?php if (!$view_analiseQualificacoes): ?>
				<section id="adc-competency" class="main-block acc-recommendation">
					<div class="container text-center">

						<div class="row">
							<div class="col-md-6">
							<!-- Acc RecommendationTitle -->
								<div class="title-main text-left wow fadeIn">
									<div class="main-title__inner">
										<div class="main-title__left text-right">
											<i class="fa fa-bar-chart"></i>
											<h1 class="title-session">Competências</h1>
											<em class="title-description">Adicionar Resumo Profissional e Qualificações</em>
										</div><!-- </main-title__left> -->
									</div><!-- </main-title__inner> -->
								</div><!-- </title-main> -->
							</div>
		 					<!--
		 					*	Add Competências
		 					*-->
							<div class="col-md-6">
								<div class="row">
									<div class="col-md-12">
										<form method="POST" action="<?php echo BASE; ?>home/cadastrarskill/"  name="addSkill" id="registration-skill" class="registration-skill form-horizontal wrapper-repeater" >
											<fieldset>
												<div class="row">
													<div class="boxResume col-xs-10 col-sm-10 col-md-12 col-lg-12 ">
														<textarea class="form-control border-input" placeholder="Adicione seu resumo profissional" rows="4" name="description"></textarea>
													</div>
												</div>
												<legend>Adicionar Competências</legend>
												<div class="boxCompetencies">
													<div class="row">
														<div class="boxTitles">
															<div class="col-md-5">
																<label>Competências</label>
															</div>
															<div class="col-md-2">
																<label>Nível</label>
															</div>
														</div>
													</div><!-- </row> -->
						      					<div class="row">
														<div class="col-xs-8 col-sm-7 col-md-7 col-lg-5 wow flipInx">
							   							<div class="box-input">
							   								<select name="qualification_id" id="qualification_id" class="form-control border input">
		 															<option class="opt-placeholder" value="-1" selected="">Competência</option>
				 													<optgroup label="Microsoft">
				 													<?php foreach ($view_qualificacoes as $qualificacao) :
				 													if ($qualificacao->domain == 'Microsoft') : ?>
					 													<option value="<?php echo $qualificacao->id ?>">
					 														<?php echo $qualificacao->qualification ?>
					 													</option>
					 												<?php endif;
					 												endforeach; ?>
				 													</optgroup>
				 													<optgroup label="Linux">
				 													<?php foreach ($view_qualificacoes as $qualificacao) :
				 													if ($qualificacao->domain == 'Linux') : ?>
					 													<option value="<?php echo $qualificacao->id?>">
					 														<?php echo $qualificacao->qualification ?>
					 													</option>
					 												<?php endif;
					 												endforeach; ?>
				 													</optgroup>
				 													<optgroup label="Especializações">
				 													<?php foreach ($view_qualificacoes as $qualificacao) :
				 													if ($qualificacao->domain == 'Especialização') : ?>
					 													<option value="<?php echo $qualificacao->qualification ?>">
					 														<?php echo $qualificacao->qualification ?>
					 													</option>
					 												<?php endif;
					 												endforeach; ?>
				 													</optgroup>
				 													<optgroup label="Processos ">
				 													<?php foreach ($view_qualificacoes as $qualificacao) :
				 													if ($qualificacao->domain == 'Processos') : ?>
					 													<option value="<?php echo $qualificacao->qualification ?>">
					 														<?php echo $qualificacao->qualification ?>
					 													</option>
					 												<?php endif;
					 												endforeach; ?>
				 													</optgroup>
			 													</select>
							   							</div><!-- </box-input> -->
							      					</div><!-- </col-md-5> -->
														<div class="col-xs-2 col-sm-2 col-md-3 col-lg-2 wow flipInx">
		 													<div class="box-input">
		 														<select name="level" id="level" class="form-control">
				 													<option value="1">
				 														1
				 													</option>
				 													<option value="2">
				 														2
				 													</option>
				 													<option value="3">
				 														3
				 													</option>
				 													<option value="4">
				 														4
				 													</option>
				 													<option value="5">
				 														5
				 													</option>
				 													<option value="6">
				 														6
				 													</option>
				 													<option value="7">
				 														7
				 													</option>
				 													<option value="8">
				 														8
				 													</option>
				 													<option value="9">
				 														9
				 													</option>
				 													<option value="10">
				 														10
				 													</option>
			 													</select>
		 													</div>
						         					</div><!-- </col-md-1> -->
													</div><!-- </row> -->
				 									<hr/>
													<div class="row">
														<div class="col-md-12">
															<div class="md-padder text-left">
				                        				<button type="submit" class="btn btn-primary btn-lg margin-btm-30" id="btnSkill">
				                        					<i class="fa fa-send"></i>
				                        					<span>Enviar</span>
				                        				</button>
				                        				<div class="msgbox" id="msg-alert">
						               						<span></span>
						            						</div>
						 									</div><!-- </md-padder> -->
														</div>
													</div>
												</div><!-- </boxCompetencies> -->
											</fieldset>
										</form>
									</div><!-- </col-md-12> -->
								</div><!-- </row> -->
							</div><!-- </col-md-6> -->
						</div>
						<!-- End Title Section -->
					</div><!-- </container> -->
				</section><!-- </opportunities> -->
				<?php endif; ?>
				<!-- ==============================================
				Messages (Mensagens Recebidas)
		        =============================================== -->
				<?php if ($view_user->messages) : ?>
				<section class="messages" id="messages" data-stellar-background-ratio="0.6">
					<div class="overlay"></div>
				   <div class="above-overlay">
						<div id="team" class="fw-main-row default full-height"  style="background-color: #111111; background-repeat: no-repeat; background-position: left top; background-size: cover; ">
							<div class="container">
								<div class="fw-row">
									<div class="fw-col-xs-12 grid-column"  style="">
										<div id="shortcode-team-members-id-59d94077dca64" class="shortcode-team-members" style="padding-top: 60px; padding-bottom: 60px; ">
											<!--
												Photos and content
											-->
											<div class="items">

												<?php
												if (!$view_myMessages) {
													$lastMessage = Message::find('last', array('conditions' => array('user_id in (?)', array($view_user->id))));
													$lastSender = User::find($lastMessage->sender_id);
													$lastFuncao = Definition::find_by_user_id($lastSender->id);
													$lastAnalista = Profile::find_by_type($lastFuncao->profile_id);
												?>
												<div class="item" data-bg="http://themes.wplab.pro/unicum/wp-content/uploads/sites/2/2015/09/team_bg_1.jpg">
													<div class="container-fluid">
														<div class="row">
															<div class="col-md-6 wow fadeInDown">										<!--
															Position title
															-->
																<div class="position"><?php echo $lastAnalista->profile ?></div>
																<!--
																Team mamber name
																-->
																<h2 class="h1 member-title"><?php echo $lastSender->name ?> <?php echo $lastSender->last_name ?></h2>
																<!--
																Description
																-->
																<div class="member-text">
																	<div class="fw-page-builder-content"><?php echo $lastMessage->message ?></div>
																</div><!--</member-text>-->
																<div class="links">
																	<!--
																	Send message button
																	-->
																		<a href="#" data-toggle="modal" data-target="#modalMessage" class="button cyan" onclick="replyModal(<?php echo $myMessage->id ?>, <?php echo $view_user->id ?>)">Responder</a>
																		<!--
																		Social icons
																		-->
																		<div class="social-icons">
																			<?php if ($lastSender->network->facebook ) :
																			 ?>
																			<a href="http://facebook.com/<?php echo $sender->network->facebook ?>" target="_blank">
																				<i class="fa fa-facebook"></i>
																			</a>
																			<?php endif;
																			if ($lastSender->network->twitter ) :
																			 ?>
																			<a href="http://twitter.com/<?php echo $sender->network->twitter ?>" target="_blank">
																				<i class="fa fa-twitter"></i>
																			</a>
																			<?php endif;
																			if ($lastSender->network->linkedin ) :
																			 ?>
																			<a href="http://linkedin.com/in/<?php echo $sender->network->linkedin ?>" target="_blank">
																				<i class="fa fa-linkedin"></i>
																			</a>
																			<?php endif;
																			if ($lastSender->network->github ) :
																			 ?>
																			<a href="http://github.com/<?php echo $sender->network->github ?>" target="_blank">
																				<i class="fa fa-github"></i>
																			</a>
																			<?php endif; ?>
																		</div><!--</social-icons> -->
																</div><!--</links>-->
															</div><!--</col-md-6 wow fadeInDown>-->
														</div><!--</row>-->
													</div><!--</container-fluid>-->
												</div><!--</item>-->
												<?php
												}
												else {
													foreach ($view_myMessages as $myMessage) :
														$sender = User::find($myMessage->sender_id);
														$funcao = Definition::find_by_user_id($sender->id);
														$analista = Profile::find_by_type($funcao->profile_id);
												?>
												<div class="item" data-bg="http://themes.wplab.pro/unicum/wp-content/uploads/sites/2/2015/09/team_bg_1.jpg">
													<div class="container-fluid">
														<div class="row">
															<div class="col-md-6 wow fadeInDown">										<!--
															Position title
															-->
																<div class="position"><?php echo $analista->profile ?></div>
																<!--
																Team mamber name
																-->
																<h2 class="h1 member-title"><?php echo $sender->name ?> <?php echo $sender->last_name ?></h2>
																<!--
																Description
																-->
																<div class="member-text">
																	<div class="fw-page-builder-content"><?php echo $myMessage->message ?></div>
																</div><!--</member-text>-->
																<div class="links">
																		<div class="social-icons">
																			<a class="pointer" onclick="checkMessage(<?php echo $myMessage->id ?>, <?php echo $view_user->id ?>)">
																				<i class="fa fa-check-square-o"></i>
																			</a>
																		</div><!--</social-icons> -->
																	<!--
																	Send message button
																	-->
																		<a data-toggle="modal" data-target="#modalMessage" class="button cyan" onclick="replyModal('<?php echo $sender->id ?>','<?php echo $sender->image?>')">Responder</a>
																		<!--
																		Social icons
																		-->
																		<div class="social-icons">
																			<?php if ($sender->network->facebook ) :
																			 ?>
																			<a href="http://facebook.com/<?php echo $sender->network->facebook ?>" target="_blank">
																				<i class="fa fa-facebook"></i>
																			</a>
																			<?php endif;
																			if ($sender->network->twitter ) :
																			 ?>
																			<a href="http://twitter.com/<?php echo $sender->network->twitter ?>" target="_blank">
																				<i class="fa fa-twitter"></i>
																			</a>
																			<?php endif;
																			if ($sender->network->linkedin ) :
																			 ?>
																			<a href="http://linkedin.com/in/<?php echo $sender->network->linkedin ?>" target="_blank">
																				<i class="fa fa-linkedin"></i>
																			</a>
																			<?php endif;
																			if ($sender->network->github ) :
																			 ?>
																			<a href="http://github.com/<?php echo $sender->network->github ?>" target="_blank">
																				<i class="fa fa-github"></i>
																			</a>
																			<?php endif; ?>
																		</div><!--</social-icons> -->
																</div><!--</links>-->
															</div><!--</col-md-6 wow fadeInDown>-->
														</div><!--</row>-->
													</div><!--</container-fluid>-->
												</div><!--</item>-->
												<?php
													endforeach;
												}
												?>
											</div><!--</items>-->
											<div class="container-fluid">
												<div class="row">
													<div class="col-md-12">
														<!--
															Pagination
														-->
														<div class="team-pagination">
														<?php
														if (!$view_myMessages) { ?>
															<a href="javascript:;" class="current">
																<span class="overlay"></span>
																<?php echo '<img class="wproto-wp-image" alt="" width="130" height="130" src="' . BASE . 'public/uploads/users/' . $lastSender->id . '/' . $lastSender->image . '">';
																?>
															</a>
														<?php
														}
														else {
															foreach ($view_myMessages as $myMessage) :
															$sender = User::find($myMessage->sender_id);
														?>

															<a href="javascript:;" class="current">
																<span class="overlay"></span>
																<?php echo '<img class="wproto-wp-image" alt="" width="130" height="130" src="' . BASE . 'public/uploads/users/' . $sender->id . '/' . $sender->image . '">';
																?>
															</a>

														<?php
															endforeach;
														}
														?>
														</div><!--</team-pagination>-->
													</div><!--</col-md-12>-->
												</div><!--</row>-->
											</div><!--</container-fluid>-->
										</div><!--</shortcode-team-members-id-59d94077dca64>-->
									</div><!--</fw-col-xs-12 grid-column>-->
								</div><!--</fw-row>-->
							</div><!--</container>-->
						</div><!--</team>-->
				  	</div><!-- </above-overlay> -->
				</section><!-- </recommendation> Sessão Apresentação Recomendações-->
				<?php endif; ?>

				<!-- ========================================= -->
				<!-- Opportunities (Oportunidades Disponiveis)   -->
				<!-- ========================================= -->
				<section id="opportunities" class="main-block opportunities">
					<div class="container text-center">
						<!-- Opportunities Title -->
						<div class="title-main text-left wow fadeIn">
							<div class="main-title__inner">
								<div class="main-title__left text-right">
									<i class="fa fa-cog mega"></i>
									<h1 class="title-session">Oportunidades</h1>
									<em class="title-description">Oportunidades Perfiladas</em>
								</div><!-- </main-title__left> -->
								<div class="main-title__right">
									<p class="resumo">
										Através de análise do seu perfil, identificamos algumas vagas disponíveis que se enquadram em suas competências. Contudo você pode realizar consultas de todas as vagas disponíveis atualmente cadastradas no sistema.
									</p>
								</div><!-- </main-title__right> -->
							</div><!-- </main-title__inner> -->
						</div><!-- </title-main> -->

						<!-- Opportunities Content -->
						<div class="main-block__padder text-left">
							<div class="row services-list">
							<?php
							if ($view_vagas) :
								$cont = 0;
								foreach ($view_vagas as $vaga) :
									$cont++;
							?>
								<div class="col-lg-5 col-md-6 col-lg-push-1 text-right clearfix wow fadeInLeft">
									<div class="<?php if ($cont % 2 == 0) {
										echo 'pull-right';}
									else { echo 'pull-left';} ?> icone-fa h4 icone-fa-opportunities text-center" href="#" data-toggle="modal" data-target="#modal1">
										<i class="fa fa-puzzle-piece"></i>
									</div>
									<div class="no-overflow">
										<h6 class="text-subtitulo"><?php echo $vaga->profile->profile ?></h6>
										<p class="texto_profileit">
											<?php echo $vaga->company ?> / <?php echo $vaga->contact ?>
										</p>
										<p class="texto_profileit">
											<?php echo $vaga->assignments ?>
										</p>
									</div>
								</div>
							<?php
								endforeach;
							endif;
							?>
							</div><!-- </row services-list> -->
						</div><!-- </main-block__padder> -->
					</div><!-- </container> Opportunities Content -->
				</section><!-- </opportuninities> Section Opportunities-->

				<!-- ==============================================
			   Recommendations (Acc Recomendações)
			   =============================================== -->
				<section id="acc-recommendation" class="main-block acc-recommendation">
					<div class="container text-center">
						<!-- Acc RecommendationTitle -->
						<div class="title-main text-left wow fadeIn">
							<div class="main-title__inner">
								<div class="main-title__left text-right">
									<i class="fa fa-cog mega"></i>
									<h1 class="title-session">Recomendações</h1>
									<em class="title-description">Aprovar as recomendações dos colegas</em>
								</div><!-- </main-title__left> -->
								<div class="main-title__right">
									<p class="resumo">
									Aprove recomendações que foram realizadas por seus colegas, reconhecendo suas competências e conhecimentos. Estas recomendações colaboram para uma melhor apresentação e comprovação de suas experências.
									</p>
								</div><!-- </main-title__right> -->
							</div><!-- </main-title__inner> -->
						</div><!-- </title-main> -->
						<!-- End Title Section -->
						<div class="container-recommendation">
						<?php
						if ($view_user->recommendations) :
							foreach ($view_user->recommendations as $recommendation):
					      if ($recommendation->approved == 2) {
					      	$adviser = User::find($recommendation->adviser_id);
						?>
							<div class="row wrapper-recommended">
								<div class="container-accRecommendation col-sm-6">
									<blockquote>
										<div class="text-left quote-icon"> <i class="fa fa-quote-left"></i> </div>
											<p><?php echo $recommendation->description?></p>
										<div class="text-right quote-icon"> <i class="fa fa-quote-right"></i> </div>
										<small>
											<cite title="John Bostic"><?php echo $adviser->name?></cite>
											<cite title="John Bostic"> - <?php echo $recommendation->charge_recommendation?></cite>
										</small>
									</blockquote>
								</div><!-- </container-accRecommendation> End Blockquote -->
								<!-- Info e Avatar User -->
								<div class="col-sm-3 container-accAvatar">

									<?php
									if (!is_null($view_user->image)) {
			                       echo '<img class="avatar-md quote-slider-img" src="' . BASE . 'public/uploads/users/' .  $recommendation->adviser_id . '/' . $adviser->image . '" >';
			                   }
			                   else{
			                       echo '<img class="avatar-md quote-slider-img" src="' . BASE . 'public/uploads/users/' . 'default' . '/' . 'default.png' . '">';
			                   }
			                   ?>

									<div class="md-padder">
										<p class="texto-cite text-center">
									<?php echo $recommendation->relationship?><br> na função de <br>
									<?php echo $recommendation->charge_recommended?>
										</p>
									</div><!-- </md-padder> -->
								</div><!-- </container-accAvatar> -->
								<div class="col-sm-3 container-aprove">
									<div class="md-padder text-center">
										<button type="button" value="<?php echo $recommendation->id ?>" onclick="appRecommendation(this.value, '<?php echo $view_user->name?>')" class="btn btn-primary btn-sm margin-btm-10" id="btnAPPUp">
											<i class="fa fa-thumbs-up"></i>
										</button>

										<button type="button" value="<?php echo $recommendation->id ?>" onclick="disRecommendation(this.value, '<?php echo $view_user->name?>')" class="btn btn-primary btn-sm margin-btm-10" id="btnAPPDown">
											<i class="fa fa-thumbs-down"></i>
										</button>
									</div><!-- </md-padder> -->
								</div><!-- </container-aprove> -->
							</div><!--</row wrapper-recommended> -->
						<?php
								}
							endforeach;
						endif;
						?>
						</div><!-- </container-recommendation> -->
					</div><!-- </container> -->
				</section><!-- </opportunities> -->
				<!-- ==============================================
				Contact-Me (Contate-me ou add uma Recomendação)
		      =============================================== -->
				<section id="contact-area">
				    <div class="overlay-contactme"></div>
				    <div class="container">
				        <div class="row">
				            <div class="col-md-offset-2 col-md-8 col-sm-12">
									<div class="section-title wow bounceIn">
									   <div class="text-center">
									      <h2>Adicionar Nova Oportunidade de Trabalho</h2>
									      <p class="texto_profileit wow fadeInUp" data-wow-delay="0.5s">Adicione um nova oportunidade de emprego e recomende a comunidade. Desta forma, contribuindo para o desenvolvimento e a integração de sua rede de relacionamentos.</p>
									  </div><!-- </text-center> -->
									</div><!-- </section-title> -->
									<div class="contact-form wow fadeInUp" data-wow-delay="0.8s">
									   <form action="#" method="post">
									       <div class="col-xs-11 col-md-12 text-center centered">
									       	<a class="btn envio" name="btnAddVaga" id="btnAddVaga" href="#" data-toggle="modal" data-target="#modal10"> <i class="fa fa-archive"></i> <span class="hidden-xs">Adicionar  </span> Oportunidade </a>
									       </div>
									   </form>
									</div><!-- </contact-form> -->
				            </div><!-- </cols> Colunas de Grid -->
				        </div><!-- </row> -->
				    </div><!-- </container -->
				</section><!-- </contact-me> Final Sessão de Nova Oportunidade -->
			</main><!-- Main End (Final do Corpo de Conteúdo) -->