		<!-- ==============================================
		Layout Content Site (Definição de Layout)
		====================================-->
		<div class="layout">
			<!-- ==============================================
			Main Start (Inicio do Corpo de Conteúdo)
			=============================================== -->
			<main>												
				<!-- ========================================= -->
				<!--Section Menu Access(Menu de Acesso Rápido)                            -->
				<!-- ========================================= -->				
				<section class="update-menu">
					<div class="container">
						<div class="options-menu">										
							<a class="item-central pointer-cursor" href="home.html">
								<img src="<?php echo IMAGES; ?>curriculo-tag-miolo.png" alt="Curriculo TAG">
							</a>

							<a class="icone-lapis pointer-cursor" href="update.html">
								<i class="fa fa-pencil" alt="Update Profile"></i>
							</a>

							<a class="icone-codigo pointer-cursor" href="home.html">
								<i class="fa fa-industry"></i>
							</a>

							<a class="icone-coracao pointer-cursor" href="home.html">
								<i class="fa fa-question"></i>
							</a>

							<a class="icone-compartilhar pointer-cursor" href="#" data-toggle="modal" data-target="#modal3">
								<i class="fa fa-users"></i>
							</a>
						</div><!-- </options-menu> -->						
					</div><!-- </container> -->
				</section><!-- </update-menu> --> 
				<!-- ========================================= -->
				<!--Section Profile(Resumo Profile)            -->
				<!-- ========================================= -->
				<section id="profile" class="head-block">
					<div class="container text-center">
						<!-- ========================================= -->
						<!-- Conteúdo Perfil                           -->
						<!-- ========================================= -->
						<div class="row head-block__padder text-left">
							<!-- Foto Perfil -->
							<div class="col-lg-4 col-md-6 col-lg-push-4 text-center wow fadeInUp">
								<div class="inline-block photo-column-inner">
									<div class="photo-profile">
										<img src="<?php echo IMAGES; ?>photo.png" class="img-responsive" alt="#">
									</div>
									<div class="md-padder">
										<a class="btn btn-primary btn-lg margin-btm-30" href="update.html" target="_blank"> <i class="fa fa-user"></i> <span class="hidden-xs"> View </span> Profile </a>
									</div>
								</div>
							</div><!-- Container Foto Perfil -->

							<!-- #Informações Perfis Pessoais -->
							<div class="col-lg-4 col-md-6 col-lg-pull-4 info-column wow fadeInUp">
								<div>
									<h5 class="text-subtitulo">personal info</h5>
									<ul class="padder list-unstyled home-infolist">
										<li>Calculation of experience</li>
										<li>Suggested upgrades</li>
										<li>Unfilled items </li>
									</ul>
									<div class="col-md-12 col-md-offset-0 text-uppercase">
										<!-- SKILL TITLE -->
										<h5 class="text-subtitulo">Full Profile</h5>

										<!-- Force Meter -->
										<div class="force-meter xs-padder">
											<div class="on"></div>
											<div class="on"></div>
											<div class="on"></div>
											<div></div>
											<div></div>
										</div><!-- </Force Meter> -->
									</div><!-- </> Final Barra Força Perfil-->

								</div>
							</div><!-- Container Informações Perfil -->

							<!-- Presentation ticket -->
							<div class="col-lg-4 col-xs-12 text-left story-column wow fadeInUp">
								
								<div class="container-hive wow fadeIn" data-wow-delay="2s"><h5 class="text-subtitulo text-center">Network</h5>
									<!-- Apresentação de Avatares network -->
									<div class="row">
										<div class="line-hive">
											<div class="hive-contact">
												<div class="avatar-molde">
													<img class="avatar-picture wow bounceIn" src="<?php echo IMAGES; ?>profiles/1.jpg" >
												</div>
												<div class="avatar-molde">
													<img class="avatar-picture wow bounceIn" src="<?php echo IMAGES; ?>profiles/11.jpg" >
												</div>
												<div class="avatar-molde">
													<img class="avatar-picture wow bounceIn" src="<?php echo IMAGES; ?>profiles/3.jpg" >
												</div>
												<div class="avatar-molde">
													<img class="avatar-picture wow bounceIn" src="<?php echo IMAGES; ?>profiles/4.jpg" >
												</div>											
											</div>
										</div>
									</div>
									<div class="row">
										<div class="line-hive">
											<div class="hive-contact">
												<div class="avatar-molde">
													<img class="avatar-picture wow bounceIn" src="<?php echo IMAGES; ?>profiles/10.jpg" >
												</div>
												<div class="avatar-molde">
													<img class="avatar-picture wow bounceIn" src="<?php echo IMAGES; ?>profiles/6.jpg" >
												</div>
												<div class="avatar-molde">
													<img class="avatar-picture wow bounceIn" src="<?php echo IMAGES; ?>profiles/7.jpg" >
												</div>
												<div class="avatar-molde">
													<img class="avatar-picture wow bounceIn" src="<?php echo IMAGES; ?>profiles/8.jpg" >
												</div>											
											</div>
										</div>
									</div>
									<div class="row">
										<div class="line-hive">
											<div class="hive-contact">
												<div class="avatar-molde">
													<img class="avatar-picture wow bounceIn" src="<?php echo IMAGES; ?>profiles/13.jpg" >
												</div>
												<div class="avatar-molde">
													<img class="avatar-picture wow bounceIn" src="<?php echo IMAGES; ?>profiles/5.jpg" >
												</div>
												<div class="avatar-molde">
													<img class="avatar-picture wow bounceIn" src="<?php echo IMAGES; ?>profiles/2.jpg" >
												</div>
												<div class="avatar-molde">
													<img class="avatar-picture wow bounceIn" src="<?php echo IMAGES; ?>profiles/12.jpg" >
												</div>											
											</div>
										</div>
									</div>
									<div class="row">
										<div class="line-hive">
											<div class="hive-contact">
												<div class="avatar-molde">
													<img class="avatar-picture wow bounceIn" src="<?php echo IMAGES; ?>profiles/14.jpg" >
												</div>
												<div class="avatar-molde">
													<img class="avatar-picture wow bounceIn" src="<?php echo IMAGES; ?>profiles/9.jpg" >
												</div>
												<div class="avatar-molde">
													<img class="avatar-picture wow bounceIn" src="<?php echo IMAGES; ?>profiles/15.jpg" >
												</div>
												<div class="avatar-molde">
													<img class="avatar-picture wow bounceIn" src="<?php echo IMAGES; ?>profiles/16.jpg" >
												</div>											
											</div>
										</div>
									</div>
								</div>
							</div><!-- Container Bilhete de Apresentação -->
						</div><!-- </main-block__padder> -->
					</div><!-- </container> -->
				</section><!-- </section> Profile -->
				<!-- ========================================= -->
				<!-- Opportuties (Oportunidades Disponiveis)   -->
				<!-- ========================================= -->
				<section id="opportunities" class="main-block">
					<div class="container text-center">						
						<!-- Opportunities Title -->
						<div class="title-main text-left wow fadeIn">
							<div class="main-title__inner">
								<div class="main-title__left text-right">
									<i class="fa fa-cog mega"></i>
									<h1 class="title-session">Opportunities</h1>
									<em class="title-description">what my clients get</em>									
								</div><!-- </main-title__left> -->
								<div class="main-title__right">
									<p class="resumo">
										Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer.
									</p>
								</div><!-- </main-title__right> -->
							</div><!-- </main-title__inner> -->
						</div><!-- </title-main> -->

						<!-- Opportunities Content -->
						<div class="main-block__padder text-left">
							<div class="row services-list">
								<div class="col-lg-5 col-md-6 col-lg-push-1 text-right clearfix wow fadeInLeft">
									<div class="pull-right icone-fa h4 icone-fa-opportunities text-center" href="#" data-toggle="modal" data-target="#modal1">
										<i class="fa fa-wrench"></i>
									</div>
									<div class="no-overflow">
										<h6 class="text-subtitulo">web design</h6>
										<p class="texto_profileit">
											Lorem Ipsum is simply dummy text of the printing and typesetting industry.
										</p>
									</div>
								</div>
								<div class="col-lg-5 col-md-6 col-lg-push-1 clearfix wow fadeInRight">
									<div class="pull-left icone-fa h4 icone-fa-opportunities text-center" href="#" data-toggle="modal" data-target="#modal1">
										<i class="fa fa-wrench"></i>
									</div>
									<div class="no-overflow">
										<h6 class="text-subtitulo">web development</h6>
										<p class="texto_profileit">
											Lorem Ipsum is simply dummy text of the printing and typesetting industry.
										</p>
									</div>
								</div>
								<div class="col-lg-5 col-md-6 col-lg-push-1 text-right clearfix wow fadeInLeft">
									<div class="pull-right icone-fa h4 icone-fa-opportunities text-center" href="#" data-toggle="modal" data-target="#modal1">
										<i class="fa fa-wrench"></i>
									</div>
									<div class="no-overflow">
										<h6 class="text-subtitulo">branding</h6>
										<p class="texto_profileit">
											Lorem Ipsum is simply dummy text of the printing and typesetting industry.
										</p>
									</div>
								</div>
								<div class="col-lg-5 col-md-6 col-lg-push-1 clearfix wow fadeInRight">
									<div class="pull-left icone-fa h4 icone-fa-opportunities text-center" href="#" data-toggle="modal" data-target="#modal1">
										<i class="fa fa-wrench"></i>
									</div>
									<div class="no-overflow">
										<h6 class="text-subtitulo">marketing</h6>
										<p class="texto_profileit">
											Lorem Ipsum is simply dummy text of the printing and typesetting industry.
										</p>
									</div>
								</div>
								<div class="col-lg-5 col-md-6 col-lg-push-1 text-right clearfix wow fadeInLeft">
									<div class="pull-right icone-fa h4 icone-fa-opportunities text-center" href="#" data-toggle="modal" data-target="#modal1">
										<i class="fa fa-wrench"></i>
									</div>
									<div class="no-overflow">
										<h6 class="text-subtitulo">website installation</h6>
										<p class="texto_profileit">
											Lorem Ipsum is simply dummy text of the printing and typesetting industry.
										</p>
									</div>
								</div>
								<div class="col-lg-5 col-md-6 col-lg-push-1 clearfix wow fadeInRight">
									<div class="pull-left icone-fa h4 icone-fa-opportunities text-center" href="#" data-toggle="modal" data-target="#modal1">
										<i class="fa fa-wrench"></i>
									</div>
									<div class="no-overflow">
										<h6 class="text-subtitulo">support my products</h6>
										<p class="texto_profileit">
											Lorem Ipsum is simply dummy text of the printing and typesetting industry.
										</p>
									</div>
								</div>
							</div><!-- </row services-list> -->
						</div><!-- </main-block__padder> -->
					</div><!-- </container> -->
				</section><!-- </opportuninities> Section Opportunities-->
				<!-- ==============================================
			   Recommendations (Acc Recomendações)
			   =============================================== -->
				<section id="acc-recommendation" class="main-block">
					<div class="container text-center">					
						<!-- Acc RecommendationTitle -->
						<div class="title-main text-left wow fadeIn">
							<div class="main-title__inner">
								<div class="main-title__left text-right">
									<i class="fa fa-cog mega"></i>
									<h1 class="title-session">Recommendations</h1>
									<em class="title-description">Approve colleagues' recommendations</em>								
								</div><!-- </main-title__left> -->
								<div class="main-title__right">
									<p class="resumo">
									Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer.
									</p>
								</div><!-- </main-title__right> -->
							</div><!-- </main-title__inner> -->
						</div><!-- </title-main> -->
						<!-- End Title Section -->        

						<div class="container-recommendation">
							<?php foreach ($view_user->recommendations as $recommendation):
					      	if ($recommendation->approved == 2) {
					      		$adviser = User::find($recommendation->adviser_id);
							?>
								<div class="row">
									<div class="container-accRecommendation col-sm-6">
										<blockquote>
											<div class="text-left quote-icon"> <i class="fa fa-quote-left"></i> </div>
												<p><?php echo $recommendation->description?></p>
											<div class="text-right quote-icon"> <i class="fa fa-quote-right"></i> </div>
											<small>
												<cite title="John Bostic"><?php echo $adviser->name?></cite>
												<cite title="John Bostic"> - <?php echo $recommendation->charge_recomendation?></cite>
											</small>
										</blockquote>
									</div><!-- </container-accRecommendation> End Blockquote -->
									<!-- Info e Avatar User -->
									<div class="col-sm-3 container-accAvatar">        
										
										<?php
										if (!is_null($view_user->image)) {
				                       echo '<img class="avatar-md quote-slider-img" src="' . BASE . 'public/uploads/users/' .  $recommendation->adviser_id . '/' . $adviser->image . '" >';
				                   }
				                   else{
				                       echo '<img class="avatar-md quote-slider-img" src="' . BASE . 'public/uploads/users/' . 'default' . '/' . 'default.png' . '">';
				                   }
				                   ?>

										<div class="md-padder">
											<p class="texto-cite text-center">
										<?php echo $recommendation->relationship?><br> na função de <br>
										<?php echo $recommendation->charge_recommended?>
											</p>
										</div><!-- </md-padder> -->					                		
									</div><!-- </container-accAvatar> -->
									<div class="col-sm-3 container-aprove">
										<div class="md-padder text-center">
											<a class="btn btn-primary btn-sm margin-btm-10" href="update.html" target="_blank"> <i class="fa fa-thumbs-up"></i> </a>
											<a class="btn btn-primary btn-sm margin-btm-10" href="update.html" target="_blank"> <i class="fa fa-thumbs-down"></i> </a>
										</div><!-- </md-padder> -->				                		
									</div><!-- </container-aprove> -->
								</div><!--</row> -->
								<?php
									}
								endforeach
								?>	
						</div><!-- </container-recommendation> --> 
					</div><!-- </container> -->
				</section><!-- </opportunities> -->	

				<!-- ==============================================
				Contact-Me (Contate-me ou add uma Recomendação)
		      =============================================== -->
				<section id="contact-area">
				    <div class="overlay-contactme"></div>
				    <div class="container">
				        <div class="row">
				            <div class="col-md-offset-2 col-md-8 col-sm-12">
									<div class="section-title wow bounceIn">
									   <div class="text-center">
									      <h2>Add New Job Opportunity</h2>
									      <p class="texto_profileit wow fadeInUp" data-wow-delay="0.5s">Add um nova oportunidade de emprego recoemendada a comunidade Incluindo novas vagas você contribui para o desenvolvimento e a integração de sua rede de relacionamentos.</p>
									  </div><!-- </text-center> -->
									</div><!-- </section-title> -->
									<div class="contact-form wow fadeInUp" data-wow-delay="0.8s">
									   <form action="#" method="post">
									       <div class="col-xs-11 col-md-12 text-center centered">
									       	<a class="btn envio" href="#" data-toggle="modal" data-target="#modal2"> <i class="fa fa-paper-plane"></i> <span class="hidden-xs">Add  </span> Opportunity </a>	
									       </div>
									   </form>
									</div><!-- </contact-form> -->
				            </div><!-- </cols> Colunas de Grid -->
				        </div><!-- </row> -->
				    </div><!-- </container -->
				</section><!-- </contact-me> Final Sessão de Nova Oportunidade -->
			</main><!-- Main End (Final do Corpo de Conteúdo) -->