<!DOCTYPE html>
<html lang="pt-br">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<title>Login - ProfileIT </title>

      <!-- ==============================================
      CSS
      ================================================== -->
		<link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Roboto:400,100,300,500"> 
      <link rel="stylesheet" type="text/css" href="<?php echo CSS; ?>plugins.css" />      
      <link rel="stylesheet" type="text/css" href="<?php echo CSS; ?>login.css" />

		<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
		<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
		<!--[if lt IE 9]>
	   <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
	   <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
	   <![endif]-->

	</head>

   <body>
   	<!-- Top menu -->
   	<nav class="navbar navbar-inverse navbar-no-bg" role="navigation">
   		<div class="container">
   			<div class="navbar-header">
   				<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#top-navbar-1">
   					<span class="sr-only">Toggle navigation</span>
   					<span class="icon-bar"></span>
   					<span class="icon-bar"></span>
   					<span class="icon-bar"></span>
   				</button>
   				<a class="navbar-brand" href="index.html"></a>
   			</div><!-- </navbar-header> -->
   			<!-- Collect the nav links, forms, and other content for toggling -->
   			<div class="collapse navbar-collapse" id="top-navbar-1">
   				<ul class="nav navbar-nav navbar-right">
   					<li>
   						<span class="li-text">
   							Recuperar
   						</span>
   						<a href="<?php echo BASE . 'recuperar/'; ?>"><strong>aqui</strong></a>
   						<span class="li-text">
   							, senha de acesso:
   						</span>
   						<span class="li-social">
                        <a href="<?php echo BASE . 'recuperar/'; ?>"><i class="fa fa-recycle"></i></a>
   							<a href="#"><i class="fa fa-facebook"></i></a>
   							<a href="#"><i class="fa fa-twitter"></i></a>
   							<a href="#"><i class="fa fa-envelope"></i></a>
   							<a href="#"><i class="fa fa-github"></i></a>
   						</span>
   					</li>
   				</ul><!-- </nav navbar-nav navbar-right> -->
   			</div><!-- </collapse navbar-collapse> -->
   		</div><!-- </container> -->
   	</nav><!-- </navbar navbar-inverse navbar-no-bg> -->