   	<!-- Top content -->
   	<div class="top-content">
   		<div class="inner-bg">
   			<div class="container">
   				<div class="row">
   					<div class="col-sm-8 col-sm-offset-2 form-box">
                     <?php echo (isset($this->alert) ? $this->alert : ''); ?>   						
                     <form class="form-user clearfix" role="form" data-toggle="validator" action="<?php echo BASE; ?>login/logar/" method="post"> 
                        <p>
                           <input type="text" name="username" id="username" value="<?php echo $this->request->post('username') ?>" placeholder="Username">       
                           <input type="password" name="password" id="password" placeholder="Your Password">
                        </p>
                        <button type="submit" name="submit">
                           <i class="fa fa-arrow-right"></i>
                           <span>Sign In</span>
                        </button>  
                        <a href="<?php echo BASE . 'cadastro'; ?>" >     
                           <button type="button" id="register" value="register" name="register">   
                              <i class="fa fa-user"></i>
                              <span>Sign Up</span>
                           </button>
                        </a>
                     </form><!-- </form-user> -->
   					</div><!-- </form-box> -->
   				</div><!-- </row> -->
   			</div><!-- </container> -->
   		</div><!-- </inner-bg> -->
   	</div><!-- </top-content> -->