<!doctype html>
<html lang="pt-br">
<head>	
	<meta charset="utf-8">

	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta name="description" content="Login Usuarios: Rede Colaborativa Profissional" />
	<meta name="keywords" content="networkingTI, profissional, profile, indicacao, rede social profissional" />

	<meta name="author" content="Elisandro M. Corrêa">
	<meta name="generator" content="Sistema Profile IT">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title><?php echo $view_title; ?></title>
	
	<!--
    Favicon para todos os formatos
     -->
	<link rel="apple-touch-icon" sizes="57x57" href="<?php echo IMG; ?>/favicon/apple-icon-57x57.png">
	<link rel="apple-touch-icon" sizes="60x60" href="<?php echo IMG; ?>/favicon/apple-icon-60x60.png">
	<link rel="apple-touch-icon" sizes="72x72" href="./favicon/apple-icon-72x72.png">
	<link rel="apple-touch-icon" sizes="76x76" href="<?php echo IMG; ?>/favicon/apple-icon-76x76.png">
	<link rel="apple-touch-icon" sizes="114x114" href="<?php echo IMG; ?>/favicon/apple-icon-114x114.png">
	<link rel="apple-touch-icon" sizes="120x120" href="<?php echo IMG; ?>/favicon/apple-icon-120x120.png">
	<link rel="apple-touch-icon" sizes="144x144" href="<?php echo IMG; ?>/favicon/apple-icon-144x144.png">
	<link rel="apple-touch-icon" sizes="152x152" href="<?php echo IMG; ?>/favicon/apple-icon-152x152.png">
	<link rel="apple-touch-icon" sizes="180x180" href="<?php echo IMG; ?>/favicon/apple-icon-180x180.png">
	<link rel="icon" type="image/png" sizes="192x192"  href="<?php echo IMG; ?>/favicon/android-icon-192x192.png">
	<link rel="icon" type="image/png" sizes="32x32" href="<?php echo IMG; ?>/favicon/favicon-32x32.png">
	<link rel="icon" type="image/png" sizes="96x96" href="<?php echo IMG; ?>/favicon/favicon-96x96.png">
	<link rel="icon" type="image/png" sizes="16x16" href="<?php echo IMG; ?>/favicon/favicon-16x16.png">
	<link rel="manifest" href="<?php echo IMG; ?>favicon/manifest.json">
	<meta name="msapplication-TileColor" content="#ffffff">
	<meta name="msapplication-TileImage" content="/ms-icon-144x144.png">
	<meta name="theme-color" content="#ffffff">
	<!--Final área de favicon -->



	<link rel="stylesheet" href="<?php echo BOWER; ?>bootstrap/dist/css/bootstrap.min.css" type="text/css">
	<link rel="stylesheet" href="<?php echo BOWER; ?>font-awesome/css/font-awesome.min.css" type="text/css">
	<!--<link rel="stylesheet" href="<?php echo CSS; ?>main.css" type="text/css">-->

	<link rel="stylesheet" type="text/css" href="<?php echo CSS; ?>style/nav.css" />
	<link rel="stylesheet" type="text/css" href="<?php echo CSS; ?>style/footer.css" />
	<link rel="stylesheet" type="text/css" href="<?php echo CSS; ?>style/copyright.css" />
	<link rel="stylesheet" type="text/css" href="<?php echo CSS; ?>style/social.css" />
    <link rel="stylesheet" type="text/css" href="<?php echo CSS; ?>login/login.css" />




	<script src="<?php echo BOWER; ?>jquery/dist/jquery.min.js"></script>
	<?php 
		echo $add_css;
		echo $add_js;
	?>
</head>
<body>


	<!-- ==============================================
	    Navbar
	=============================================== -->
	<div id="home-nav" class="navbar navbar-default navbar-fixed-top" role="navigation">
		 <div class="container">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1"> <span class="sr-only">Toggle navigation</span> <span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> </button>
			    <a class="navbar-brand" href="#home"> 
				    <!-- Logo Header -->
				    <section id="foxin" class="foxin">
				    	<div> <img src="<?php echo IMG; ?>logo.png" alt="Foxin by Elisandro Mello"> </div>
				    </section>
				    <!--/ Logo Header--> 
			    </a>
			</div>
			<div class="navbar-collapse collapse" id="bs-example-navbar-collapse-1">
				<ul class="nav navbar-nav navbar-right">
			    	<li><a href="/inicial/login">Home</a></li>
			        <li><a href="recuperar">Recover Password</a></li>
			        <li><a href="#history">Policy</a></li>
			        <li><a href="#contact">Contact</a></li>
			    </ul>
			</div>
		</div>
	</div>



	<div class="container">
		    <div class="row">
		        <!--<div class="col-md-6 col-md-offset-3">
		            <div class="panel panel-custom">-->
