<!doctype html>
<html lang="pt-br">
<head>	
	<meta charset="utf-8">

	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta name="description" content="Login Usuarios: Rede Colaborativa Profissional" />
	<meta name="keywords" content="networkingTI, profissional, profile, indicacao, rede social profissional" />

	<meta name="author" content="Elisandro M. Corrêa">
	<meta name="generator" content="Sistema Profile IT">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title><?php echo $view_title; ?></title>
	
	<!--
    Favicon para todos os formatos
     -->
	<link rel="apple-touch-icon" sizes="57x57" href="<?php echo IMG; ?>/favicon/apple-icon-57x57.png">
	<link rel="apple-touch-icon" sizes="60x60" href="<?php echo IMG; ?>/favicon/apple-icon-60x60.png">
	<link rel="apple-touch-icon" sizes="72x72" href="./favicon/apple-icon-72x72.png">
	<link rel="apple-touch-icon" sizes="76x76" href="<?php echo IMG; ?>/favicon/apple-icon-76x76.png">
	<link rel="apple-touch-icon" sizes="114x114" href="<?php echo IMG; ?>/favicon/apple-icon-114x114.png">
	<link rel="apple-touch-icon" sizes="120x120" href="<?php echo IMG; ?>/favicon/apple-icon-120x120.png">
	<link rel="apple-touch-icon" sizes="144x144" href="<?php echo IMG; ?>/favicon/apple-icon-144x144.png">
	<link rel="apple-touch-icon" sizes="152x152" href="<?php echo IMG; ?>/favicon/apple-icon-152x152.png">
	<link rel="apple-touch-icon" sizes="180x180" href="<?php echo IMG; ?>/favicon/apple-icon-180x180.png">
	<link rel="icon" type="image/png" sizes="192x192"  href="<?php echo IMG; ?>/favicon/android-icon-192x192.png">
	<link rel="icon" type="image/png" sizes="32x32" href="<?php echo IMG; ?>/favicon/favicon-32x32.png">
	<link rel="icon" type="image/png" sizes="96x96" href="<?php echo IMG; ?>/favicon/favicon-96x96.png">
	<link rel="icon" type="image/png" sizes="16x16" href="<?php echo IMG; ?>/favicon/favicon-16x16.png">
	<link rel="manifest" href="<?php echo IMG; ?>favicon/manifest.json">
	<meta name="msapplication-TileColor" content="#ffffff">
	<meta name="msapplication-TileImage" content="/ms-icon-144x144.png">
	<meta name="theme-color" content="#ffffff">
	<!--Final área de favicon -->



	<link rel="stylesheet" href="<?php echo BOWER; ?>bootstrap/dist/css/bootstrap.min.css" type="text/css">
	<link rel="stylesheet" href="<?php echo BOWER; ?>font-awesome/css/font-awesome.min.css" type="text/css">
	<link rel="stylesheet" href="<?php echo CSS; ?>main.css" type="text/css">

	<link rel="stylesheet" type="text/css" href="<?php echo CSS; ?>style/style.css" />
	


	<script src="<?php echo BOWER; ?>jquery/dist/jquery.min.js"></script>
	<?php 
		echo $add_css;
		echo $add_js;
	?>

</head>
<body>
	<div class="container">
		    <div class="row">
		        <div class="col-md-6 col-md-offset-3">
		            <div class="panel panel-custom">
		                <div class="panel-heading">
		                    <a id="logo" href="<?php echo BASE; ?>">
		                        <img class="img-responsive" src="<?php echo IMG; ?>hxphp-logo.png" alt="">
		                    </a>
		                </div>

						<!--Conteudo-->
		                <div class="panel-body">
		                    <h4 class="alert alert-success">
		                        Uhull! Você instalou e configurou o HXPHP Framework com sucesso!
		                    </h4>
		                    <p>
		                        Agora acesse a <a class="btn btn-success btn-xs" href="http://www.hxtutors.com.br/curso/dominando-o-hxphp-framework/" title="Acesse o curso completo sobre HXPHP" target="_blank">área de membros</a> e assista ao nosso curso oficial para dominar completamente esta poderosa ferramenta.
		                    </p>
		                </div>

						   <!--Footer -->	
			        </div> <!--/panel-custom -->	
			    </div> <!--/class="col-md-6 col-md-offset-3 -->	
			</div> <!--row-->
	</div>
	
	<div class="container">
		<div class="row">
			<div class="col-md-4 col-md-offset-4 text-center">
				HXPHP <?php echo date("Y"); ?> &copy; - Todos os direitos reservados
			</div>
		</div>
	</div>


	<!-- ==============================================
	   Créditos (Credits)
	=============================================== --> 
	<section class="copyright">
	  <div class="container">
	    <div class="col-md-12">
	      <div class="text-center"> 
	        <!-- Logo Header -->
	        <section id="fox_footer" class="fox_footer">
	          <div> <img src="<?php echo IMG; ?>logofooter.png" alt="Foxin by Elisandro Mello">  - &copy;<script>document.write(new Date().getFullYear())</script> - Designer codificado e projetado por <i class="fa fa-cloud-upload"></i> Elisandro Mello</div>
	          
	        </section>
	        <!--/ Logo Header-->
	      </div>
	    </div>
	  </div>
	</section>



	<script src="<?php echo BOWER; ?>bootstrap/dist/js/bootstrap.min.js"></script>
</body>
</html>

